(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/s034-return-cargo-shed/wrench-contact-master.xcf" "visual-novel/art/scene-studies/s034-return-cargo-shed/wrench-contact-master.xcf")))
       (flat (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE))))
 (file-png-save RUN-NONINTERACTIVE im flat "/tmp/s034-master-reopened-native.png" "/tmp/s034-master-reopened-native.png" 0 9 0 0 0 0 0)
 (gimp-image-crop im 1664 936 4 2)
 (gimp-context-set-interpolation INTERPOLATION-NOHALO)
 (gimp-image-scale im 1920 1080)
 (file-png-save RUN-NONINTERACTIVE im flat "visual-novel/renpy/game/art/scenes/s034-return-cargo-shed.png" "visual-novel/renpy/game/art/scenes/s034-return-cargo-shed.png" 0 9 0 0 0 0 0)
 (gimp-image-delete im))
(gimp-quit 0)
