(let* ((img (car (gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/s054-throne-hall/hall-rectangular-candidate.png" "source")))
       (base (car (gimp-image-get-active-layer img)))
       (head (car (gimp-file-load-layer RUN-NONINTERACTIVE img "visual-novel/art/scene-studies/s054-throne-hall/valcair-attention-component.png"))))
 (gimp-item-set-name base "Original rectangular hall, bodies, hands and weapons")
 (gimp-image-insert-layer img head 0 0)
 (gimp-item-set-name head "Valcair head only, current portrait identity facing Tessa")
 (gimp-image-select-polygon img CHANNEL-OP-REPLACE 16 (vector 1165 55 1300 25 1388 47 1388 188 1330 242 1215 242 1170 179 1162 100))
 (gimp-selection-feather img 3)
 (let ((mask (car (gimp-layer-create-mask head ADD-BLACK-MASK))))
  (gimp-layer-add-mask head mask)
  (gimp-context-set-foreground '(255 255 255))
  (gimp-edit-fill mask FOREGROUND-FILL))
 (gimp-selection-none img)
 (gimp-xcf-save RUN-NONINTERACTIVE img head "visual-novel/art/scene-studies/s054-throne-hall/hall-local-master.xcf" "master")
 (let* ((copy (car (gimp-image-duplicate img))) (flat (car (gimp-image-merge-visible-layers copy CLIP-TO-IMAGE))))
  (file-png-save RUN-NONINTERACTIVE copy flat "/tmp/s054-head-corrected.png" "review" 0 9 0 0 0 0 0)
  (gimp-image-resize copy 1952 1098 110 50)
  (let ((bg (car (gimp-layer-new copy 1952 1098 RGB-IMAGE "Framing guide margins" 100 NORMAL-MODE))))
   (gimp-image-insert-layer copy bg 0 1)
   (gimp-context-set-foreground '(126 129 130))
   (gimp-drawable-fill bg FOREGROUND-FILL))
  (let ((guide (car (gimp-image-merge-visible-layers copy CLIP-TO-IMAGE))))
   (file-png-save RUN-NONINTERACTIVE copy guide "/tmp/s054-framing-guide.png" "guide" 0 9 0 0 0 0 0))
  (gimp-image-delete copy))
 (gimp-image-delete img))
