(let* ((img (car (gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/s054-throne-hall/hall-local-master.xcf" "master")))
       (part (car (gimp-file-load-layer RUN-NONINTERACTIVE img "visual-novel/art/scene-studies/s054-throne-hall/rear-release-component.png"))))
 (gimp-image-insert-layer img part 0 0)
 (gimp-context-set-interpolation INTERPOLATION-NOHALO)
 (gimp-layer-scale part 710 425 FALSE)
 (gimp-layer-set-offsets part 510 175)
 (gimp-item-set-name part "Entrance release behind throne at left; old front-right mount removed")
 (gimp-image-select-rectangle img CHANNEL-OP-REPLACE 815 312 78 175)
 (gimp-image-select-rectangle img CHANNEL-OP-ADD 1044 326 65 168)
 (gimp-selection-feather img 2)
 (gimp-image-select-polygon img CHANNEL-OP-SUBTRACT 20 (vector 686 489 815 438 838 446 847 439 1223 348 1223 362 850 458 839 456 822 468 700 491))
 (let ((mask (car (gimp-layer-create-mask part ADD-BLACK-MASK))))
  (gimp-layer-add-mask part mask)
  (gimp-context-set-foreground '(255 255 255))
  (gimp-edit-fill mask FOREGROUND-FILL))
 (gimp-selection-none img)
 (gimp-xcf-save RUN-NONINTERACTIVE img part "visual-novel/art/scene-studies/s054-throne-hall/hall-local-master.xcf" "master")
 (let* ((copy (car (gimp-image-duplicate img))) (flat (car (gimp-image-merge-visible-layers copy CLIP-TO-IMAGE))))
  (file-png-save RUN-NONINTERACTIVE copy flat "/tmp/s054-low-dais-release.png" "review" 0 9 0 0 0 0 0)
  (gimp-image-resize copy 1952 1098 110 50)
  (let ((bg (car (gimp-layer-new copy 1952 1098 RGB-IMAGE "Framing guide margins" 100 NORMAL-MODE))))
   (gimp-image-insert-layer copy bg 0 1)
   (gimp-context-set-foreground '(126 129 130))
   (gimp-drawable-fill bg FOREGROUND-FILL))
  (let ((guide (car (gimp-image-merge-visible-layers copy CLIP-TO-IMAGE))))
   (file-png-save RUN-NONINTERACTIVE copy guide "/tmp/s054-framing-guide.png" "guide" 0 9 0 0 0 0 0))
  (gimp-image-delete copy))
 (gimp-image-delete img))
