#!/usr/bin/env python3
"""Deterministic Fountain-to-Ren'Py adaptation, preserving every source block.

This handles the project's deliberately simple Fountain subset. Unknown syntax
fails loudly. Generated dialogue is not a place to edit the screenplay.
"""
from pathlib import Path
import argparse
import hashlib
import json
import re

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / 'screenplay/original-timeline/source.fountain'
GAME = ROOT / 'visual-novel/renpy/game'
CHAPTERS = [(1, 'Rovel'), (6, 'Bellweir'), (10, 'The broken promise'),
            (18, 'Gray Scar'), (26, 'Across the river'), (32, 'Harrow'),
            (38, 'After Harrow'), (44, 'The witness'), (50, 'The citadel'),
            (58, 'Bellweir again')]
ROUNDS = {5: 1, 17: 2, 31: 3, 43: 4, 49: 5}


def q(value):
    return json.dumps(value, ensure_ascii=False)


def pages(text, limit=270):
    # Break long action blocks at sentences, never silently shorten them.
    sentences = re.split(r'(?<=[.!?]) (?=[A-Z“])', text)
    result, current = [], ''
    for sentence in sentences:
        if current and len(current) + len(sentence) + 1 > limit:
            result.append(current)
            current = ''
        current += (' ' if current else '') + sentence
    if current:
        result.append(current)
    if any(len(p) > 410 for p in result):
        raise ValueError('Review a paragraph too long for the reading panel: ' + text)
    return result


def adapt():
    raw = SOURCE.read_text()
    lines = raw.splitlines()
    starts = [i for i, l in enumerate(lines) if re.match(r'^(INT\.|EXT\.) ', l)]
    assert len(starts) == 58
    out = ['# Generated by tools/adapt_screenplay.py; edit source or adapter, not this file.', '']
    scenes, speakers = [], set()
    for n, begin in enumerate(starts, 1):
        end = starts[n] if n < len(starts) else len(lines)
        chapter = max(i for i, (first, _) in enumerate(CHAPTERS, 1) if first <= n)
        title = CHAPTERS[chapter - 1][1]
        heading = lines[begin]
        location = re.sub(r'^(INT\.|EXT\.) ', '', heading).replace(' - ', ' · ').title()
        scene = {'id': f'S{n:03}', 'chapter': chapter, 'heading': heading,
                 'line': begin + 1, 'end': end, 'blocks': []}
        out += [f'label s{n:03}:', f'    $ current_scene = {n}',
                f'    $ current_chapter = {chapter}', f'    $ scene_location = {q(location)}',
                '    $ scene_art = None', '    $ scene_art_alt = ""']
        if n == CHAPTERS[chapter - 1][0]:
            out += [f'    call chapter_card({chapter}, {q(title)})']
        out += ['    show screen story_stage', f'    $ scene_heading = {q(location)}']
        i = begin + 1
        while i < end:
            if not lines[i].strip():
                i += 1
                continue
            start = i
            block = []
            while i < end and lines[i].strip():
                block.append(lines[i]); i += 1
            if block == ['FADE TO BLACK.']:
                scene['blocks'].append({'line': start + 1, 'kind': 'fade', 'text': block[0]})
                continue
            who = None
            if re.fullmatch(r"[A-Z][A-Z '’()-]{0,38}", block[0]):
                assert len(block) > 1, (start + 1, block)
                who = block.pop(0)
                speakers.add(who)
            text = ' '.join(block)
            scene['blocks'].append({'line': start + 1, 'speaker': who, 'text': text})
            art = None
            alt = ''
            if n == 1 and start + 1 >= 17:
                art = 'art/backgrounds/chamber-closed.png'
                alt = 'The return arch is sealed stone, newly cracked. Severe pale light fills the chamber.'
            if n == 2 and 73 <= start + 1 < 107:
                art = 'art/backgrounds/apartment-open.png'
                alt = 'A very dark apartment, cold window at left, candle on the table, open door to the guarded hall at right.'
            out += [f'    # Source lines {start + 1}–{i}',
                    f'    $ source_line = {start + 1}', f'    $ scene_art = {q(art) if art else "None"}',
                    f'    $ scene_art_alt = {q(alt)}',
                    f'    $ scene_speaker = {q(who) if who else "None"}']
            for page in pages(text):
                # Literal braces/brackets in source must not become Ren'Py expressions.
                page = page.replace('[', '[[').replace('{', '{{')
                out.append(f'    cast[{q(who)}] {q(page)}' if who else f'    {q(page)}')
        out += [f'    $ completed_scenes = max(completed_scenes, {n})']
        if n in ROUNDS:
            out += [f'    $ unlocked_round = {ROUNDS[n]}', f'    call investigation_invitation({ROUNDS[n]})']
        out += [f'    jump s{n+1:03}' if n < 58 else '    jump original_ending', '']
        scenes.append(scene)
    meta = {'source_sha256': hashlib.sha256(raw.encode()).hexdigest(),
            'chapters': CHAPTERS, 'speakers': sorted(speakers), 'scenes': scenes}
    return '\n'.join(out), json.dumps(meta, indent=2, ensure_ascii=False) + '\n'


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    script, manifest = adapt()
    for name, content in [('story.rpy', script), ('source-map.json', manifest)]:
        target = GAME / name
        if args.check:
            assert target.read_text() == content, f'{name} is stale; regenerate and review'
        else:
            target.write_text(content)
    print('58 scenes adapted; source blocks preserved; ' + ('checked' if args.check else 'written'))
