; GIMP 2.10. Painted UI components; run from repository root.
(load "visual-novel/tools/finish-opening.scm")
(define ui-root "visual-novel/art/interface-original/")
(define ui-out "visual-novel/renpy/game/art/interface-original/")
(define (ui-soft-ends im margin)
 (let ((layer (car (gimp-image-get-active-layer im)))
       (w (car (gimp-image-width im))) (h (car (gimp-image-height im))))
  (gimp-image-select-rectangle im CHANNEL-OP-REPLACE margin -100 (- w (* margin 2)) (+ h 200))
  (gimp-selection-feather im margin)
  (gimp-layer-add-mask layer (car (gimp-layer-create-mask layer ADD-SELECTION-MASK)))
  (gimp-selection-none im)))
(let* ((p (string-append ui-root "raw/dialogue-frame.png"))
       (im (car (gimp-file-load RUN-NONINTERACTIVE p p)))
       (base (car (gimp-image-get-active-layer im)))
       (clean (car (gimp-layer-copy base TRUE))))
 (gimp-item-set-name base "00 Generated frame - preserved original")
 (gimp-item-set-visible base FALSE)
 (gimp-image-insert-layer im clean 0 0)
 (gimp-item-set-name clean "01 Alpha cleanup and subdued mineral surface")
 (gimp-levels clean HISTOGRAM-ALPHA 14 248 1.0 0 255)
 (gimp-hue-saturation clean ALL-HUES 0 0 -12)
 (gimp-xcf-save RUN-NONINTERACTIVE im clean (string-append ui-root "masters/dialogue-frame.xcf") "dialogue-frame.xcf")
 (let ((copy (car (gimp-image-duplicate im))))
  (gimp-image-scale copy 640 214)
  (seq-export copy (string-append ui-out "speech.png"))
  (gimp-image-delete copy))
 (let ((copy (car (gimp-image-duplicate im))))
  (gimp-image-crop copy 1220 405 580 158)
  (gimp-image-scale copy 1920 1080)
  (gimp-curves-spline (car (gimp-image-get-active-layer copy)) HISTOGRAM-VALUE 8 #(0 0 64 33 150 105 255 205))
  (seq-export copy (string-append ui-out "mineral-surface.png"))
  (gimp-image-delete copy))
 (let ((copy (car (gimp-image-duplicate im))))
  (gimp-image-crop copy 1120 62 620 84)
  (gimp-image-scale copy 1120 42)
  (ui-soft-ends copy 35)
  (seq-export copy (string-append ui-out "gilt-lip.png"))
  (gimp-image-delete copy))
 ; Reusable quiet central surface with the painted lips intact.
 (let ((copy (car (gimp-image-duplicate im))))
  (gimp-image-crop copy 880 580 670 77)
  (gimp-image-scale copy 660 435)
  (ui-soft-ends copy 18)
  (seq-export copy (string-append ui-out "reading.png"))
  (gimp-image-delete copy))
 ; Separate the botanical crest with an editable contour mask. Its dark field
 ; is removed from this crop so it can sit on title and utility surfaces.
 (let* ((copy (car (gimp-image-duplicate im)))
        (flat (car (gimp-image-merge-visible-layers copy CLIP-TO-IMAGE))))
  (gimp-image-select-polygon copy CHANNEL-OP-REPLACE 30
   #(0 0 610 0 590 132 400 137 310 108 249 180 214 243 214 367 252 460 410 550 570 600 480 724 0 724 0 0 0 0))
  (gimp-selection-feather copy 2)
  (gimp-layer-add-mask flat (car (gimp-layer-create-mask flat ADD-SELECTION-MASK)))
  (gimp-selection-none copy)
  (gimp-image-crop copy 610 724 0 0)
  (gimp-xcf-save RUN-NONINTERACTIVE copy flat (string-append ui-root "masters/crest.xcf") "crest.xcf")
  (seq-export copy (string-append ui-out "crest.png"))
  (gimp-image-delete copy))
 (gimp-image-delete im))
