; GIMP 2.10 Script-Fu. Run from the repository root.
(define bg-root "visual-novel/art/runtime/backgrounds/")
(define bg-out "visual-novel/renpy/game/art/backgrounds/")
(define harsh #(0 28 64 98 128 180 192 242 255 255))
(define night #(0 0 32 24 96 82 192 183 255 248))
(define ordinary #(0 2 64 65 128 147 192 215 255 255))
(define (bg-load name)
 (let* ((path (string-append bg-root name "-generated.png"))
        (im (car (gimp-file-load RUN-NONINTERACTIVE path path))))
  (gimp-item-set-name (car (gimp-image-get-active-layer im)) "00 Retained environment generation")
  im))
(define (patch im source name rectangles)
 (let* ((path (string-append bg-root source "-generated.png"))
        (layer (car (gimp-file-load-layer RUN-NONINTERACTIVE im path)))
        (mask 0))
  (gimp-image-insert-layer im layer 0 0)
  (gimp-item-set-name layer name)
  (gimp-selection-none im)
  (for-each (lambda (r)
    (gimp-image-select-rectangle im CHANNEL-OP-ADD (car r) (cadr r) (caddr r) (cadddr r))) rectangles)
  (gimp-selection-feather im 7)
  (set! mask (car (gimp-layer-create-mask layer ADD-SELECTION-MASK)))
  (gimp-layer-add-mask layer mask)
  (gimp-selection-none im)
  layer))
(define (groceries im)
 (let* ((path "visual-novel/art/runtime/props/fallen-groceries-generated.png")
        (layer (car (gimp-file-load-layer RUN-NONINTERACTIVE im path)))
        (mask 0))
  (gimp-image-insert-layer im layer 0 0)
  (gimp-item-set-name layer "03 Groceries - one step inside threshold")
  (set! mask (car (gimp-layer-create-mask layer ADD-ALPHA-TRANSFER-MASK)))
  (gimp-layer-add-mask layer mask)
  (gimp-levels mask HISTOGRAM-VALUE 5 253 1.0 0 255)
  (gimp-layer-scale layer 235 157 TRUE)
  (gimp-layer-set-offsets layer 278 730)))
(define (finish-bg im name curve)
 (let* ((grade (car (gimp-layer-new-from-visible im im "10 Scene light - complete corrected environment")))
        (xcf (string-append bg-root name ".xcf"))
        (png (string-append bg-out name ".png")))
  (gimp-image-insert-layer im grade 0 0)
  (gimp-curves-spline grade HISTOGRAM-VALUE (vector-length curve) curve)
  ; Preserve Earth's distinct cold predawn exposure, not the temple curve.
  (if (or (string=? name "chamber-open") (string=? name "chamber-open-spill"))
   (let* ((mask (car (gimp-layer-create-mask grade ADD-WHITE-MASK))))
    (gimp-layer-add-mask grade mask)
    (gimp-image-select-polygon im CHANNEL-OP-REPLACE 24
     #(221 744 217 266 225 189 250 108 303 49 382 0 416 0 486 45 548 114 584 185 599 270 594 722))
    (gimp-selection-feather im 1)
    (gimp-context-set-foreground '(0 0 0))
    (gimp-edit-fill mask FOREGROUND-FILL)
    (gimp-selection-none im)
    (gimp-image-set-active-layer im grade)))
  (gimp-xcf-save RUN-NONINTERACTIVE im grade xcf xcf)
  (let* ((flat (car (gimp-layer-new-from-visible im im "Export composite"))))
   (gimp-image-insert-layer im flat 0 0)
   (file-png-save RUN-NONINTERACTIVE im flat png png 0 9 0 0 0 0 0))
  (gimp-image-delete im)))
(define (sun-rays im layer cx cy rx ry ox oy)
 (let ((k 0) (a 0) (pts (make-vector 6 0)))
  (gimp-context-set-foreground '(164 139 80))
  (while (< k 12)
   (set! a (- (* k (/ 3.14159265359 6)) (/ 3.14159265359 2)))
   (vector-set! pts 0 (+ cx (* rx (cos (- a 0.105)))))
   (vector-set! pts 1 (+ cy (* ry (sin (- a 0.105)))))
   (vector-set! pts 2 (+ cx (* ox (cos a))))
   (vector-set! pts 3 (+ cy (* oy (sin a))))
   (vector-set! pts 4 (+ cx (* rx (cos (+ a 0.105)))))
   (vector-set! pts 5 (+ cy (* ry (sin (+ a 0.105)))))
   (gimp-image-select-polygon im CHANNEL-OP-REPLACE 6 pts)
   (gimp-edit-fill layer FOREGROUND-FILL)
   (set! k (+ k 1)))
  (gimp-selection-none im)))
(let* ((im (bg-load "apartment-open")))
 (patch im "apartment-closed" "01 Offered dress - limp fabric on floor" '((1180 493 246 265)))
 (finish-bg im "apartment-open" night))
(let* ((im (bg-load "apartment-open")))
 (patch im "apartment-closed" "01 Offered dress - limp fabric on floor" '((1180 493 246 265)))
 (patch im "apartment-closed" "02 Door shut - hall concealed" '((1420 0 252 865)))
 (finish-bg im "apartment-closed" night))
(let* ((im (bg-load "apartment-open")))
 (patch im "apartment-closed" "01 Offered dress - limp fabric on floor" '((1180 493 246 265)))
 (patch im "apartment-closed" "02 Door shut - hall concealed" '((1420 0 252 865)))
 (patch im "apartment-barricaded" "03 Same chair moved from window to door" '((265 428 260 353) (1330 409 310 418)))
 (finish-bg im "apartment-barricaded" night))
(let* ((im (bg-load "chamber-closed")))
 (groceries im)
 (finish-bg im "chamber-closed" harsh))
(finish-bg (bg-load "chamber-open") "chamber-open" harsh)
(let* ((im (bg-load "chamber-open")))
 (groceries im)
 (finish-bg im "chamber-open-spill" harsh))
(finish-bg (bg-load "palace-infirmary") "palace-infirmary" ordinary)
(let* ((im (bg-load "audience-hall"))
        (layer (car (gimp-layer-new im 1672 941 RGBA-IMAGE "01 Temple banners - twelve short rays" 94 NORMAL-MODE))))
 (gimp-image-insert-layer im layer 0 0)
 (sun-rays im layer 412 220 29 34 40 47)
 (sun-rays im layer 1488 192 40 47 55 64)
 (finish-bg im "audience-hall" harsh))
(finish-bg (bg-load "infirmary-window") "infirmary-window" ordinary)
(gimp-quit 0)
