(load "visual-novel/tools/finish-opening.scm")
; Base plates and cast retain their original layers and alpha-cleaned variants.
(seq-arrival)
(seq-sprite "tessa-question")
(seq-sprite "tessa-refusal")
(seq-sprite "tessa-cloaked")
(seq-sprite "senn-speaking")
(seq-sprite "mara-supper")
; Preserve Mara's original face and costume. Only her rank bar changes.
(let* ((im (seq-load "mara-cloak")))
 (seq-patch im "mara-supper" "Single rank bar - collar only" '((589 347 68 60)))
 (seq-export im (string-append seq-root "raw/mara-cloak-corrected.png"))
 (seq-save im "mara-collar-repair")
 (gimp-image-delete im))
(seq-sprite "mara-cloak-corrected")
(seq-plate "milk-impact" "cg")
(seq-plate "closure" "cg")
(seq-plate "stretcher-passes" "cg")
(let ((im (seq-load "attempted-return")))
 (seq-patch im "attempted-return-props" "Groceries stay at original landing - two floor masks" '((233 597 223 180) (581 599 213 142)))
 (seq-grade im "bright" TRUE)
 (seq-deliver im "attempted-return" "cg"))
(let ((im (seq-load "phone-message")))
 (seq-patch im "phone-carton" "Milk from crushed bottom seam - carton only" '((355 499 273 246)))
 ; This insert has no faces and already shares the chamber's harsh illumination.
 (seq-deliver im "phone-message" "cg"))
(let ((im (seq-load "unanswered-cloak")))
 (seq-patch im "unanswered-cloak-repairs" "Senn turns away; unzipped hoodie; sealed stone" '((1010 0 662 941) (270 405 272 405) (0 0 342 233)))
 (seq-grade im "bright" FALSE)
 (seq-deliver im "unanswered-cloak" "cg"))
; Conversation plates: lock bag placement and fully depressed lever to closure.
(let ((im (seq-load "arch-conversation")))
 (seq-patch im "arch-clean-floor" "Restore floor at rejected grocery position" '((399 624 213 199)))
 (seq-grocery-and-control im)
 (seq-grade im "bright" FALSE)
 (seq-deliver im "arch-conversation" "bg"))
(let ((im (seq-load "arch-conversation")))
 (seq-patch im "arch-clean-floor" "Restore floor at rejected grocery position" '((399 624 213 199)))
 (seq-grocery-and-control im)
 (seq-patch im "arch-guards-raised" "Guards block approach with raised shields" '((716 255 299 407)))
 (seq-grade im "bright" FALSE)
 (seq-deliver im "arch-guards-raised" "bg"))
; Replace invented star clasp with the plain brass fastening from Senn's key.
(let* ((im (seq-load "pleading-mother"))
       (source (seq-load "senn-speaking"))
       (clasp 0))
 (gimp-image-crop source 85 55 560 475)
 (set! clasp (car (gimp-layer-new-from-drawable (car (gimp-image-get-active-layer source)) im)))
 (gimp-image-insert-layer im clasp 0 0)
 (gimp-layer-add-alpha clasp)
 (gimp-layer-set-offsets clasp 0 0)
 (gimp-image-select-polygon im CHANNEL-OP-REPLACE 22 #(2 22 8 9 17 6 32 8 40 15 65 12 70 20 41 25 34 38 20 42 7 34))
 (gimp-selection-feather im 1)
 (gimp-layer-add-mask clasp (car (gimp-layer-create-mask clasp ADD-SELECTION-MASK)))
 (gimp-selection-none im)
 (gimp-layer-scale clasp 128 83 FALSE)
 (gimp-layer-set-offsets clasp 1260 358)
 (gimp-item-set-name clasp "Plain brass clasp from working character - exact shape")
 (gimp-image-delete source)
 (seq-grade im "bright" FALSE)
 (seq-deliver im "pleading-mother" "cg"))
(gimp-quit 0)
