; Controlled component finishing in GIMP 2.10. No reference recasting.
(define rv-root "visual-novel/art/rovel/")
(define rv-out "visual-novel/renpy/game/art/rovel/")
(define rv-soft "visual-novel/renpy/game/art/softened/rovel/")
(define (rv-export im path)
 (let* ((copy (car (gimp-image-duplicate im)))
        (flat (car (gimp-image-merge-visible-layers copy CLIP-TO-IMAGE))))
  (file-png-save RUN-NONINTERACTIVE copy flat path path 0 9 0 0 0 0 0)
  (gimp-image-delete copy)))
(define (rv-save im name)
 (let ((path (string-append rv-root "masters/" name ".xcf")))
  (gimp-xcf-save RUN-NONINTERACTIVE im (car (gimp-image-get-active-layer im)) path path)))
(define (rv-grade layer mode softened)
 (cond
  ((equal? mode "bright")
   (gimp-hue-saturation layer ALL-HUES 0 0 -12)
   (if softened
    (gimp-curves-spline layer HISTOGRAM-VALUE 10 #(0 0 48 56 110 139 180 215 255 250))
    (gimp-curves-spline layer HISTOGRAM-VALUE 14 #(0 4 35 69 70 146 110 224 155 249 210 254 255 255))))
  ((equal? mode "ordinary")
   (gimp-color-balance layer MIDTONES TRUE -4 0 5)
   (if softened
    (gimp-curves-spline layer HISTOGRAM-VALUE 10 #(0 0 48 45 110 120 180 200 255 248))
    (gimp-curves-spline layer HISTOGRAM-VALUE 12 #(0 0 48 33 96 112 155 208 215 250 255 255))))
  ((equal? mode "night")
   (gimp-color-balance layer MIDTONES TRUE -10 -1 8)
   (gimp-hue-saturation layer ALL-HUES 0 0 -18)
   (if softened
    (gimp-curves-spline layer HISTOGRAM-VALUE 12 #(0 0 48 24 96 57 155 113 215 184 255 236))
    (gimp-curves-spline layer HISTOGRAM-VALUE 12 #(0 0 48 6 96 20 155 52 215 147 255 233))))))
(define (rv-portrait sheet name x y w h variants)
 (let* ((path (string-append rv-root "raw/" sheet ".png"))
        (im (car (gimp-file-load RUN-NONINTERACTIVE path path)))
        (source (car (gimp-image-get-active-layer im))))
  (gimp-image-crop im w h x y)
  (let* ((long-side (max w h))
         (sw (round (* 512 (/ w long-side))))
         (sh (round (* 512 (/ h long-side)))))
   (gimp-image-scale im sw sh)
   (gimp-image-resize im 512 512 (round (/ (- 512 sw) 2)) (round (/ (- 512 sh) 2)))
   (gimp-layer-resize-to-image-size source))
  (gimp-item-set-name source "00 Identity/expression crop - no costume or prop inference")
  ; Remove the neutral sheet around the head rather than lighting a pale oval.
  ; Contiguous corner samples preserve skin and the darker hair silhouette.
  (gimp-context-set-sample-threshold-int 18)
  (gimp-context-set-sample-merged FALSE)
  (gimp-image-select-contiguous-color im CHANNEL-OP-REPLACE source 3 3)
  (gimp-image-select-contiguous-color im CHANNEL-OP-ADD source 507 3)
  (gimp-selection-invert im)
  ; The lower corners of Tessa's sheet contain hair, not background. Never seed
  ; from them. Protect the continuous face/neck interior against tonal overlap.
  (if (equal? sheet "tessa-expressions-v1")
   (begin
    (gimp-image-select-ellipse im CHANNEL-OP-ADD 108 125 287 382)
    ; Hand-traced outside contour excludes sheet left among the lower strands.
    (gimp-image-select-polygon im CHANNEL-OP-INTERSECT 64
     (list->vector (map (lambda (n) (* n (/ 512 627)))
      '(179 27 282 4 419 27 496 65 546 132 548 212 535 269 527 318
        548 363 553 401 597 432 616 477 614 551 589 598 549 618 480 604
        438 585 422 622 236 624 235 575 184 542 149 493 125 448 125 399
        112 364 110 327 115 289 90 249 91 206 99 154 115 96 143 62))))))
  (gimp-selection-feather im 1.4)
  (gimp-layer-add-mask source (car (gimp-layer-create-mask source ADD-SELECTION-MASK)))
  (gimp-selection-none im)
  (gimp-image-select-rectangle im CHANNEL-OP-REPLACE 0 497 512 15)
  (gimp-selection-feather im 10)
  (gimp-context-set-foreground '(0 0 0))
  (gimp-edit-fill (car (gimp-layer-get-mask source)) FOREGROUND-FILL)
  (gimp-selection-none im)
  (for-each
   (lambda (variant)
    (let* ((label (car variant)) (mode (cadr variant))
           (intense (car (gimp-layer-copy source TRUE)))
           (soft (car (gimp-layer-copy source TRUE))))
     (gimp-item-set-visible source FALSE)
     (gimp-image-insert-layer im intense 0 0)
     (gimp-item-set-visible intense TRUE)
     (gimp-item-set-name intense (string-append "Intense " label " - editable scene grade"))
     (rv-grade intense mode #f)
     (rv-export im (string-append rv-out "portraits/" name "-" label ".png"))
     (gimp-item-set-visible intense FALSE)
     (gimp-image-insert-layer im soft 0 0)
     (gimp-item-set-visible soft TRUE)
     (gimp-item-set-name soft (string-append "Softened " label " - from same source"))
     (rv-grade soft mode #t)
     (rv-export im (string-append rv-soft "portraits/" name "-" label ".png"))
     (gimp-item-set-visible soft FALSE))) variants)
  ; The saved visible layers reproduce the delivered default, not an ungraded crop.
  (gimp-item-set-visible (vector-ref (cadr (gimp-image-get-layers im)) 1) TRUE)
  (rv-save im name)
  (gimp-image-delete im)))
(define (rv-interface)
 (let* ((path (string-append rv-root "raw/reading-surface-v1.png"))
        (im (car (gimp-file-load RUN-NONINTERACTIVE path path)))
        (source (car (gimp-image-get-active-layer im)))
        (clean (car (gimp-layer-copy source TRUE))))
  (gimp-item-set-name source "00 Unmodified generated complete frame")
  (gimp-item-set-visible source FALSE)
  (gimp-image-insert-layer im clean 0 0)
  (gimp-item-set-name clean "01 Remove stray alpha; preserve all four crafted edges")
  (gimp-levels clean HISTOGRAM-ALPHA 24 250 1.0 0 255)
  (gimp-image-crop im 2116 579 29 62)
  (gimp-image-scale im 1600 438)
  (rv-save im "reading-surface")
  (rv-export im (string-append rv-out "ui/reading-surface.png"))
  ; Smaller prose/menu panels need an open text field. Keep the complete border
  ; and corners, and replace the large interior branch using the panel's texture.
  (let ((quiet (car (gimp-layer-copy clean TRUE))))
   (gimp-image-insert-layer im quiet 0 0)
   (gimp-item-set-name quiet "02 Quiet-panel texture repair, complete border retained")
   (gimp-image-select-rectangle im CHANNEL-OP-REPLACE 450 55 240 347)
   (gimp-edit-copy quiet)
   (gimp-selection-none im)
   (let ((patch (car (gimp-edit-paste quiet FALSE))))
    (gimp-layer-set-offsets patch 22 55)
    (gimp-floating-sel-anchor patch))
   (rv-export im (string-append rv-out "ui/quiet-surface.png"))
   (gimp-item-set-visible quiet FALSE))
  (rv-save im "reading-surface")
  (gimp-image-delete im)))
(define (rv-tessa)
 (let ((variants '(("arrival-bright" "bright") ("arrival-cloak-night" "night")
                   ("arrival-night" "night") ("working-ordinary" "ordinary")
                   ("formal-bright" "bright") ("formal-ordinary" "ordinary"))))
  (rv-portrait "tessa-expressions-v1" "tessa-startled" 0 0 627 627 variants)
  (rv-portrait "tessa-expressions-v1" "tessa-resolute" 627 0 627 627 variants)
  (rv-portrait "tessa-expressions-v1" "tessa-wounded" 0 627 627 627 variants)
  (rv-portrait "tessa-expressions-v1" "tessa-listening" 627 627 627 627 variants)))

(define (rv-senn)
 (let ((variants '(("bright" "bright"))))
  (rv-portrait "senn-expressions-v1" "senn-assuring" 0 0 627 836 variants)
  (rv-portrait "senn-expressions-v1" "senn-listening" 627 0 627 836 variants)
  (rv-portrait "senn-expressions-v1" "senn-evasive" 1254 0 627 836 variants)))

(define (rv-mara)
 (let ((variants '(("bright" "bright") ("night" "night") ("ordinary" "ordinary"))))
  (rv-portrait "mara-expressions-v1" "mara-controlled" 0 0 887 887 variants)
  (rv-portrait "mara-expressions-v1" "mara-uneasy" 887 0 887 887 variants)))

(define (rv-iven)
 (let ((variants '(("bright" "bright") ("ordinary" "ordinary"))))
  (rv-portrait "iven-expressions-v1" "iven-attentive" 0 0 887 887 variants)
  (rv-portrait "iven-expressions-v1" "iven-concerned" 887 0 887 887 variants)))

(define (rv-supporting)
 (rv-portrait "supporting-cast-v1" "olan" 0 0 512 512 '(("ordinary" "ordinary") ("bright" "bright")))
 (rv-portrait "supporting-cast-v1" "priest" 512 0 512 512 '(("ordinary" "ordinary")))
 (rv-portrait "supporting-cast-v1" "mother" 1024 0 512 512 '(("ordinary" "ordinary")))
 (rv-portrait "supporting-cast-v1" "petitioner" 0 512 512 512 '(("bright" "bright")))
 (rv-portrait "supporting-cast-v1" "orra" 512 512 512 512 '(("bright" "bright")))
 (rv-portrait "supporting-cast-v1" "messenger" 1024 512 512 512 '(("bright" "bright"))))

(define (rv-detail path name x y w h)
 (let* ((im (car (gimp-file-load RUN-NONINTERACTIVE path path))))
  (gimp-image-crop im w h x y)
  (rv-export im (string-append rv-root "review/details/" name ".png"))
  (gimp-image-delete im)))

(define (rv-repair-badge im source cx cy)
 ; Replace only the wrong ray field. Preserve the rendered metal disk itself.
 (gimp-image-select-ellipse im CHANNEL-OP-REPLACE (- cx 27) (+ cy 40) 54 54)
 (gimp-selection-feather im 4)
 (let ((bounds (gimp-selection-bounds im)))
  (gimp-edit-copy source)
  (gimp-selection-none im)
  (let ((cloth (car (gimp-edit-paste source FALSE))))
   (gimp-floating-sel-to-layer cloth)
   (gimp-layer-set-offsets cloth (cadr bounds) (- (caddr bounds) 67))
   (gimp-item-set-name cloth "Cloth repair beneath corrected badge, feathered local donor")))
 (let* ((path "visual-novel/art/prop-keys/emblems/human-temple-sun.png")
        (badge (car (gimp-file-load-layer RUN-NONINTERACTIVE im path))))
  (gimp-image-insert-layer im badge 0 0)
  (gimp-layer-scale badge 72 72 FALSE)
  (gimp-layer-set-offsets badge (- cx 36) (- cy 36))
  (gimp-item-set-name badge "Fixed human temple emblem: twelve short rays"))
 (gimp-image-select-ellipse im CHANNEL-OP-REPLACE (- cx 7) (- cy 7) 14 14)
 (gimp-selection-feather im 1)
 (let ((bounds (gimp-selection-bounds im)))
  (gimp-edit-copy source)
  (gimp-selection-none im)
  (let ((disk (car (gimp-edit-paste source FALSE))))
   (gimp-floating-sel-to-layer disk)
   (gimp-layer-set-offsets disk (cadr bounds) (caddr bounds))
   (gimp-item-set-name disk "Retained modeled brass disk over fixed ray geometry"))))

(define (rv-finish-scene im name mode)
 (let ((intense 0) (soft 0))
  (set! intense (car (gimp-layer-new-from-visible im im "Intense")))
  (set! soft (car (gimp-layer-copy intense TRUE)))
  (gimp-image-insert-layer im intense 0 0)
  (gimp-item-set-name intense "01 Intense, shared environmental exposure")
  (rv-grade intense mode #f)
  (rv-export im (string-append rv-out "cg/" name ".png"))
  (gimp-item-set-visible intense FALSE)
  (gimp-image-insert-layer im soft 0 0)
  (gimp-item-set-name soft "02 Softened, same corrected scene")
  (rv-grade soft mode #t)
  (rv-export im (string-append rv-soft "cg/" name ".png"))
  (gimp-item-set-visible soft FALSE)
  (gimp-item-set-visible intense TRUE)
  (rv-save im name)
  (gimp-image-delete im)))

(define (rv-scene raw name mode . badge-center)
 (let* ((path (string-append rv-root "raw/" raw ".png"))
        (im (car (gimp-file-load RUN-NONINTERACTIVE path path)))
        (source (car (gimp-image-get-active-layer im))))
  (gimp-item-set-name source "00 Retained source, reviewed staging and performance")
  (if (not (null? badge-center))
   (rv-repair-badge im source (car badge-center) (cadr badge-center)))
  (rv-finish-scene im name mode)))

(define (rv-chair)
 (let* ((path (string-append rv-root "raw/ceremony-refused-chair-v1.png"))
        (im (car (gimp-file-load RUN-NONINTERACTIVE path path)))
        (source (car (gimp-image-get-active-layer im)))
        (patch (car (gimp-file-load-layer RUN-NONINTERACTIVE im
                    (string-append rv-root "raw/ceremony-chair-grip-repair.png")))))
  (gimp-item-set-name source "00 Original chair-refusal scene; all identity/geometry preserved")
  (gimp-image-insert-layer im patch 0 0)
  (gimp-item-set-name patch "01 Local closed grip and cloth fold, editable feathered mask")
  (gimp-image-select-rectangle im CHANNEL-OP-REPLACE 771 295 124 85)
  (gimp-selection-feather im 6)
  (gimp-layer-add-mask patch (car (gimp-layer-create-mask patch ADD-SELECTION-MASK)))
  (gimp-selection-none im)
  (rv-finish-scene im "ceremony-refused-chair" "bright")))

(define (rv-applause)
 (let* ((path (string-append rv-root "raw/ceremony-applause-v2.png"))
        (im (car (gimp-file-load RUN-NONINTERACTIVE path path)))
        (source (car (gimp-image-get-active-layer im)))
        (patch (car (gimp-file-load-layer RUN-NONINTERACTIVE im
                    (string-append rv-root "raw/applause-right-hand-repair.png")))))
  (gimp-item-set-name source "00 Standing Olan and applause, preserved source")
  (gimp-image-insert-layer im patch 0 0)
  (gimp-layer-scale patch 243 180 FALSE)
  (gimp-layer-set-offsets patch 694 413)
  (gimp-item-set-name patch "01 Right hand: thumb/index/middle survive; masked local repair")
  (gimp-image-select-polygon im CHANNEL-OP-REPLACE 20
   #(737 446 809 431 865 432 884 486 889 537 871 558 808 566 746 552 734 509 734 470))
  (gimp-selection-feather im 6)
  (gimp-layer-add-mask patch (car (gimp-layer-create-mask patch ADD-SELECTION-MASK)))
  (gimp-selection-none im)
  (rv-finish-scene im "ceremony-applause" "bright")))

(define (rv-runtime-detail scene name x y w h)
 (for-each (lambda (root)
  (let* ((path (string-append root "cg/" scene ".png"))
         (im (car (gimp-file-load RUN-NONINTERACTIVE path path))))
   (gimp-image-crop im w h x y)
   (rv-export im (string-append root "details/" name ".png"))
   (gimp-image-delete im))) (list rv-out rv-soft)))

(define (rv-intervention)
 (let* ((path (string-append rv-root "raw/ceremony-intervention-v1.png"))
        (im (car (gimp-file-load RUN-NONINTERACTIVE path path)))
        (patch (car (gimp-file-load-layer RUN-NONINTERACTIVE im
                    (string-append rv-root "raw/intervention-orra-costume-repair.png")))))
  (gimp-image-insert-layer im patch 0 0)
  (gimp-layer-scale patch 420 680 FALSE)
  (gimp-layer-set-offsets patch 530 30)
  (gimp-item-set-name patch "Orra only: military coat, trousers, gloves; no Saint mantle")
  ; Outside the old mantle, keep the original hall; head remains original.
  (gimp-image-select-rectangle im CHANNEL-OP-REPLACE 530 145 420 565)
  (gimp-selection-feather im 3)
  (gimp-layer-add-mask patch (car (gimp-layer-create-mask patch ADD-SELECTION-MASK)))
  (gimp-selection-none im)
  (rv-export im (string-append rv-root "review/ceremony-intervention-corrected.png"))
  (rv-finish-scene im "ceremony-intervention" "bright")))

(define (rv-yield)
 (let* ((path (string-append rv-root "raw/ceremony-yield-v1.png"))
        (im (car (gimp-file-load RUN-NONINTERACTIVE path path)))
        (badge (car (gimp-file-load-layer RUN-NONINTERACTIVE im
                     "visual-novel/art/prop-keys/emblems/human-temple-sun.png"))))
  ; The motion edit dropped the pinned badge. Restore only that small prop.
  (gimp-image-insert-layer im badge 0 0)
  (gimp-layer-scale badge 34 34 FALSE)
  (gimp-layer-set-offsets badge 1417 230)
  (gimp-item-set-name badge "Retained temple badge, fixed twelve-ray geometry")
  (rv-finish-scene im "ceremony-yield" "bright")))

(define (rv-window-pause)
 (let* ((path (string-append rv-root "raw/window-packing-v1.png"))
        (im (car (gimp-file-load RUN-NONINTERACTIVE path path)))
        (patch (car (gimp-file-load-layer RUN-NONINTERACTIVE im
                     (string-append rv-root "raw/window-pause-v1.png")))))
  (gimp-image-insert-layer im patch 0 0)
  (gimp-item-set-name patch "Iven stops: empty hands on chest, bottle returned; local state mask")
  (gimp-image-select-rectangle im CHANNEL-OP-REPLACE 906 0 554 941)
  (gimp-selection-feather im 8)
  (gimp-layer-add-mask patch (car (gimp-layer-create-mask patch ADD-SELECTION-MASK)))
  (gimp-selection-none im)
  (rv-finish-scene im "window-pause" "ordinary")))

(define (rv-window-together)
 (let* ((path (string-append rv-root "raw/window-packing-v1.png"))
        (im (car (gimp-file-load RUN-NONINTERACTIVE path path)))
        (patch (car (gimp-file-load-layer RUN-NONINTERACTIVE im
                     (string-append rv-root "raw/window-together-v1.png")))))
  (gimp-image-insert-layer im patch 0 0)
  (gimp-item-set-name patch "Iven joins offered sill; old standing position cleared; local state mask")
  (gimp-image-select-polygon im CHANNEL-OP-REPLACE 16
   #(590 0 1460 0 1460 941 726 941 605 634 588 496 617 313 590 165))
  (gimp-selection-feather im 8)
  (gimp-layer-add-mask patch (car (gimp-layer-create-mask patch ADD-SELECTION-MASK)))
  (gimp-selection-none im)
  (rv-finish-scene im "window-together" "ordinary")))
