(load "visual-novel/tools/finish-opening.scm")
(define (two-chairs im)
 (seq-patch im "apartment-two-chairs" "Remove two invented dining chairs; keep window and table seats" '((949 562 188 186) (1089 729 326 212))))
(seq-sprite "tessa-cloaked")
(seq-sprite "mara-supper")
(seq-sprite "tessa-refusal")
(let ((im (seq-load "apartment-window")))
 (seq-patch im "apartment-two-chairs" "Offered dress is empty collapsed cloth" '((610 450 315 225)))
 (two-chairs im)
 (seq-grade im "night" FALSE)
 (seq-deliver im "apartment-window" "cg"))
(let ((im (seq-load "apartment-two-chairs")))
 (seq-grade im "night" FALSE)
 (seq-deliver im "apartment-open" "bg"))
(let ((im (seq-load "apartment-two-chairs")))
 (seq-patch im "apartment-window" "Closed door after Mara leaves; guard no longer visible" '((1228 97 295 528)))
 (seq-patch im "chair-barricade" "Second covered supper plate remains on the table" '((1422 658 214 126)))
 (seq-grade im "night" FALSE)
 (seq-deliver im "apartment-locked" "bg"))
(let ((im (seq-load "chair-barricade")))
 (two-chairs im)
 (seq-grade im "night" FALSE)
 (seq-deliver im "chair-barricade" "cg"))
(let ((im (seq-load "blocked-doorway")))
 (seq-grade im "night" FALSE)
 (seq-deliver im "blocked-doorway" "cg"))
(let ((im (seq-load "cloak-discarded")))
 (seq-patch im "blocked-doorway" "Welcome letter stays on table after cloak falls" '((365 852 243 57)))
 (seq-grade im "night" FALSE)
 (seq-deliver im "cloak-discarded" "cg"))
; The paper tear is a tiny local painted layer, not another full regeneration.
(define (paper-tear im)
 (let ((layer (car (gimp-layer-new im 1672 941 RGBA-IMAGE "Small pen tear: dark slit and lifted paper edge" 100 NORMAL-MODE))))
  (gimp-image-insert-layer im layer 0 0)
  (gimp-context-set-foreground '(49 33 25))
  (gimp-image-select-polygon im CHANNEL-OP-REPLACE 20 #(942 744 950 750 951 755 960 762 964 768 959 765 954 760 947 756 948 752 942 746))
  (gimp-edit-fill layer FOREGROUND-FILL)
  (gimp-context-set-foreground '(229 208 175))
  (gimp-image-select-polygon im CHANNEL-OP-REPLACE 12 #(943 746 950 754 957 762 961 765 954 761 947 755))
  (gimp-edit-fill layer FOREGROUND-FILL)
  (gimp-selection-none im)))
(for-each (lambda (name)
 (let ((im (seq-load name)))
  (paper-tear im)
  (seq-grade im "night" FALSE)
  (seq-deliver im name "cg"))) '("drawing-letter" "drawing-restart"))
(seq-crop "visual-novel/renpy/game/art/opening/cg/drawing-restart.png" 718 704 586 204 "visual-novel/renpy/game/art/opening/cg/detail-drawing.png")
(seq-crop "visual-novel/renpy/game/art/opening/cg/drawing-restart.png" 1310 746 275 160 "visual-novel/renpy/game/art/opening/cg/detail-phone.png")
(gimp-quit 0)
