(load "visual-novel/tools/finish-opening.scm")
(let ((im (seq-load "tessa-treatment")))
 (seq-patch im "tessa-before-light" "Closed mouth and unlit hands only; preserve identity, costume and alpha" '((508 315 135 101) (326 1025 335 253)))
 (seq-export im (string-append seq-root "raw/tessa-unlit-masked.png"))
 (seq-save im "tessa-unlit-mask")
 (gimp-image-delete im))
(seq-sprite "tessa-treatment")
(seq-sprite "tessa-unlit-masked")
(seq-sprite "iven-treatment")
; Corruption passes the ink boundary; paint only a few subcutaneous branches.
(define (corruption-edge im)
 (let ((layer (car (gimp-layer-new-from-visible im im "Local skin texture extends past the morning boundary"))))
  (gimp-image-insert-layer im layer 0 0)
  (gimp-layer-set-offsets layer 50 0)
  (gimp-layer-set-opacity layer 74)
  (gimp-image-select-ellipse im CHANNEL-OP-REPLACE 902 594 64 48)
  (gimp-image-select-ellipse im CHANNEL-OP-ADD 955 604 15 18)
  (gimp-selection-feather im 5)
  (gimp-layer-add-mask layer (car (gimp-layer-create-mask layer ADD-SELECTION-MASK)))
  (gimp-selection-none im)))
(let ((im (seq-load "blue-healing")))
 ; Use corrected arm/light and bed-rail grip, preserving all original faces.
 (seq-patch im "blue-final" "Blue light at missing fingers; intact wrist; left hand grips bed rail" '((645 357 567 251) (566 542 444 171) (1330 652 342 289)))
 (corruption-edge im)
 (seq-grade im "ordinary" FALSE)
 (seq-deliver im "blue-healing" "cg"))
(let ((im (seq-load "ward-conversation")))
 (corruption-edge im)
 (seq-grade im "ordinary" FALSE)
 (seq-deliver im "ward-conversation" "bg"))
(let ((im (seq-load "ward-entrance")))
 (seq-grade im "ordinary" FALSE)
 (seq-deliver im "ward-entrance" "cg"))
(let ((im (seq-load "first-purification")))
 (let ((layer (car (gimp-file-load-layer RUN-NONINTERACTIVE im (string-append seq-root "raw/purification-cleared.png")))))
  (gimp-image-insert-layer im layer 0 0)
  (gimp-item-set-name layer "Soft irregular clearing beneath Iven's fingertips")
  (gimp-image-select-polygon im CHANNEL-OP-REPLACE 16 #(750 599 831 590 859 609 848 622 858 638 845 657 755 662 750 599))
  (gimp-selection-feather im 14)
  (gimp-layer-add-mask layer (car (gimp-layer-create-mask layer ADD-SELECTION-MASK)))
  (gimp-selection-none im))
 (seq-grade im "ordinary" FALSE)
 (seq-deliver im "first-purification" "cg"))
(let ((im (seq-load "purification-cleared")))
 ; Last patch beside the wound before the light finishes moving back.
 (seq-patch im "first-purification" "Tessa still watching the wound" '((272 108 357 283)))
 (let ((layer (car (gimp-file-load-layer RUN-NONINTERACTIVE im (string-append seq-root "raw/first-purification.png")))))
  (gimp-image-insert-layer im layer 0 0)
  (gimp-item-set-name layer "Last branching discoloration at wrist - local source texture")
  (gimp-layer-set-offsets layer -120 0)
  (gimp-image-select-ellipse im CHANNEL-OP-REPLACE 717 615 33 27)
  (gimp-selection-feather im 5)
  (gimp-layer-add-mask layer (car (gimp-layer-create-mask layer ADD-SELECTION-MASK)))
  (gimp-selection-none im))
 (seq-grade im "ordinary" FALSE)
 (seq-deliver im "last-patch" "cg"))
(for-each (lambda (name)
 (let ((im (seq-load name)))
  (seq-grade im "ordinary" FALSE)
  (seq-deliver im name "cg"))) '("purification-cleared" "treatment-pause" "after-first-treatment"))
(seq-crop "visual-novel/renpy/game/art/opening/cg/treatment-pause.png" 780 428 880 495 "visual-novel/renpy/game/art/opening/cg/rested-hand.png")
; Native inspection crops are made by GIMP, not a second image processor.
(seq-crop "visual-novel/renpy/game/art/opening/cg/blue-healing.png" 536 470 506 270 "/tmp/ward-blue-hands.png")
(seq-crop "visual-novel/renpy/game/art/opening/cg/purification-cleared.png" 540 500 491 211 "/tmp/ward-cleared-hands.png")
(seq-crop "visual-novel/renpy/game/art/opening/cg/after-first-treatment.png" 773 635 239 160 "/tmp/ward-resting-hand.png")
(gimp-quit 0)
