(load "visual-novel/tools/finish-opening.scm")
(seq-sprite "tessa-phone")
(let ((im (seq-load "arch-conversation")))
 (seq-patch im "arch-clean-floor" "Remove old misplaced groceries without copying feet" '((399 624 213 199)))
 (seq-grocery-and-control im)
 (seq-grade im "bright" FALSE)
 (seq-deliver im "arch-conversation" "bg"))
(let ((im (seq-load "arch-conversation")))
 (seq-patch im "arch-clean-floor" "Remove old misplaced groceries without copying feet" '((399 624 213 199)))
 (seq-grocery-and-control im)
 (seq-patch im "arch-guards-raised" "Guards before lowering shields" '((716 255 299 407)))
 (seq-grade im "bright" FALSE)
 (seq-deliver im "arch-guards-raised" "bg"))
(let* ((im (seq-load "woman-release"))
       (source (seq-load "senn-speaking"))
       (clasp 0))
 (gimp-image-crop source 85 55 560 475)
 (set! clasp (car (gimp-layer-new-from-drawable (car (gimp-image-get-active-layer source)) im)))
 (gimp-image-insert-layer im clasp 0 0)
 (gimp-layer-add-alpha clasp)
 (gimp-layer-set-offsets clasp 0 0)
 (gimp-image-select-polygon im CHANNEL-OP-REPLACE 22 #(2 22 8 9 17 6 32 8 40 15 65 12 70 20 41 25 34 38 20 42 7 34))
 (gimp-selection-feather im 1)
 (gimp-layer-add-mask clasp (car (gimp-layer-create-mask clasp ADD-SELECTION-MASK)))
 (gimp-selection-none im)
 (gimp-layer-scale clasp 128 83 FALSE)
 (gimp-layer-set-offsets clasp 1265 358)
 (gimp-item-set-name clasp "Same plain round brass clasp")
 (gimp-image-delete source)
 (seq-grade im "bright" FALSE)
 (seq-deliver im "woman-release" "cg"))
(let ((im (seq-load "apartment-window")))
 (seq-patch im "apartment-open" "Collapsed empty ceremonial dress - local cloth mask" '((610 450 315 225)))
 (seq-grade im "night" FALSE)
 (seq-deliver im "apartment-window" "cg"))
(let ((im (seq-load "apartment-open")))
 (seq-grade im "night" FALSE)
 (seq-deliver im "apartment-open" "bg"))
(gimp-quit 0)
