; Run from the repository root with GIMP 2.10 Script-Fu.
; Retains the generation, editable transferred alpha mask, and distinct light
; layers. Each export selects exactly one light layer; no stacked exposure.
(define (export-png im layer path)
  ; Apply the target layer's mask in a disposable image. Exporting a hidden
  ; drawable directly can discard its mask; XCF masters keep editable masks.
  (gimp-image-set-active-layer im layer)
  (let* ((copy (car (gimp-image-duplicate im)))
         (flat (car (gimp-image-get-active-layer copy)))
         (layers (gimp-image-get-layers copy)) (i 0))
    (while (< i (car layers))
      (gimp-item-set-visible (vector-ref (cadr layers) i) FALSE)
      (set! i (+ i 1)))
    (gimp-item-set-visible flat TRUE)
    (if (> (car (gimp-layer-get-mask flat)) -1)
        (gimp-layer-remove-mask flat MASK-APPLY))
    (file-png-save RUN-NONINTERACTIVE copy flat path path 0 9 0 0 0 0 0)
    (gimp-image-delete copy)))
(define (sprite-layer im base name)
  (let ((layer (car (gimp-layer-copy base TRUE))))
    (gimp-image-insert-layer im layer 0 0)
    (gimp-item-set-visible layer TRUE)
    (gimp-item-set-name layer name)
    layer))
(define (sun-rays im layer cx cy rx ry ox oy color)
  (let ((k 0) (a 0) (t 0) (pts (make-vector 6 0)))
    (gimp-context-set-foreground color)
    (while (< k 12)
      (set! a (- (* k (/ 3.14159265359 6)) (/ 3.14159265359 2)))
      (set! t 0.105)
      (vector-set! pts 0 (+ cx (* rx (cos (- a t)))))
      (vector-set! pts 1 (+ cy (* ry (sin (- a t)))))
      (vector-set! pts 2 (+ cx (* ox (cos a))))
      (vector-set! pts 3 (+ cy (* oy (sin a))))
      (vector-set! pts 4 (+ cx (* rx (cos (+ a t)))))
      (vector-set! pts 5 (+ cy (* ry (sin (+ a t)))))
      (gimp-image-select-polygon im CHANNEL-OP-REPLACE 6 pts)
      (gimp-edit-fill layer FOREGROUND-FILL)
      (set! k (+ k 1)))
    (gimp-selection-none im)))
(define (ceremony-badge im master)
  (let* ((layer (car (gimp-layer-new im 1024 1536 RGBA-IMAGE "02 Exactly twelve short brass badge rays" 100 NORMAL-MODE)))
         (combined 0))
    (gimp-image-insert-layer im layer 0 0)
    (sun-rays im layer 574 348 12.0 12.2 21.5 22.0 '(190 161 99))
    (set! combined (car (gimp-layer-new-from-visible im im "03 Corrected costume master")))
    (gimp-image-insert-layer im combined 0 0)
    (gimp-item-set-visible layer FALSE)
    (gimp-item-set-visible master FALSE)
    combined))
(define (senn-embroidery im master)
  (let* ((src "visual-novel/art/runtime/sprites/senn-embroidery-repair.png")
         (cloth (car (gimp-file-load-layer RUN-NONINTERACTIVE im src)))
         (rays (car (gimp-layer-new im 1024 1536 RGBA-IMAGE "03 Correct twelve-ray embroidery" 78 NORMAL-MODE)))
         (mask 0) (combined 0)
         (motifs '((398 288 22 35) (375 363 23 37) (354 455 22 38)
                   (590 223 25 24) (550 285 32 37) (519 380 35 42) (504 482 33 40)
                   (635 732 26 30) (706 756 26 28) (768 806 27 31))))
    (gimp-image-insert-layer im cloth 0 0)
    (gimp-item-set-name cloth "02 Masked textile repairs - only former emblems")
    (gimp-selection-none im)
    (for-each (lambda (m)
      (gimp-image-select-ellipse im CHANNEL-OP-ADD
        (- (car m) (+ (caddr m) 3)) (- (cadr m) (+ (cadddr m) 3))
        (* 2 (+ (caddr m) 3)) (* 2 (+ (cadddr m) 3)))) motifs)
    (gimp-selection-feather im 2)
    (gimp-image-select-item im CHANNEL-OP-INTERSECT (car (gimp-layer-get-mask master)))
    (set! mask (car (gimp-layer-create-mask cloth ADD-SELECTION-MASK)))
    (gimp-layer-add-mask cloth mask)
    (gimp-selection-none im)
    (gimp-image-insert-layer im rays 0 0)
    (for-each (lambda (m)
      (let* ((cx (car m)) (cy (cadr m)) (rx (* .42 (caddr m))) (ry (* .42 (cadddr m))))
        (sun-rays im rays cx cy rx ry (* .80 (caddr m)) (* .80 (cadddr m)) '(160 128 71))
        (gimp-image-select-ellipse im CHANNEL-OP-REPLACE (- cx rx) (- cy ry) (* 2 rx) (* 2 ry))
        (gimp-edit-fill rays FOREGROUND-FILL)
        (gimp-image-select-ellipse im CHANNEL-OP-REPLACE (- cx (- rx 1.5)) (- cy (- ry 1.5)) (* 2 (- rx 1.5)) (* 2 (- ry 1.5)))
        (gimp-edit-clear rays)
        (gimp-selection-none im))) motifs)
    (gimp-image-select-item im CHANNEL-OP-REPLACE (car (gimp-layer-get-mask master)))
    (gimp-layer-add-mask rays (car (gimp-layer-create-mask rays ADD-SELECTION-MASK)))
    (gimp-selection-none im)
    (set! combined (car (gimp-layer-new-from-visible im im "04 Costume master with consistent emblems")))
    (gimp-image-insert-layer im combined 0 0)
    (gimp-item-set-visible cloth FALSE)
    (gimp-item-set-visible rays FALSE)
    (gimp-item-set-visible master FALSE)
    combined))
(define (finish-sprite name)
  (let* ((dir "visual-novel/art/runtime/sprites/")
         (src (string-append dir name "-generated.png"))
         (im (car (gimp-file-load RUN-NONINTERACTIVE src src)))
         (base (car (gimp-image-get-active-layer im)))
         (master 0) (mask 0) (bright 0) (dark 0) (ordinary 0))
    (gimp-item-set-name base "00 Retained generation - unmodified")
    (set! master (sprite-layer im base "01 Master - editable alpha cleanup"))
    (set! mask (car (gimp-layer-create-mask master ADD-ALPHA-TRANSFER-MASK)))
    (gimp-layer-add-mask master mask)
    ; Generated interiors peak near alpha 253. Make bodies fully opaque and
    ; remove nearly invisible fringe without thresholding fine hair edges.
    (gimp-levels mask HISTOGRAM-VALUE 5 253 1.0 0 255)
    (gimp-item-set-visible base FALSE)
    (if (string=? name "senn-ceremonial")
        (set! master (senn-embroidery im master)))
    (if (string=? name "tessa-ceremony")
        (set! master (ceremony-badge im master)))
    (export-png im master (string-append dir name "-neutral.png"))
    (set! ordinary (sprite-layer im master "02 Ordinary - insistent reflected light"))
    (gimp-curves-spline ordinary HISTOGRAM-VALUE 10 #(0 2 64 62 128 143 192 214 255 255))
    (gimp-item-set-visible master FALSE)
    (export-png im ordinary (string-append "visual-novel/renpy/game/art/sprites/" name "-ordinary.png"))
    (gimp-item-set-visible ordinary FALSE)
    (set! bright (sprite-layer im master "03 Summoning - severe room-wide bounce"))
    (gimp-curves-spline bright HISTOGRAM-VALUE 10 #(0 55 50 158 100 220 170 251 255 255))
    (export-png im bright (string-append "visual-novel/renpy/game/art/sprites/" name "-bright.png"))
    (gimp-item-set-visible bright FALSE)
    (set! dark (sprite-layer im master "04 Night - limited cold reflected light"))
    (gimp-curves-spline dark HISTOGRAM-VALUE 10 #(0 0 64 15 128 48 192 103 255 176))
    (gimp-curves-spline dark HISTOGRAM-BLUE 6 #(0 3 100 114 255 255))
    (export-png im dark (string-append "visual-novel/renpy/game/art/sprites/" name "-dark.png"))
    (gimp-item-set-visible dark FALSE)
    (gimp-item-set-visible master TRUE)
    (gimp-xcf-save RUN-NONINTERACTIVE im master (string-append dir name ".xcf") (string-append dir name ".xcf"))
    (gimp-image-delete im)))
(finish-sprite "tessa-arrival")
(finish-sprite "mara-indoor")
(finish-sprite "senn-ceremonial")
(finish-sprite "iven-treatment")
(finish-sprite "tessa-cloaked")
(finish-sprite "tessa-first-treatment")
(finish-sprite "tessa-ceremony")
(finish-sprite "tessa-phone")
(gimp-quit 0)
