; Local reflected-light correction. No generative head/identity edit is used.
(let* ((src "visual-novel/art/presentation-v2/raw/sealed-arch.png")
 (im (car (gimp-file-load RUN-NONINTERACTIVE src src)))
 (base (car (gimp-image-get-active-layer im)))
 (bounce (car (gimp-layer-copy base TRUE)))
 (mask 0)
 (xcf "visual-novel/art/presentation-v2/masters/sealed-arch.xcf")
 (out "visual-novel/renpy/game/art/cg/sealed-arch.png"))
 (gimp-item-set-name base "00 Original - face, hairline, hands and architecture unchanged")
 (gimp-image-insert-layer im bounce 0 0)
 (gimp-item-set-name bounce "01 Pale stone bounce across both figures - broad feathered mask")
 ; Lift the shadow-facing planes receiving reflected light from pale stone.
 ; The hard incident highlights and hair geometry remain from the base image.
 (gimp-curves-spline bounce HISTOGRAM-VALUE 14 #(0 0 26 30 64 109 115 183 170 229 223 251 255 255))
 (gimp-layer-set-opacity bounce 88)
 (gimp-image-select-ellipse im CHANNEL-OP-REPLACE 18 -150 1800 1300)
 (gimp-selection-feather im 110)
 (set! mask (car (gimp-layer-create-mask bounce ADD-SELECTION-MASK)))
 (gimp-layer-add-mask bounce mask)
 (gimp-selection-none im)
 (gimp-xcf-save RUN-NONINTERACTIVE im bounce xcf xcf)
 (let ((flat (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE))))
  (file-png-save RUN-NONINTERACTIVE im flat out out 0 9 0 0 0 0 0)
  (let ((copy (car (gimp-image-duplicate im))))
   (gimp-image-crop copy 355 330 406 130)
   (file-png-save RUN-NONINTERACTIVE copy (car (gimp-image-get-active-layer copy)) "/tmp/vn-bright-tessa.png" "/tmp/vn-bright-tessa.png" 0 9 0 0 0 0 0)
   (gimp-image-delete copy))
  (let ((copy (car (gimp-image-duplicate im))))
   (gimp-image-crop copy 370 369 1022 0)
   (file-png-save RUN-NONINTERACTIVE copy (car (gimp-image-get-active-layer copy)) "/tmp/vn-bright-senn.png" "/tmp/vn-bright-senn.png" 0 9 0 0 0 0 0)
   (gimp-image-delete copy)))
 (gimp-image-delete im))
(gimp-quit 0)
