; GIMP 2.10. Controlled component assembly; run from repository root.
(define seq-root "visual-novel/art/opening-sequence/")
(define seq-out "visual-novel/renpy/game/art/opening/")
(define (seq-export im path)
 (let* ((copy (car (gimp-image-duplicate im)))
        (flat (car (gimp-image-merge-visible-layers copy CLIP-TO-IMAGE))))
  (file-png-save RUN-NONINTERACTIVE copy flat path path 0 9 0 0 0 0 0)
  (gimp-image-delete copy)))
(define (seq-save im name)
 (let ((path (string-append seq-root "masters/" name ".xcf")))
  (gimp-xcf-save RUN-NONINTERACTIVE im (car (gimp-image-get-active-layer im)) path path)))
(define (seq-sprite name)
 (let* ((path (string-append seq-root "raw/" name ".png"))
        (im (car (gimp-file-load RUN-NONINTERACTIVE path path)))
        (base (car (gimp-image-get-active-layer im)))
        (clean (car (gimp-layer-copy base TRUE)))
        (bright 0) (night 0))
  (gimp-item-set-name base "00 Generated original alpha - retained hidden")
  (gimp-item-set-visible base FALSE)
  (gimp-image-insert-layer im clean 0 0)
  (gimp-item-set-name clean "01 Alpha edge cleanup - ordinary light")
  (gimp-levels clean HISTOGRAM-ALPHA 40 250 1.0 0 255)
  (seq-export im (string-append seq-out "sprites/" name ".png"))
  (set! bright (car (gimp-layer-copy clean TRUE)))
  (gimp-image-insert-layer im bright 0 0)
  (gimp-item-set-name bright "02 Temple reflected glare - shared cast curve")
  (gimp-curves-spline bright HISTOGRAM-VALUE 12 #(0 8 48 90 96 158 150 220 210 249 255 255))
  (seq-export im (string-append seq-out "sprites/" name "-bright.png"))
  (gimp-item-set-visible bright FALSE)
  (set! night (car (gimp-layer-copy clean TRUE)))
  (gimp-image-insert-layer im night 0 0)
  (gimp-item-set-name night "03 Night ambience - candle warmth preserved")
  (gimp-curves-spline night HISTOGRAM-VALUE 12 #(0 0 48 12 96 42 150 92 210 159 255 206))
  (gimp-color-balance night MIDTONES TRUE -8 0 10)
  (seq-export im (string-append seq-out "sprites/" name "-night.png"))
  (gimp-item-set-visible night FALSE)
  (seq-save im name)
  (gimp-image-delete im)))
(define (seq-arrival)
 (let* ((src (string-append seq-root "raw/arrival.png"))
        (im (car (gimp-file-load RUN-NONINTERACTIVE src src)))
        (base (car (gimp-image-get-active-layer im)))
        (patch (car (gimp-file-load-layer RUN-NONINTERACTIVE im (string-append seq-root "raw/arrival-props.png"))))
        (grade 0))
  (gimp-item-set-name base "00 Original faces, bodies, architecture and layout")
  (gimp-image-insert-layer im patch 0 0)
  (gimp-item-set-name patch "01 Carton and lever pivot only - separate local mask")
  (gimp-image-select-rectangle im CHANNEL-OP-REPLACE 530 394 97 206)
  (gimp-image-select-rectangle im CHANNEL-OP-ADD 1460 289 88 125)
  (gimp-selection-feather im 5)
  (gimp-layer-add-mask patch (car (gimp-layer-create-mask patch ADD-SELECTION-MASK)))
  (gimp-selection-none im)
  (set! grade (car (gimp-layer-new-from-visible im im "02 Shared stone bounce - temple only")))
  (gimp-image-insert-layer im grade 0 0)
  (gimp-curves-spline grade HISTOGRAM-VALUE 12 #(0 8 48 79 96 148 150 207 210 248 255 255))
  ; Exclude the modern street. Feather at the architectural boundary only.
  (gimp-image-select-polygon im CHANNEL-OP-REPLACE 18 #(395 0 1672 0 1672 941 0 941 0 760 366 683 365 194 294 0 395 0))
  (gimp-selection-feather im 8)
  (gimp-layer-add-mask grade (car (gimp-layer-create-mask grade ADD-SELECTION-MASK)))
  (gimp-selection-none im)
  (seq-save im "arrival")
  (seq-export im (string-append seq-out "cg/arrival.png"))
  (gimp-image-delete im)))
(define (seq-plate name category)
 (let* ((p (string-append seq-root "raw/" name ".png"))
        (im (car (gimp-file-load RUN-NONINTERACTIVE p p)))
        (base (car (gimp-image-get-active-layer im)))
        (lit (car (gimp-layer-copy base TRUE))))
  (gimp-item-set-name base "00 Original scene state")
  (gimp-image-insert-layer im lit 0 0)
  (gimp-item-set-name lit "01 Shared temple reflected light")
  (gimp-curves-spline lit HISTOGRAM-VALUE 12 #(0 8 48 79 96 148 150 207 210 248 255 255))
  (seq-save im name)
  (seq-export im (string-append seq-out category "/" name ".png"))
  (gimp-image-delete im)))
; Concrete batch recipes live in finish-opening-assets.scm.
(define (seq-load name)
 (let ((p (string-append seq-root "raw/" name ".png")))
  (car (gimp-file-load RUN-NONINTERACTIVE p p))))
(define (seq-patch im name label rectangles)
 (let ((layer (car (gimp-file-load-layer RUN-NONINTERACTIVE im (string-append seq-root "raw/" name ".png")))))
  (gimp-image-insert-layer im layer 0 0)
  (gimp-item-set-name layer label)
  (gimp-selection-none im)
  (for-each (lambda (r) (apply gimp-image-select-rectangle (append (list im CHANNEL-OP-ADD) r))) rectangles)
  (gimp-selection-feather im 4)
  (gimp-layer-add-mask layer (car (gimp-layer-create-mask layer ADD-SELECTION-MASK)))
  (gimp-selection-none im)
  layer))
(define (seq-grocery-and-control im)
 (let ((layer (car (gimp-file-load-layer RUN-NONINTERACTIVE im (string-append seq-root "raw/closure.png")))))
  (gimp-image-insert-layer im layer 0 0)
  (gimp-item-set-name layer "Groceries silhouette and depressed control - protect guard legs")
  (gimp-image-select-polygon im CHANNEL-OP-REPLACE 24 #(554 669 592 632 645 606 668 615 687 648 743 647 775 661 782 706 738 733 621 729 556 712 554 669))
  (gimp-image-select-polygon im CHANNEL-OP-ADD 18 #(1268 170 1490 170 1535 346 1600 365 1600 435 1440 435 1440 677 1268 677 1268 170))
  (gimp-selection-feather im 2)
  (gimp-layer-add-mask layer (car (gimp-layer-create-mask layer ADD-SELECTION-MASK)))
  (gimp-selection-none im)
  layer))
(define (seq-grade im mode earth)
 (let ((layer (car (gimp-layer-new-from-visible im im "Shared scene light - independent masked grade"))))
  (gimp-image-insert-layer im layer 0 0)
  (cond
   ((equal? mode "bright") (gimp-curves-spline layer HISTOGRAM-VALUE 12 #(0 8 48 79 96 148 150 207 210 248 255 255)))
   ((equal? mode "ordinary") (gimp-curves-spline layer HISTOGRAM-VALUE 12 #(0 0 48 36 96 97 150 173 210 231 255 255)))
   ((equal? mode "night") (gimp-curves-spline layer HISTOGRAM-VALUE 12 #(0 0 48 24 96 64 150 121 210 191 255 239))))
  (if (= earth TRUE)
   (begin
    (gimp-image-select-polygon im CHANNEL-OP-REPLACE 18 #(395 0 1672 0 1672 941 0 941 0 760 366 683 365 194 294 0 395 0))
    (gimp-selection-feather im 8)
    (gimp-layer-add-mask layer (car (gimp-layer-create-mask layer ADD-SELECTION-MASK)))
    (gimp-selection-none im)))
  layer))
(define (seq-deliver im name category)
 (seq-save im name)
 (seq-export im (string-append seq-out category "/" name ".png"))
 (gimp-image-delete im))
(define (seq-crop path x y w h output)
 (let ((im (car (gimp-file-load RUN-NONINTERACTIVE path path))))
  (gimp-image-crop im w h x y)
  (seq-export im output)
  (gimp-image-delete im)))
