(load "visual-novel/tools/finish-opening.scm")
(define (standing-corruption im)
 (let ((layer (car (gimp-file-load-layer RUN-NONINTERACTIVE im (string-append seq-root "raw/blue-final.png")))))
  (gimp-image-insert-layer im layer 0 0)
  (gimp-item-set-name layer "Corruption retained from wrist toward elbow before white purification")
  (gimp-layer-set-offsets layer 67 53)
  (gimp-image-select-polygon im CHANNEL-OP-REPLACE 18 #(790 663 827 650 984 632 1012 644 1031 667 1021 692 854 710 797 708 790 663))
  (gimp-selection-feather im 7)
  (gimp-layer-add-mask layer (car (gimp-layer-create-mask layer ADD-SELECTION-MASK)))
  (gimp-selection-none im)))

(let ((im (seq-load "ward-standing")))
 (standing-corruption im)
 (seq-grade im "ordinary" FALSE)
 (seq-deliver im "ward-standing-unlit" "cg"))
(let* ((im (seq-load "ward-standing"))
       (light (car (gimp-layer-new im 1672 941 RGBA-IMAGE "Small white light and shared falloff on both hands" 100 SCREEN-MODE))))
 (gimp-image-insert-layer im light 0 0)
 (gimp-context-set-foreground '(89 94 102))
 (gimp-image-select-ellipse im CHANNEL-OP-REPLACE 488 534 131 122)
 (gimp-selection-feather im 45)
 (gimp-edit-fill light FOREGROUND-FILL)
 (gimp-context-set-foreground '(211 219 225))
 (gimp-image-select-ellipse im CHANNEL-OP-REPLACE 541 581 24 24)
 (gimp-selection-feather im 12)
 (gimp-edit-fill light FOREGROUND-FILL)
 (gimp-context-set-foreground '(254 254 255))
 (gimp-image-select-ellipse im CHANNEL-OP-REPLACE 548 588 10 9)
 (gimp-selection-feather im 3)
 (gimp-edit-fill light FOREGROUND-FILL)
 (gimp-selection-none im)
 (standing-corruption im)
 (seq-grade im "ordinary" FALSE)
 (seq-deliver im "ward-standing-light" "cg"))
(gimp-quit 0)
