(load "visual-novel/tools/relight-opening.scm")
(for-each (lambda (name) (light-scene name "cg" "bright" TRUE name))
 '("arrival" "attempted-return" "phone-message" "milk-impact"))
(for-each (lambda (name) (light-scene name "cg" "bright" FALSE name))
 '("closure" "pleading-mother" "woman-release" "stretcher-passes" "unanswered-cloak"))
(for-each (lambda (name) (light-scene name "bg" "bright" FALSE name))
 '("arch-guards-raised" "arch-conversation"))
(for-each (lambda (name) (light-scene name "sprites" "bright" FALSE (string-append name "-bright")))
 '("tessa-question" "tessa-refusal" "tessa-phone" "senn-speaking" "mara-cloak-corrected"))
(for-each (lambda (name) (light-scene name "cg" "night" FALSE name))
 '("apartment-window" "blocked-doorway" "cloak-discarded" "chair-barricade" "drawing-letter" "drawing-restart"))
(for-each (lambda (name) (light-scene name "bg" "night" FALSE name))
 '("apartment-open" "apartment-locked"))
(for-each (lambda (name) (light-scene name "sprites" "night" FALSE (string-append name "-night")))
 '("tessa-cloaked" "mara-supper" "tessa-refusal"))
(for-each (lambda (name) (light-scene name "cg" "ordinary" FALSE name))
 '("ward-entrance" "blue-healing" "ward-standing-unlit" "ward-standing-light" "first-purification" "last-patch" "purification-cleared" "treatment-pause" "after-first-treatment"))
(seq-crop "visual-novel/renpy/game/art/opening/cg/treatment-pause.png" 780 428 880 495 "visual-novel/renpy/game/art/opening/cg/rested-hand.png")
(seq-crop "visual-novel/renpy/game/art/opening/cg/drawing-restart.png" 718 704 586 204 "visual-novel/renpy/game/art/opening/cg/detail-drawing.png")
(seq-crop "visual-novel/renpy/game/art/opening/cg/drawing-restart.png" 1310 746 275 160 "visual-novel/renpy/game/art/opening/cg/detail-phone.png")
