(let* ((im(car(gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/s057-father/first-candidate.png" "visual-novel/art/scene-studies/s057-father/first-candidate.png")))(l 0)(m 0)(f 0))
(set! l(car(gimp-file-load-layer RUN-NONINTERACTIVE im "visual-novel/art/scene-studies/s057-father/bearers-wagon-donor.png")))
(gimp-image-insert-layer im l 0 0)(gimp-item-set-name l "Distinct older porter head")
(set! m(car(gimp-layer-create-mask l ADD-BLACK-MASK)))(gimp-layer-add-mask l m)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 16 #(62 2 282 2 294 174 259 211 214 224 170 203 131 172 68 137))
(gimp-selection-feather im 7)(gimp-edit-fill m WHITE-FILL)(gimp-selection-none im)
(set! l(car(gimp-file-load-layer RUN-NONINTERACTIVE im "visual-novel/art/scene-studies/s057-father/bearers-wagon-donor.png")))
(gimp-image-insert-layer im l 0 0)(gimp-item-set-name l "Distinct red-haired porter head")
(set! m(car(gimp-layer-create-mask l ADD-BLACK-MASK)))(gimp-layer-add-mask l m)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 16 #(1401 12 1607 12 1625 130 1590 183 1565 229 1515 229 1460 206 1407 157))
(gimp-selection-feather im 7)(gimp-edit-fill m WHITE-FILL)(gimp-selection-none im)
(set! l(car(gimp-file-load-layer RUN-NONINTERACTIVE im "visual-novel/art/scene-studies/s057-father/bearers-wagon-donor.png")))
(gimp-image-insert-layer im l 0 0)(gimp-item-set-name l "Unmarked wagon canvas")
(set! m(car(gimp-layer-create-mask l ADD-BLACK-MASK)))(gimp-layer-add-mask l m)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 8 #(1134 304 1183 306 1188 365 1139 371))
(gimp-selection-feather im 5)(gimp-edit-fill m WHITE-FILL)(gimp-selection-none im)
(gimp-xcf-save RUN-NONINTERACTIVE im l "visual-novel/art/scene-studies/s057-father/native-master.xcf" "visual-novel/art/scene-studies/s057-father/native-master.xcf")
(set! f(car(gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save RUN-NONINTERACTIVE im f "visual-novel/art/scene-studies/s057-father/native-candidate.png" "visual-novel/art/scene-studies/s057-father/native-candidate.png" 0 9 0 0 0 0 0)
(gimp-image-delete im))(gimp-quit 0)