(let* ((im(car(gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/s057-father/native-master.xcf" "visual-novel/art/scene-studies/s057-father/native-master.xcf")))(bg 0)(f 0)(base 0)(m 0))
(set! base (vector-ref (cadr(gimp-image-get-layers im)) 0))
(set! base (vector-ref (cadr(gimp-image-get-layers im)) (- (car(gimp-image-get-layers im)) 1)))
(gimp-image-resize im 2240 1260 284 100)
(set! m(car(gimp-layer-create-mask base ADD-BLACK-MASK)))(gimp-layer-add-mask base m)
(gimp-image-select-rectangle im CHANNEL-OP-REPLACE 340 118 1590 880)
(gimp-selection-feather im 24)(gimp-edit-fill m WHITE-FILL)(gimp-selection-none im)
(set! bg(car(gimp-file-load-layer RUN-NONINTERACTIVE im "visual-novel/art/scene-studies/s057-father/peripheral-donor.png")))
(gimp-image-insert-layer im bg 0 (car(gimp-image-get-layers im)))
(gimp-layer-scale bg 2240 1260 TRUE)(gimp-layer-set-offsets bg 0 0)
(gimp-item-set-name bg "Peripheral gate, porter boots and trestle feet")
(gimp-xcf-save RUN-NONINTERACTIVE im bg "visual-novel/art/scene-studies/s057-father/framed-master.xcf" "visual-novel/art/scene-studies/s057-father/framed-master.xcf")
(set! f(car(gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save RUN-NONINTERACTIVE im f "visual-novel/art/scene-studies/s057-father/framed-candidate.png" "visual-novel/art/scene-studies/s057-father/framed-candidate.png" 0 9 0 0 0 0 0)
(gimp-image-delete im))(gimp-quit 0)
