(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-minor-details/s010-bellweir-hills/before.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-minor-details/s010-bellweir-hills/before.png"))) (l 0) (mask 0) (out 0))
(gimp-item-set-name (car (gimp-image-get-active-layer im)) "Current neutral original — unchanged")
(set! l (car (gimp-file-load-layer RUN-NONINTERACTIVE im "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-minor-details/components/s010-forest-helmet-donor.png")))
(gimp-image-insert-layer im l 0 0)
(gimp-layer-scale l 235 320 TRUE)
(gimp-layer-set-offsets l 330 220)
(gimp-item-set-name l "Five readable forest helmets fitted around natural horn pairs")
(set! mask (car (gimp-layer-create-mask l ADD-BLACK-MASK)))
(gimp-layer-add-mask l mask)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 8 #(352 254 374 254 374 276 352 276))
(gimp-selection-feather im 0.65)
(gimp-context-set-foreground '(255 255 255))
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none im)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 8 #(382 234 403 234 403 252 382 252))
(gimp-selection-feather im 0.65)
(gimp-context-set-foreground '(255 255 255))
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none im)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 8 #(414 291 442 291 442 316 414 316))
(gimp-selection-feather im 0.65)
(gimp-context-set-foreground '(255 255 255))
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none im)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 8 #(488 273 513 273 513 294 488 294))
(gimp-selection-feather im 0.65)
(gimp-context-set-foreground '(255 255 255))
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none im)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 8 #(474 321 504 321 504 343 474 343))
(gimp-selection-feather im 0.65)
(gimp-context-set-foreground '(255 255 255))
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none im)
(set! l (car (gimp-file-load-layer RUN-NONINTERACTIVE im "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-minor-details/components/s010-river-helmets-flag-donor.png")))
(gimp-image-insert-layer im l 0 0)
(gimp-layer-scale l 230 290 TRUE)
(gimp-layer-set-offsets l 840 275)
(gimp-item-set-name l "River column helmet openings and northern white eight-point star")
(set! mask (car (gimp-layer-create-mask l ADD-BLACK-MASK)))
(gimp-layer-add-mask l mask)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 8 #(891 401 926 401 926 428 891 428))
(gimp-selection-feather im 0.65)
(gimp-context-set-foreground '(255 255 255))
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none im)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 8 #(944 429 979 429 979 455 944 455))
(gimp-selection-feather im 0.65)
(gimp-context-set-foreground '(255 255 255))
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none im)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 8 #(1005 457 1040 457 1040 486 1005 486))
(gimp-selection-feather im 0.65)
(gimp-context-set-foreground '(255 255 255))
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none im)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 8 #(866 304 884 304 884 345 866 345))
(gimp-selection-feather im 0.65)
(gimp-context-set-foreground '(255 255 255))
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none im)
(set! l (car (gimp-layer-new im 230 290 RGBA-IMAGE "Visible center split in white northern banner star" 100 NORMAL-MODE)))
(gimp-image-insert-layer im l 0 0)
(gimp-context-set-foreground '(15 29 23))
(gimp-edit-fill l FOREGROUND-FILL)
(gimp-layer-set-offsets l 840 275)
(set! mask (car (gimp-layer-create-mask l ADD-BLACK-MASK)))
(gimp-layer-add-mask l mask)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 8 #(875.0 306 875.85 306 875.85 345 875.0 345))
(gimp-selection-feather im 0)
(gimp-context-set-foreground '(255 255 255))
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none im)
(gimp-xcf-save RUN-NONINTERACTIVE im l "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-minor-details/s010-bellweir-hills/repair-master.xcf" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-minor-details/s010-bellweir-hills/repair-master.xcf")
(set! out (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save2 RUN-NONINTERACTIVE im out "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-minor-details/s010-bellweir-hills/candidate.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-minor-details/s010-bellweir-hills/candidate.png" 0 9 0 0 0 0 0 0 0)
(gimp-image-delete im))
(gimp-quit 0)
