(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-minor-details/s037-relief-camp/before.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-minor-details/s037-relief-camp/before.png"))) (l 0) (mask 0) (out 0))
(gimp-item-set-name (car (gimp-image-get-active-layer im)) "Current neutral original — unchanged")
(set! l (car (gimp-image-get-active-layer im)))
(set! mask (car (gimp-layer-create-mask l ADD-ALPHA-TRANSFER-MASK)))
(gimp-layer-add-mask l mask)
(gimp-layer-remove-mask l MASK-DISCARD)
(set! l (car (gimp-file-load-layer RUN-NONINTERACTIVE im "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-minor-details/components/s037-solid-near-horn-donor.png")))
(gimp-image-insert-layer im l 0 0)
(gimp-layer-scale l 210 215 TRUE)
(gimp-layer-set-offsets l 680 100)
(gimp-item-set-name l "Existing ghost near horn made solid; far horn and face untouched")
(set! mask (car (gimp-layer-create-mask l ADD-BLACK-MASK)))
(gimp-layer-add-mask l mask)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 18 #(727 134 746 131 764 140 772 152 766 173 751 185 738 179 730 163 725 151))
(gimp-selection-feather im 1)
(gimp-context-set-foreground '(255 255 255))
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none im)
(gimp-xcf-save RUN-NONINTERACTIVE im l "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-minor-details/s037-relief-camp/repair-master.xcf" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-minor-details/s037-relief-camp/repair-master.xcf")
(set! out (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save2 RUN-NONINTERACTIVE im out "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-minor-details/s037-relief-camp/candidate.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-minor-details/s037-relief-camp/candidate.png" 0 9 0 0 0 0 0 0 0)
(gimp-image-delete im))
(gimp-quit 0)
