(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-minor-details/s058-bellweir-market-spring/before.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-minor-details/s058-bellweir-market-spring/before.png"))) (l 0) (mask 0) (out 0))
(gimp-item-set-name (car (gimp-image-get-active-layer im)) "Current neutral original — unchanged")
(set! l (car (gimp-file-load-layer RUN-NONINTERACTIVE im "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-minor-details/components/s058-orren-likeness-donor.png")))
(gimp-image-insert-layer im l 0 0)
(gimp-layer-scale l 105 165 TRUE)
(gimp-layer-set-offsets l 1370 245)
(gimp-item-set-name l "Orren early forties long chin and receding hair; current lettering protected")
(set! mask (car (gimp-layer-create-mask l ADD-BLACK-MASK)))
(gimp-layer-add-mask l mask)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 18 #(1426 268 1447 268 1470 273 1474 288 1474 320 1458 336 1443 332 1435 314 1426 302))
(gimp-selection-feather im 1.2)
(gimp-context-set-foreground '(255 255 255))
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none im)
(set! l (car (gimp-file-load-layer RUN-NONINTERACTIVE im "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-minor-details/components/s058-cart-wheel-donor.png")))
(gimp-image-insert-layer im l 0 0)
(gimp-layer-scale l 270 410 TRUE)
(gimp-layer-set-offsets l 1650 490)
(gimp-item-set-name l "Matching spoked cart wheel at coherent far axle; near wheel untouched")
(set! mask (car (gimp-layer-create-mask l ADD-BLACK-MASK)))
(gimp-layer-add-mask l mask)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 22 #(1721 636 1747 635 1768 646 1783 680 1786 741 1772 774 1753 786 1729 782 1713 760 1707 720 1709 677))
(gimp-selection-feather im 1.6)
(gimp-context-set-foreground '(255 255 255))
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none im)
(gimp-xcf-save RUN-NONINTERACTIVE im l "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-minor-details/s058-bellweir-market-spring/repair-master.xcf" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-minor-details/s058-bellweir-market-spring/repair-master.xcf")
(set! out (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save2 RUN-NONINTERACTIVE im out "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-minor-details/s058-bellweir-market-spring/candidate.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-minor-details/s058-bellweir-market-spring/candidate.png" 0 9 0 0 0 0 0 0 0)
(gimp-image-delete im))
(gimp-quit 0)
