(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-minor-details/s037-relief-camp/repair-master.xcf" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-minor-details/s037-relief-camp/repair-master.xcf"))) (layers (gimp-image-get-layers im)) (mi (car (gimp-image-new 1920 1080 RGB))) (bg (car (gimp-layer-new mi 1920 1080 RGBA-IMAGE "Black outside repair masks" 100 NORMAL-MODE))) (j 0) (l 0) (mask 0) (ml 0) (off 0) (merged 0))
(gimp-image-insert-layer mi bg 0 0)
(gimp-context-set-foreground '(0 0 0))
(gimp-edit-fill bg FOREGROUND-FILL)
(while (< j (car layers))
 (set! l (vector-ref (cadr layers) j))
 (set! mask (car (gimp-layer-get-mask l)))
 (if (> mask -1)
  (begin
   (set! off (gimp-drawable-offsets l))
   (set! ml (car (gimp-layer-new-from-drawable mask mi)))
   (gimp-image-insert-layer mi ml 0 0)
   (gimp-layer-set-offsets ml (car off) (cadr off))
   (gimp-layer-set-mode ml LIGHTEN-ONLY-MODE)))
 (set! j (+ j 1)))
(set! merged (car (gimp-image-merge-visible-layers mi CLIP-TO-IMAGE)))
(file-png-save2 RUN-NONINTERACTIVE mi merged "/tmp/batch6-minor-details-checks/s037-relief-camp-mask.png" "mask" 0 9 0 0 0 0 0 0 0)
(set! merged (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save2 RUN-NONINTERACTIVE im merged "/tmp/batch6-minor-details-checks/s037-relief-camp-reopened.png" "reopened" 0 9 0 0 0 0 0 0 0)
(gimp-image-delete mi)
(gimp-image-delete im))
(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-minor-details/s043-seasons/repair-master.xcf" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-minor-details/s043-seasons/repair-master.xcf"))) (layers (gimp-image-get-layers im)) (mi (car (gimp-image-new 1920 1080 RGB))) (bg (car (gimp-layer-new mi 1920 1080 RGBA-IMAGE "Black outside repair masks" 100 NORMAL-MODE))) (j 0) (l 0) (mask 0) (ml 0) (off 0) (merged 0))
(gimp-image-insert-layer mi bg 0 0)
(gimp-context-set-foreground '(0 0 0))
(gimp-edit-fill bg FOREGROUND-FILL)
(while (< j (car layers))
 (set! l (vector-ref (cadr layers) j))
 (set! mask (car (gimp-layer-get-mask l)))
 (if (> mask -1)
  (begin
   (set! off (gimp-drawable-offsets l))
   (set! ml (car (gimp-layer-new-from-drawable mask mi)))
   (gimp-image-insert-layer mi ml 0 0)
   (gimp-layer-set-offsets ml (car off) (cadr off))
   (gimp-layer-set-mode ml LIGHTEN-ONLY-MODE)))
 (set! j (+ j 1)))
(set! merged (car (gimp-image-merge-visible-layers mi CLIP-TO-IMAGE)))
(file-png-save2 RUN-NONINTERACTIVE mi merged "/tmp/batch6-minor-details-checks/s043-seasons-mask.png" "mask" 0 9 0 0 0 0 0 0 0)
(set! merged (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save2 RUN-NONINTERACTIVE im merged "/tmp/batch6-minor-details-checks/s043-seasons-reopened.png" "reopened" 0 9 0 0 0 0 0 0 0)
(gimp-image-delete mi)
(gimp-image-delete im))
(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-minor-details/s058-bellweir-market-spring/repair-master.xcf" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-minor-details/s058-bellweir-market-spring/repair-master.xcf"))) (layers (gimp-image-get-layers im)) (mi (car (gimp-image-new 1920 1080 RGB))) (bg (car (gimp-layer-new mi 1920 1080 RGBA-IMAGE "Black outside repair masks" 100 NORMAL-MODE))) (j 0) (l 0) (mask 0) (ml 0) (off 0) (merged 0))
(gimp-image-insert-layer mi bg 0 0)
(gimp-context-set-foreground '(0 0 0))
(gimp-edit-fill bg FOREGROUND-FILL)
(while (< j (car layers))
 (set! l (vector-ref (cadr layers) j))
 (set! mask (car (gimp-layer-get-mask l)))
 (if (> mask -1)
  (begin
   (set! off (gimp-drawable-offsets l))
   (set! ml (car (gimp-layer-new-from-drawable mask mi)))
   (gimp-image-insert-layer mi ml 0 0)
   (gimp-layer-set-offsets ml (car off) (cadr off))
   (gimp-layer-set-mode ml LIGHTEN-ONLY-MODE)))
 (set! j (+ j 1)))
(set! merged (car (gimp-image-merge-visible-layers mi CLIP-TO-IMAGE)))
(file-png-save2 RUN-NONINTERACTIVE mi merged "/tmp/batch6-minor-details-checks/s058-bellweir-market-spring-mask.png" "mask" 0 9 0 0 0 0 0 0 0)
(set! merged (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save2 RUN-NONINTERACTIVE im merged "/tmp/batch6-minor-details-checks/s058-bellweir-market-spring-reopened.png" "reopened" 0 9 0 0 0 0 0 0 0)
(gimp-image-delete mi)
(gimp-image-delete im))
(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-minor-details/s010-bellweir-hills/repair-master.xcf" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-minor-details/s010-bellweir-hills/repair-master.xcf"))) (layers (gimp-image-get-layers im)) (mi (car (gimp-image-new 1920 1080 RGB))) (bg (car (gimp-layer-new mi 1920 1080 RGBA-IMAGE "Black outside repair masks" 100 NORMAL-MODE))) (j 0) (l 0) (mask 0) (ml 0) (off 0) (merged 0))
(gimp-image-insert-layer mi bg 0 0)
(gimp-context-set-foreground '(0 0 0))
(gimp-edit-fill bg FOREGROUND-FILL)
(while (< j (car layers))
 (set! l (vector-ref (cadr layers) j))
 (set! mask (car (gimp-layer-get-mask l)))
 (if (> mask -1)
  (begin
   (set! off (gimp-drawable-offsets l))
   (set! ml (car (gimp-layer-new-from-drawable mask mi)))
   (gimp-image-insert-layer mi ml 0 0)
   (gimp-layer-set-offsets ml (car off) (cadr off))
   (gimp-layer-set-mode ml LIGHTEN-ONLY-MODE)))
 (set! j (+ j 1)))
(set! merged (car (gimp-image-merge-visible-layers mi CLIP-TO-IMAGE)))
(file-png-save2 RUN-NONINTERACTIVE mi merged "/tmp/batch6-minor-details-checks/s010-bellweir-hills-mask.png" "mask" 0 9 0 0 0 0 0 0 0)
(set! merged (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save2 RUN-NONINTERACTIVE im merged "/tmp/batch6-minor-details-checks/s010-bellweir-hills-reopened.png" "reopened" 0 9 0 0 0 0 0 0 0)
(gimp-image-delete mi)
(gimp-image-delete im))
(gimp-quit 0)
