(gimp-context-push)
(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s018-gray-scar-ferry-approach/source.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s018-gray-scar-ferry-approach/source.png"))))
(gimp-item-set-name (car (gimp-image-get-active-layer im)) "Current source with Claude repairs")
(let* ((ly (car (gimp-layer-new im 1920 1080 RGBA-IMAGE "Complete left and right rear escort strings to both bow tips" 100 NORMAL-MODE))))
(gimp-image-insert-layer im ly 0 0)
(gimp-context-set-brush "2. Hardness 075")
(gimp-context-set-brush-size 1.0)
(gimp-context-set-foreground (list 177 166 146))
(gimp-paintbrush-default ly 4 (vector 1195.06 622.48 1190.3 643.0))
(gimp-paintbrush-default ly 4 (vector 1291.36 654.82 1289.8 674.2))
)
(gimp-xcf-save RUN-NONINTERACTIVE im (car (gimp-image-get-active-layer im)) "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s018-gray-scar-ferry-approach/master.xcf" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s018-gray-scar-ferry-approach/master.xcf")
(let* ((dup (car (gimp-image-duplicate im))))
(gimp-image-merge-visible-layers dup CLIP-TO-IMAGE)
(file-png-save RUN-NONINTERACTIVE dup (car (gimp-image-get-active-layer dup)) "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s018-gray-scar-ferry-approach/candidate.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s018-gray-scar-ferry-approach/candidate.png" 0 9 0 0 0 0 0)
(gimp-image-delete dup))
(let* ((dup (car (gimp-image-duplicate im))))
(gimp-image-merge-visible-layers dup CLIP-TO-IMAGE)
(gimp-image-crop dup 235 280 1110 500)
(file-png-save RUN-NONINTERACTIVE dup (car (gimp-image-get-active-layer dup)) "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s018-gray-scar-ferry-approach/bows-after.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s018-gray-scar-ferry-approach/bows-after.png" 0 9 0 0 0 0 0)
(gimp-image-delete dup))
(gimp-image-delete im))
(let* ((re (car (gimp-file-load RUN-NONINTERACTIVE "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s018-gray-scar-ferry-approach/master.xcf" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s018-gray-scar-ferry-approach/master.xcf"))))
(gimp-image-merge-visible-layers re CLIP-TO-IMAGE)
(file-png-save RUN-NONINTERACTIVE re (car (gimp-image-get-active-layer re)) "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s018-gray-scar-ferry-approach/reopened.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s018-gray-scar-ferry-approach/reopened.png" 0 9 0 0 0 0 0)
(gimp-image-delete re))
(gimp-context-pop)
(gimp-quit 0)
