(let* ((img(car(gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/s043-upper-stores/casting-master.xcf" "visual-novel/art/scene-studies/s043-upper-stores/casting-master.xcf"))) (ly 0) (foundation 0))
(gimp-image-resize img 1920 1080 124 70)
(set! ly(car(gimp-file-load-layer RUN-NONINTERACTIVE img "visual-novel/art/scene-studies/s043-upper-stores/margin-component.png")))
(gimp-image-insert-layer img ly 0 0)(gimp-layer-add-alpha ly)(gimp-item-set-name ly "Environmental margins only - native original frame protected")
(gimp-context-set-interpolation INTERPOLATION-NOHALO)(gimp-layer-scale ly 1920 1080 TRUE)(gimp-layer-set-offsets ly 0 0)
(set! foundation(car(gimp-layer-copy ly TRUE)))
(gimp-image-insert-layer img foundation 0 99)(gimp-item-set-name foundation "Opaque environmental foundation beneath all feathered edges")
(gimp-image-select-rectangle img CHANNEL-OP-REPLACE 124 70 1672 940)(gimp-selection-feather img 5)(gimp-selection-invert img)
(gimp-layer-add-mask ly(car(gimp-layer-create-mask ly ADD-SELECTION-MASK)))(gimp-selection-none img)
(gimp-xcf-save RUN-NONINTERACTIVE img (car(gimp-image-get-active-layer img)) "visual-novel/art/scene-studies/s043-upper-stores/upper-stores-master.xcf" "visual-novel/art/scene-studies/s043-upper-stores/upper-stores-master.xcf")
(let* ((merged(car(gimp-image-merge-visible-layers img CLIP-TO-IMAGE))))(file-png-save RUN-NONINTERACTIVE img merged "/tmp/s043-upper-stores-final-candidate.png" "/tmp/s043-upper-stores-final-candidate.png" 0 9 0 0 0 0 0))
(gimp-image-delete img))(gimp-quit 0)
