(gimp-context-push)
(let* ((img (car (gimp-file-load RUN-NONINTERACTIVE "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch7-gray-scar/s018-gray-scar-ferry-approach/source.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch7-gray-scar/s018-gray-scar-ferry-approach/source.png"))))
(gimp-item-set-name (car (gimp-image-get-active-layer img)) "Current source — protected base")
(let* ((ly (car (gimp-file-load-layer RUN-NONINTERACTIVE img "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch7-gray-scar/s020-gray-scar-riverbank/horns-visible-donor.png"))) (mask 0))
(gimp-image-insert-layer img ly 0 0)
(gimp-item-set-name ly "Near solid backward horn")
(gimp-layer-scale ly 238 140 TRUE)
(gimp-item-transform-flip-simple ly ORIENTATION-HORIZONTAL TRUE 0)
(gimp-layer-set-offsets ly 751 302)
(set! mask (car (gimp-layer-create-mask ly ADD-BLACK-MASK)))
(gimp-layer-add-mask ly mask)
(gimp-image-select-polygon img CHANNEL-OP-REPLACE 32 (vector 840 345 845 347 852 346 862 339 871 335 879 336 887 339 890 342 888 345 880 341 875 341 870 343 862 347 855 350 850 351 843 349))
(gimp-selection-feather img 0.55)
(gimp-context-set-foreground "white")
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none img)
)
(let* ((ly (car (gimp-file-load-layer RUN-NONINTERACTIVE img "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch7-gray-scar/s020-gray-scar-riverbank/horns-visible-donor.png"))) (mask 0))
(gimp-image-insert-layer img ly 0 0)
(gimp-item-set-name ly "Far matched backward horn")
(gimp-layer-scale ly 238 140 TRUE)
(gimp-item-transform-flip-simple ly ORIENTATION-HORIZONTAL TRUE 0)
(gimp-layer-set-offsets ly 751 302)
(set! mask (car (gimp-layer-create-mask ly ADD-BLACK-MASK)))
(gimp-layer-add-mask ly mask)
(gimp-image-select-polygon img CHANNEL-OP-REPLACE 22 (vector 848 331 852 333 859 333 866 331 871 330 875 331 871 334 865 337 858 338 854 336 850 335))
(gimp-selection-feather img 0.55)
(gimp-context-set-foreground "white")
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none img)
)
(let* ((ly (car (gimp-file-load-layer RUN-NONINTERACTIVE img "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch7-gray-scar/s018-gray-scar-ferry-approach/crossbow-string-donor.png"))) (mask 0))
(gimp-image-insert-layer img ly 0 0)
(gimp-item-set-name ly "Serat complete functional crossbow and natural grips")
(gimp-layer-scale ly 497 415 TRUE)
(gimp-layer-set-offsets ly 891 409)
(set! mask (car (gimp-layer-create-mask ly ADD-BLACK-MASK)))
(gimp-layer-add-mask ly mask)
(gimp-image-select-polygon img CHANNEL-OP-REPLACE 32 (vector 995 485 1030 487 1050 503 1100 494 1124 500 1143 518 1180 525 1185 556 1162 570 1145 589 1116 606 1073 605 1055 587 1049 562 1020 550 1000 528))
(gimp-selection-feather img 2)
(gimp-context-set-foreground "white")
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none img)
)
(let* ((ly (car (gimp-file-load-layer RUN-NONINTERACTIVE img "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch7-gray-scar/s018-gray-scar-ferry-approach/crossbow-string-donor.png"))) (mask 0))
(gimp-image-insert-layer img ly 0 0)
(gimp-item-set-name ly "Rear escort one independent crossbow")
(gimp-layer-scale ly 497 415 TRUE)
(gimp-layer-set-offsets ly 891 409)
(set! mask (car (gimp-layer-create-mask ly ADD-BLACK-MASK)))
(gimp-layer-add-mask ly mask)
(gimp-image-select-polygon img CHANNEL-OP-REPLACE 22 (vector 1144 584 1180 584 1208 597 1243 600 1261 610 1265 629 1254 647 1227 662 1200 650 1175 636 1146 616))
(gimp-selection-feather img 2)
(gimp-context-set-foreground "white")
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none img)
)
(let* ((ly (car (gimp-file-load-layer RUN-NONINTERACTIVE img "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch7-gray-scar/s018-gray-scar-ferry-approach/crossbow-string-donor.png"))) (mask 0))
(gimp-image-insert-layer img ly 0 0)
(gimp-item-set-name ly "Rear escort two independent crossbow")
(gimp-layer-scale ly 497 415 TRUE)
(gimp-layer-set-offsets ly 891 409)
(set! mask (car (gimp-layer-create-mask ly ADD-BLACK-MASK)))
(gimp-layer-add-mask ly mask)
(gimp-image-select-polygon img CHANNEL-OP-REPLACE 24 (vector 1236 618 1260 617 1285 626 1325 633 1360 646 1365 669 1341 685 1323 693 1304 679 1280 674 1254 661 1240 642))
(gimp-selection-feather img 2)
(gimp-context-set-foreground "white")
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none img)
)
(gimp-xcf-save RUN-NONINTERACTIVE img (car (gimp-image-get-active-layer img)) "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch7-gray-scar/s018-gray-scar-ferry-approach/master.xcf" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch7-gray-scar/s018-gray-scar-ferry-approach/master.xcf")
(let* ((dup (car (gimp-image-duplicate img))) (flat (car (gimp-image-merge-visible-layers dup CLIP-TO-IMAGE))))
(file-png-save RUN-NONINTERACTIVE dup flat "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch7-gray-scar/s018-gray-scar-ferry-approach/candidate.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch7-gray-scar/s018-gray-scar-ferry-approach/candidate.png" 0 9 0 0 0 0 0)
(gimp-image-delete dup))
(gimp-image-delete img))
(let* ((re (car (gimp-file-load RUN-NONINTERACTIVE "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch7-gray-scar/s018-gray-scar-ferry-approach/master.xcf" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch7-gray-scar/s018-gray-scar-ferry-approach/master.xcf"))) (flat (car (gimp-image-merge-visible-layers re CLIP-TO-IMAGE))))
(file-png-save RUN-NONINTERACTIVE re flat "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch7-gray-scar/s018-gray-scar-ferry-approach/reopened.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch7-gray-scar/s018-gray-scar-ferry-approach/reopened.png" 0 9 0 0 0 0 0)
(gimp-image-delete re))
(gimp-context-pop)
(gimp-quit 0)
