(gimp-context-push)
(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch7-gray-scar/s018-gray-scar-ferry-approach/crossbow-structure-donor.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch7-gray-scar/s018-gray-scar-ferry-approach/crossbow-structure-donor.png"))) (base (car (gimp-image-get-active-layer im))))
(gimp-item-set-name base "Generated two-limb crossbows")
(let* ((ly (car (gimp-layer-copy base TRUE))) (mask 0))
(gimp-image-insert-layer im ly 0 0)
(gimp-item-set-name ly "Foreground wrong butt string: coat pixels sampled 20px above")
(gimp-layer-set-offsets ly 0 20)
(set! mask (car (gimp-layer-create-mask ly ADD-BLACK-MASK)))
(gimp-layer-add-mask ly mask)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 8 (vector 359 285 668 318 670 336 360 304))
(gimp-selection-feather im 1)
(gimp-context-set-foreground "white")
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none im)
)
(let* ((ly (car (gimp-layer-copy base TRUE))) (mask 0))
(gimp-image-insert-layer im ly 0 0)
(gimp-item-set-name ly "Rear left wrong butt string: coat pixels sampled 20px above")
(gimp-layer-set-offsets ly 0 20)
(set! mask (car (gimp-layer-create-mask ly ADD-BLACK-MASK)))
(gimp-layer-add-mask ly mask)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 8 (vector 747 522 915 555 915 575 747 544))
(gimp-selection-feather im 1)
(gimp-context-set-foreground "white")
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none im)
)
(let* ((ly (car (gimp-layer-copy base TRUE))) (mask 0))
(gimp-image-insert-layer im ly 0 0)
(gimp-item-set-name ly "Rear right wrong butt string: coat pixels sampled 20px above")
(gimp-layer-set-offsets ly 0 20)
(set! mask (car (gimp-layer-create-mask ly ADD-BLACK-MASK)))
(gimp-layer-add-mask ly mask)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 8 (vector 1010 593 1184 638 1187 662 1013 618))
(gimp-selection-feather im 1)
(gimp-context-set-foreground "white")
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none im)
)
(let* ((ly (car (gimp-layer-new im 1373 1145 RGBA-IMAGE "Continuous strings from limb tips to central cocking notches" 100 NORMAL-MODE))))
(gimp-image-insert-layer im ly 0 0)
(gimp-context-set-brush "2. Hardness 075")
(gimp-context-set-brush-size 1.7)
(gimp-context-set-foreground (list 177 166 146))
(gimp-paintbrush-default ly 4 (vector 666 326 490 363))
(gimp-paintbrush-default ly 4 (vector 911 564 840 589))
(gimp-paintbrush-default ly 4 (vector 1181 650 1106 678))
)
(gimp-xcf-save RUN-NONINTERACTIVE im (car (gimp-image-get-active-layer im)) "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch7-gray-scar/s018-gray-scar-ferry-approach/crossbow-string-master.xcf" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch7-gray-scar/s018-gray-scar-ferry-approach/crossbow-string-master.xcf")
(let* ((fl (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE))))
(file-png-save RUN-NONINTERACTIVE im fl "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch7-gray-scar/s018-gray-scar-ferry-approach/crossbow-string-donor.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch7-gray-scar/s018-gray-scar-ferry-approach/crossbow-string-donor.png" 0 9 0 0 0 0 0))
(gimp-image-delete im))
(gimp-context-pop)
(gimp-quit 0)
