(gimp-context-push)
(let* ((img (car (gimp-file-load RUN-NONINTERACTIVE "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s050-citadel-lower-stair/source.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s050-citadel-lower-stair/source.png"))))
(gimp-item-set-name (car (gimp-image-get-active-layer img)) "Current source, Claude repairs preserved")
(let* ((ly (car (gimp-file-load-layer RUN-NONINTERACTIVE img "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s050-citadel-lower-stair/stone-donor.png"))) (mask 0))
(gimp-image-insert-layer img ly 0 0)
(gimp-item-set-name ly "Pier base and step end: remove old diamond surface")
(gimp-layer-scale ly 440 305 TRUE)
(gimp-layer-set-offsets ly 1170 625)
(set! mask (car (gimp-layer-create-mask ly ADD-BLACK-MASK)))
(gimp-layer-add-mask ly mask)
(gimp-image-select-polygon img CHANNEL-OP-REPLACE 16 (vector 1242 628 1349 627 1349 734 1317 739 1315 794 1341 798 1341 858 1243 860))
(gimp-selection-feather img 1.8)
(gimp-context-set-foreground "white")
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none img)
)
(gimp-xcf-save RUN-NONINTERACTIVE img (car (gimp-image-get-active-layer img)) "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s050-citadel-lower-stair/master.xcf" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s050-citadel-lower-stair/master.xcf")
(let* ((dup (car (gimp-image-duplicate img))))
(gimp-image-merge-visible-layers dup CLIP-TO-IMAGE)
(file-png-save RUN-NONINTERACTIVE dup (car (gimp-image-get-active-layer dup)) "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s050-citadel-lower-stair/candidate.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s050-citadel-lower-stair/candidate.png" 0 9 0 0 0 0 0)
(gimp-image-crop dup 440 305 1170 625)
(file-png-save RUN-NONINTERACTIVE dup (car (gimp-image-get-active-layer dup)) "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s050-citadel-lower-stair/after-native.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s050-citadel-lower-stair/after-native.png" 0 9 0 0 0 0 0)
(gimp-image-delete dup))
(gimp-image-delete img))
(let* ((re (car (gimp-file-load RUN-NONINTERACTIVE "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s050-citadel-lower-stair/master.xcf" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s050-citadel-lower-stair/master.xcf"))))
(gimp-image-merge-visible-layers re CLIP-TO-IMAGE)
(file-png-save RUN-NONINTERACTIVE re (car (gimp-image-get-active-layer re)) "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s050-citadel-lower-stair/reopened.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s050-citadel-lower-stair/reopened.png" 0 9 0 0 0 0 0)
(gimp-image-delete re))
(gimp-context-pop)
(gimp-quit 0)
