(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-bellweir/s012-temple-reading-room/before.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-bellweir/s012-temple-reading-room/before.png"))) (l 0) (mask 0) (out 0))
(gimp-item-set-name (car (gimp-image-get-active-layer im)) "Current neutral original — unchanged")
(set! l (car (gimp-file-load-layer RUN-NONINTERACTIVE im "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-bellweir/components/s012-banner-blank-donor.png")))
(gimp-image-insert-layer im l 0 0)
(gimp-layer-scale l 180 320 TRUE)
(gimp-layer-set-offsets l 1120 0)
(gimp-item-set-name l "Remove erroneous chalice from banner cloth")
(set! mask (car (gimp-layer-create-mask l ADD-BLACK-MASK)))
(gimp-layer-add-mask l mask)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 8 #(1171 11 1236 11 1239 172 1172 174))
(gimp-selection-feather im 2)
(gimp-context-set-foreground '(255 255 255))
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none im)
(set! l (car (gimp-file-load-layer RUN-NONINTERACTIVE im "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-bellweir/components/human-temple-sun-template.png")))
(gimp-image-insert-layer im l 0 0)
(gimp-layer-scale l 95 95 TRUE)
(gimp-layer-set-offsets l 1157 8)
(gimp-item-set-name l "Brass sun disk and exactly twelve short rays fixed geometry")
(set! mask (car (gimp-layer-create-mask l ADD-BLACK-MASK)))
(gimp-layer-add-mask l mask)
(gimp-layer-set-opacity l 55)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 8 #(1157 8 1252 8 1252 103 1157 103))
(gimp-selection-feather im 0)
(gimp-context-set-foreground '(255 255 255))
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none im)
(gimp-xcf-save RUN-NONINTERACTIVE im l "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-bellweir/s012-temple-reading-room/repair-master.xcf" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-bellweir/s012-temple-reading-room/repair-master.xcf")
(set! out (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save2 RUN-NONINTERACTIVE im out "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-bellweir/s012-temple-reading-room/candidate.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-bellweir/s012-temple-reading-room/candidate.png" 0 9 0 0 0 0 0 0 0)
(gimp-image-delete im))
(gimp-quit 0)
