(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-bellweir/s022-river-picket/before.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-bellweir/s022-river-picket/before.png"))) (l 0) (mask 0) (out 0))
(gimp-item-set-name (car (gimp-image-get-active-layer im)) "Current neutral original — unchanged")
(set! l (car (gimp-file-load-layer RUN-NONINTERACTIVE im "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-bellweir/components/s022-blank-drawing-donor.png")))
(gimp-image-insert-layer im l 0 0)
(gimp-layer-scale l 190 210 TRUE)
(gimp-layer-set-offsets l 880 340)
(gimp-item-set-name l "Remove inconsistent portrait within held sheet only")
(set! mask (car (gimp-layer-create-mask l ADD-BLACK-MASK)))
(gimp-layer-add-mask l mask)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 18 #(945 409 968 403 985 413 991 429 1002 442 977 452 955 451 952 435 944 422))
(gimp-selection-feather im 2)
(gimp-context-set-foreground '(255 255 255))
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none im)
(set! l (car (gimp-file-load-layer RUN-NONINTERACTIVE im "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-bellweir/components/orren-search-drawing.png")))
(gimp-image-insert-layer im l 0 0)
(gimp-layer-scale l 1254 1254 TRUE)
(gimp-layer-set-offsets l 0 0)
(gimp-item-set-name l "Exact shared Orren search drawing handed over")
(gimp-context-set-transform-resize TRANSFORM-RESIZE-ADJUST)
(set! l (car (gimp-item-transform-perspective l 930 411 978 395 956 455 1012 439)))
(gimp-layer-set-mode l MULTIPLY-MODE)
(gimp-layer-set-opacity l 83)
(set! mask (car (gimp-layer-create-mask l ADD-BLACK-MASK)))
(gimp-layer-add-mask l mask)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 8 #(930 411 978 395 1012 439 956 455))
(gimp-selection-feather im 0)
(gimp-context-set-foreground '(255 255 255))
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none im)
(gimp-xcf-save RUN-NONINTERACTIVE im l "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-bellweir/s022-river-picket/repair-master.xcf" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-bellweir/s022-river-picket/repair-master.xcf")
(set! out (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save2 RUN-NONINTERACTIVE im out "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-bellweir/s022-river-picket/candidate.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-bellweir/s022-river-picket/candidate.png" 0 9 0 0 0 0 0 0 0)
(gimp-image-delete im))
(gimp-quit 0)
