(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-bellweir/s024-northern-wharf/before.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-bellweir/s024-northern-wharf/before.png"))) (l 0) (mask 0) (out 0))
(gimp-item-set-name (car (gimp-image-get-active-layer im)) "Current neutral original — unchanged")
(set! l (car (gimp-file-load-layer RUN-NONINTERACTIVE im "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-bellweir/components/s024-blank-drawing-donor.png")))
(gimp-image-insert-layer im l 0 0)
(gimp-layer-scale l 400 240 TRUE)
(gimp-layer-set-offsets l 870 545)
(gimp-item-set-name l "Remove inconsistent portrait inside sheet on chart")
(set! mask (car (gimp-layer-create-mask l ADD-BLACK-MASK)))
(gimp-layer-add-mask l mask)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 18 #(996 608 1035 602 1061 615 1083 642 1088 657 1047 667 1020 658 1000 641 987 630))
(gimp-selection-feather im 2.5)
(gimp-context-set-foreground '(255 255 255))
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none im)
(set! l (car (gimp-file-load-layer RUN-NONINTERACTIVE im "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-bellweir/components/orren-search-drawing.png")))
(gimp-image-insert-layer im l 0 0)
(gimp-layer-scale l 1254 1254 TRUE)
(gimp-layer-set-offsets l 0 0)
(gimp-item-set-name l "Exact same Orren drawing laid on river chart")
(gimp-context-set-transform-resize TRANSFORM-RESIZE-ADJUST)
(set! l (car (gimp-item-transform-perspective l 946 621 1046 597 1026 670 1138 641)))
(gimp-layer-set-mode l MULTIPLY-MODE)
(gimp-layer-set-opacity l 83)
(set! mask (car (gimp-layer-create-mask l ADD-BLACK-MASK)))
(gimp-layer-add-mask l mask)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 8 #(946 621 1046 597 1138 641 1026 670))
(gimp-selection-feather im 0)
(gimp-context-set-foreground '(255 255 255))
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none im)
(gimp-xcf-save RUN-NONINTERACTIVE im l "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-bellweir/s024-northern-wharf/repair-master.xcf" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-bellweir/s024-northern-wharf/repair-master.xcf")
(set! out (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save2 RUN-NONINTERACTIVE im out "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-bellweir/s024-northern-wharf/candidate.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-bellweir/s024-northern-wharf/candidate.png" 0 9 0 0 0 0 0 0 0)
(gimp-image-delete im))
(gimp-quit 0)
