#!/usr/bin/env python3
"""Capture the portrait-treatment samples beside the current screen.

Copies the prototype screen and its art into the game only for the run,
captures S004 (bright), S002 and S023 (night) and S008 (day) with each
treatment on the old gradient and on the lacquer-toned gradient, removes the
files again and writes comparison sheets to renpy/test-output/review/:

  frames-samples.png   current, vignette, oval and rect, on the old gradient
  frames-shade.png     the vignette on the old and the lacquer-toned gradient
  frames-detail.png    the lower part of the screen at full size

    python3 visual-novel/prototypes/portrait-frames/sample.py
"""
from pathlib import Path
import shutil
import subprocess

from PIL import Image, ImageDraw, ImageFont

HERE = Path(__file__).resolve().parent
VN = HERE.parents[1]
GAME = VN / 'renpy/game'
SHOTS = VN / 'renpy/test-output/frames'
OUT = VN / 'renpy/test-output/review'
LINES = [('s002', 2, 75), ('s004', 4, 211), ('s008', 8, 352), ('s023', 23, 1012)]
VARIANTS = [(f, 'plain') for f in ('oval-bare', 'oval', 'oval-halo')]


def capture_test():
    steps = ['# Generated by prototypes/portrait-frames/sample.py; removed after the run.',
             'testcase frames_samples:',
             '    $ _test.timeout = 240.0',
             '    $ _preferences.text_cps = 0',
             "    $ _test.screenshot_directory = 'test-output/frames'",
             "    run Preference('display', 'fullscreen')",
             '    pause 1.0',
             "    click id 'main_begin'"]
    for name, scene, line in LINES:
        if scene != 2:
            steps += ["    run Jump('s%03d')" % scene, '    pause 0.5']
        steps += ['    advance until eval (current_scene, source_line) == (%d, %d)' % (scene, line), '    pause 0.8']
        for frame, shade in VARIANTS:
            steps += ["    $ frame_style, shade_style = %r, %r" % (frame, shade),
                      '    $ renpy.restart_interaction()', '    pause 0.6',
                      "    screenshot '%s-%s-%s.png'" % (frame, shade, name)]
    return '\n'.join(steps) + '\n'


def main():
    subprocess.run(['python3', str(HERE / 'build-frames.py')], check=True)
    placed = [GAME / 'zz-frames-prototype.rpy', GAME / 'zz-frames-capture.rpy']
    shutil.copy(HERE / 'zz-frames-prototype.rpy', placed[0])
    placed[1].write_text(capture_test())
    shutil.copytree(HERE / 'ui', GAME / 'frames', dirs_exist_ok=True)
    try:
        subprocess.run([str(VN / 'tools/run-tests.sh'), 'frames_samples'], check=True, stdout=subprocess.DEVNULL)
    finally:
        for path in placed:
            path.unlink(missing_ok=True)
            path.with_suffix('.rpyc').unlink(missing_ok=True)
        shutil.rmtree(GAME / 'frames', ignore_errors=True)
    sheets()


def shot(name):
    if name.startswith('current-'):
        return Image.open(VN / 'renpy/test-output/panel' / (name + '.png')).convert('RGB')
    return Image.open(SHOTS / (name + '.png')).convert('RGB')


def sheet(rows, cols, out, W=960, H=540):
    font = ImageFont.truetype('/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf', 26)
    img = Image.new('RGB', (len(cols) * (W + 10) + 10, len(rows) * (H + 46) + 10), (16, 16, 16))
    draw = ImageDraw.Draw(img)
    for r, (scene, label) in enumerate(rows):
        for c, (prefix, name) in enumerate(cols):
            x, y = 10 + c * (W + 10), 10 + r * (H + 46)
            img.paste(shot(prefix + scene).resize((W, H), Image.LANCZOS), (x, y + 38))
            draw.text((x, y + 4), '%s: %s' % (label, name), fill=(235, 235, 235), font=font)
    OUT.mkdir(parents=True, exist_ok=True)
    img.save(OUT / out)
    print('wrote', (OUT / out).relative_to(VN))


def sheets():
    rows = [('s004', 'S004 (bright)'), ('s002', 'S002 (night)'), ('s008', 'S008 (day)'), ('s023', 'S023 (night)')]
    sheet(rows, [('current-', 'Current'), ('oval-bare-plain-', 'Oval, no outline'), ('oval-plain-', 'Oval, gilt line'),
                 ('oval-halo-plain-', 'Oval, golden halo')], 'ovals-samples.png')
    font = ImageFont.truetype('/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf', 24)
    crops = [(v + scene, '%s, %s' % (label, scene.upper()))
             for scene in ('s004', 's008', 's023') for v, label in
             (('oval-bare-plain-', 'No outline'), ('oval-plain-', 'Gilt line'), ('oval-halo-plain-', 'Golden halo'))]
    img = Image.new('RGB', (3 * 650 + 20, 3 * 410), (16, 16, 16))
    draw = ImageDraw.Draw(img)
    for i, (name, label) in enumerate(crops):
        x, y = (i % 3) * 660, (i // 3) * 410
        img.paste(shot(name).crop((60, 700, 710, 1060)), (x, y + 40))
        draw.text((x + 6, y + 8), label + ', full size', fill=(235, 235, 235), font=font)
    img.save(OUT / 'ovals-detail.png')
    print('wrote', (OUT / 'ovals-detail.png').relative_to(VN))

if __name__ == '__main__':
    main()
