(define d "visual-novel/art/scene-studies/batch7-cats-minor/stair-healer/")
(define (layout role)
(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE (string-append d role "-generated.png") "generated"))) (ly (car (gimp-image-get-active-layer im))) (mask 0))
(gimp-image-resize im 1394 1394 70 140)
(gimp-layer-resize-to-image-size ly)
(set! mask (car (gimp-layer-create-mask ly ADD-ALPHA-TRANSFER-MASK)))
(gimp-layer-add-mask ly mask)
(gimp-levels mask HISTOGRAM-VALUE 0 250 1.0 0 255)
(gimp-item-set-name ly (string-append "Independent " role " portrait — native pixels, +70 x +140 y composition"))
(gimp-xcf-save RUN-NONINTERACTIVE im ly (string-append d role "-composition.xcf") "composition")
(set! ly (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save RUN-NONINTERACTIVE im ly (string-append d role "-candidate.png") "candidate" 0 9 0 0 0 0 0)
(gimp-image-delete im)))
(layout "speaking")
(layout "listening")
(gimp-quit 0)
