(define d "visual-novel/art/scene-studies/batch7-cats-minor/stair-healer/")
(define (reopen role)
(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE (string-append d role "-composition.xcf") "composition"))) (ly (car (gimp-image-get-active-layer im))))
(set! ly (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save RUN-NONINTERACTIVE im ly (string-append d role "-reopened.png") "reopened" 0 9 0 0 0 0 0)
(gimp-image-delete im)))
(reopen "speaking")
(reopen "listening")
(gimp-quit 0)
