(define d "visual-novel/art/scene-studies/batch7-cats-minor/")
(define (check name)
 (let* ((dir (string-append d name "/")) (im (car (gimp-file-load RUN-NONINTERACTIVE (string-append dir "repair-master.xcf") "master"))))
 (gimp-message (string-append name " layers: " (number->string (car (gimp-image-get-layers im)))))
 (let* ((ly (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE))))
 (file-png-save RUN-NONINTERACTIVE im ly (string-append dir "reopened.png") "reopen" 0 9 0 0 0 0 0))
 (gimp-image-delete im)))
(check "s018-cats") (check "s011-bellweir-causeway") (check "s034-return-cargo-shed")
(gimp-quit 0)
