(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/s035-harrow-bridge-crossing/local-finish-master.xcf" "visual-novel/art/scene-studies/s035-harrow-bridge-crossing/local-finish-master.xcf")))
 (flat (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE))))
 (file-png-save RUN-NONINTERACTIVE im flat "/tmp/s035-master-reopened-native.png" "/tmp/s035-master-reopened-native.png" 0 9 0 0 0 0 0)
 (gimp-image-crop im 1664 936 4 2)
 (gimp-context-set-interpolation INTERPOLATION-NOHALO)
 (gimp-image-scale im 1920 1080)
 (set! flat (car (gimp-image-get-active-layer im)))
 (file-png-save RUN-NONINTERACTIVE im flat "visual-novel/renpy/game/art/scenes/s035-harrow-bridge-crossing.png" "visual-novel/renpy/game/art/scenes/s035-harrow-bridge-crossing.png" 0 9 0 0 0 0 0)
 (gimp-image-delete im))
(gimp-quit 0)
