(gimp-context-push)
(gimp-context-set-interpolation INTERPOLATION-CUBIC)
(let* ((img (car (gimp-file-load RUN-NONINTERACTIVE "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/s054-duel/batch7/13-empty-hall-near-pillar.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/s054-duel/batch7/13-empty-hall-near-pillar.png"))))
(gimp-item-set-name (car (gimp-image-get-active-layer img)) "Empty throne hall with corrected near pillar — protected plate")
(let* ((ly (car (gimp-file-load-layer RUN-NONINTERACTIVE img "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/s054-duel/batch7/tessa-component.png"))) (mask 0))
(gimp-image-insert-layer img ly 0 0)
(gimp-item-set-name ly "Tessa soft floor shadow")
(gimp-layer-add-alpha ly)
(gimp-layer-set-lock-alpha ly TRUE)
(gimp-context-set-foreground "#101319")
(gimp-edit-fill ly FOREGROUND-FILL)
(gimp-layer-set-lock-alpha ly FALSE)
(gimp-item-transform-matrix ly 0.9703 -0.55 489.665 -0.06048 -0.12 997.136 0 0 1)
(gimp-layer-resize-to-image-size ly)
(gimp-layer-set-mode ly MULTIPLY-MODE)
(gimp-layer-set-opacity ly 18)
(plug-in-gauss-iir RUN-NONINTERACTIVE img ly 9 TRUE TRUE)
)
(let* ((ly (car (gimp-file-load-layer RUN-NONINTERACTIVE img "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch7-cats-minor/duel-valcair-component/valcair-component.png"))) (mask 0))
(gimp-image-insert-layer img ly 0 0)
(gimp-item-set-name ly "Valcair soft floor shadow")
(gimp-layer-add-alpha ly)
(gimp-layer-set-lock-alpha ly TRUE)
(gimp-context-set-foreground "#101319")
(gimp-edit-fill ly FOREGROUND-FILL)
(gimp-layer-set-lock-alpha ly FALSE)
(gimp-item-transform-matrix ly 1.02888 -0.4 307.344 0.08303 -0.15 883.614 0 0 1)
(gimp-layer-resize-to-image-size ly)
(gimp-layer-set-mode ly MULTIPLY-MODE)
(gimp-layer-set-opacity ly 18)
(plug-in-gauss-iir RUN-NONINTERACTIVE img ly 9 TRUE TRUE)
)
(let* ((ly (car (gimp-file-load-layer RUN-NONINTERACTIVE img "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/s054-duel/batch7/independent/contact-shadows.svg"))) (mask 0))
(gimp-image-insert-layer img ly 0 0)
(gimp-item-set-name ly "Four boot contact shadows")
(gimp-layer-add-alpha ly)
(gimp-layer-set-mode ly MULTIPLY-MODE)
(gimp-layer-set-opacity ly 62)
(plug-in-gauss-iir RUN-NONINTERACTIVE img ly 3 TRUE TRUE)
)
(let* ((ly (car (gimp-file-load-layer RUN-NONINTERACTIVE img "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/s054-duel/batch7/09-spearman-foundation.png"))) (mask 0))
(gimp-image-insert-layer img ly 0 0)
(gimp-item-set-name ly "Far heavy horn \u2014 rigid scaled original component behind crown")
(gimp-layer-add-alpha ly)
(set! mask (car (gimp-layer-create-mask ly ADD-BLACK-MASK)))
(gimp-layer-add-mask ly mask)
(gimp-image-select-polygon img CHANNEL-OP-REPLACE 40 (vector 1111 139 1123 118 1148 102 1179 91 1208 91 1239 103 1260 125 1274 135 1287 135 1297 127 1294 139 1284 147 1269 150 1250 145 1225 129 1204 119 1181 118 1159 130 1140 147 1124 152))
(gimp-selection-feather img 0.6)
(gimp-context-set-foreground "white")
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none img)
(gimp-layer-remove-mask ly MASK-APPLY)
(gimp-item-transform-matrix ly 0.6 0 518 0 0.6 17 0 0 1)
(gimp-layer-resize-to-image-size ly)
)
(let* ((ly (car (gimp-file-load-layer RUN-NONINTERACTIVE img "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/s054-duel/batch7/independent/pillar-impact-detail.svg"))) (mask 0))
(gimp-image-insert-layer img ly 0 0)
(gimp-item-set-name ly "Bounded pillar crack and stone chips")
(gimp-layer-add-alpha ly)
)
(let* ((ly (car (gimp-file-load-layer RUN-NONINTERACTIVE img "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/s054-duel/batch7/09-spearman-foundation.png"))) (mask 0))
(gimp-image-insert-layer img ly 0 0)
(gimp-item-set-name ly "Short real wooden shaft ahead of source grip")
(gimp-layer-add-alpha ly)
(set! mask (car (gimp-layer-create-mask ly ADD-BLACK-MASK)))
(gimp-layer-add-mask ly mask)
(gimp-image-select-polygon img CHANNEL-OP-REPLACE 8 (vector 399 243 467 253 467 265 398 255))
(gimp-selection-feather img 0.6)
(gimp-context-set-foreground "white")
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none img)
(gimp-layer-remove-mask ly MASK-APPLY)
(gimp-layer-set-offsets ly 275 39)
)
(let* ((ly (car (gimp-file-load-layer RUN-NONINTERACTIVE img "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/s054-duel/batch7/09-spearman-foundation.png"))) (mask 0))
(gimp-image-insert-layer img ly 0 0)
(gimp-item-set-name ly "Real spearhead \u2014 shorter foregrip reach")
(gimp-layer-add-alpha ly)
(set! mask (car (gimp-layer-create-mask ly ADD-BLACK-MASK)))
(gimp-layer-add-mask ly mask)
(gimp-image-select-polygon img CHANNEL-OP-REPLACE 14 (vector 162 218 274 211 300 225 314 233 314 242 286 248 173 229))
(gimp-selection-feather img 0.6)
(gimp-context-set-foreground "white")
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none img)
(gimp-layer-remove-mask ly MASK-APPLY)
(gimp-item-transform-matrix ly 0.45144 -0.015607 538.85 0.015607 0.45144 177.14 0 0 1)
(gimp-layer-resize-to-image-size ly)
)
(let* ((ly (car (gimp-file-load-layer RUN-NONINTERACTIVE img "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch7-cats-minor/duel-valcair-component/valcair-component.png"))) (mask 0))
(gimp-image-insert-layer img ly 0 0)
(gimp-item-set-name ly "Exact Valcair source anatomy and remaining rigid shaft")
(gimp-layer-add-alpha ly)
)
(let* ((ly (car (gimp-file-load-layer RUN-NONINTERACTIVE img "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/s054-duel/batch7/tessa-component.png"))) (mask 0))
(gimp-image-insert-layer img ly 0 0)
(gimp-item-set-name ly "Exact Tessa body \u2014 only original glove patch removed for rigid wrist rotation")
(gimp-layer-add-alpha ly)
(set! mask (car (gimp-layer-create-mask ly ADD-WHITE-MASK)))
(gimp-layer-add-mask ly mask)
(gimp-image-select-polygon img CHANNEL-OP-REPLACE 12 (vector 590 394 706 367 714 474 588 474 588 442 587 400))
(gimp-selection-feather img 0.8)
(gimp-context-set-foreground "black")
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none img)
)
(let* ((ly (car (gimp-file-load-layer RUN-NONINTERACTIVE img "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/s054-duel/batch7/tessa-component.png"))) (mask 0))
(gimp-image-insert-layer img ly 0 0)
(gimp-item-set-name ly "Healthy right glove and entire hilt \u2014 rigid9.7deg wrist articulation")
(gimp-layer-add-alpha ly)
(set! mask (car (gimp-layer-create-mask ly ADD-BLACK-MASK)))
(gimp-layer-add-mask ly mask)
(gimp-image-select-polygon img CHANNEL-OP-REPLACE 28 (vector 589 396 624 393 629 374 645 373 666 389 685 383 701 413 693 451 664 456 634 461 612 467 594 463 591 444 586 441))
(gimp-selection-feather img 0.65)
(gimp-context-set-foreground "white")
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none img)
(gimp-layer-remove-mask ly MASK-APPLY)
(gimp-item-transform-matrix ly 0.9857034690888535 -0.16848937956500257 79.24338224761098 0.16848937956500257 0.9857034690888535 -93.909659099365 0 0 1)
(gimp-layer-resize-to-image-size ly)
)
(let* ((ly (car (gimp-file-load-layer RUN-NONINTERACTIVE img "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/renpy/game/art/scenes/s054-throne-hall.png"))) (mask 0))
(gimp-image-insert-layer img ly 0 0)
(gimp-item-set-name ly "Existing arming-sword steel \u2014 rigid transform, edge at elbow and tip beyond")
(gimp-layer-add-alpha ly)
(set! mask (car (gimp-layer-create-mask ly ADD-BLACK-MASK)))
(gimp-layer-add-mask ly mask)
(gimp-image-select-polygon img CHANNEL-OP-REPLACE 14 (vector 250 557 279 575 496 705 526 728 498 718 277 592 245 575))
(gimp-selection-feather img 0.45)
(gimp-context-set-foreground "white")
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none img)
(gimp-layer-remove-mask ly MASK-APPLY)
(gimp-item-transform-matrix ly 0.654117188826414 0.9445375465649313 -28.03485803313731 -0.9445375465649313 0.654117188826414 285.68489848095953 0 0 1)
(gimp-layer-resize-to-image-size ly)
)
(let* ((ly (car (gimp-file-load-layer RUN-NONINTERACTIVE img "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/s054-duel/batch7/independent/shelter-light-donor.png"))) (mask 0))
(gimp-image-insert-layer img ly 0 0)
(gimp-item-set-name ly "Organic white sanctuary light \u2014 additive surface")
(gimp-layer-add-alpha ly)
(gimp-layer-scale ly 1672 923 TRUE)
(gimp-layer-set-offsets ly 13 48)
(gimp-layer-set-mode ly SCREEN-MODE)
(gimp-layer-set-opacity ly 54)
)
(let* ((ly (car (gimp-file-load-layer RUN-NONINTERACTIVE img "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/s054-duel/batch7/independent/glance-ripple.svg"))) (mask 0))
(gimp-image-insert-layer img ly 0 0)
(gimp-item-set-name ly "Tiny sanctuary glancing ripple by spearhead")
(gimp-layer-add-alpha ly)
(gimp-layer-set-mode ly SCREEN-MODE)
(gimp-layer-set-opacity ly 72)
(plug-in-gauss-iir RUN-NONINTERACTIVE img ly 0.5 TRUE TRUE)
)
(let* ((ly (car (gimp-file-load-layer RUN-NONINTERACTIVE img "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/s054-duel/batch7/independent/black-ward-contact-donor.png"))) (mask 0))
(gimp-image-insert-layer img ly 0 0)
(gimp-item-set-name ly "Forward elbow blade rejection")
(gimp-layer-add-alpha ly)
(set! mask (car (gimp-layer-create-mask ly ADD-BLACK-MASK)))
(gimp-layer-add-mask ly mask)
(gimp-image-select-polygon img CHANNEL-OP-REPLACE 10 (vector 155 135 585 135 615 420 590 470 140 470))
(gimp-selection-feather img 25)
(gimp-context-set-foreground "white")
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none img)
(gimp-layer-remove-mask ly MASK-APPLY)
(gimp-levels ly HISTOGRAM-VALUE 0 255 0.4 0 255)
(gimp-item-transform-matrix ly 0.19 0 875.4 0 0.19 243.61 0 0 1)
(gimp-layer-resize-to-image-size ly)
(gimp-layer-set-mode ly MULTIPLY-MODE)
(gimp-layer-set-opacity ly 92)
)
(let* ((ly (car (gimp-file-load-layer RUN-NONINTERACTIVE img "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/s054-duel/batch7/independent/black-ward-contact-donor.png"))) (mask 0))
(gimp-image-insert-layer img ly 0 0)
(gimp-item-set-name ly "Rear elbow ward seam")
(gimp-layer-add-alpha ly)
(set! mask (car (gimp-layer-create-mask ly ADD-BLACK-MASK)))
(gimp-layer-add-mask ly mask)
(gimp-image-select-polygon img CHANNEL-OP-REPLACE 10 (vector 0 0 680 0 720 440 670 540 0 540))
(gimp-selection-feather img 25)
(gimp-context-set-foreground "white")
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none img)
(gimp-layer-remove-mask ly MASK-APPLY)
(gimp-levels ly HISTOGRAM-VALUE 0 255 0.62 0 255)
(gimp-item-transform-matrix ly 0.1 0 1286.0 0 0.1 324.9 0 0 1)
(gimp-layer-resize-to-image-size ly)
(gimp-layer-set-mode ly MULTIPLY-MODE)
(gimp-layer-set-opacity ly 34)
)
(let* ((ly (car (gimp-file-load-layer RUN-NONINTERACTIVE img "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/s054-duel/batch7/independent/black-ward-contact-donor.png"))) (mask 0))
(gimp-image-insert-layer img ly 0 0)
(gimp-item-set-name ly "Front knee ward seam")
(gimp-layer-add-alpha ly)
(set! mask (car (gimp-layer-create-mask ly ADD-BLACK-MASK)))
(gimp-layer-add-mask ly mask)
(gimp-image-select-polygon img CHANNEL-OP-REPLACE 10 (vector 0 0 680 0 720 440 670 540 0 540))
(gimp-selection-feather img 25)
(gimp-context-set-foreground "white")
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none img)
(gimp-layer-remove-mask ly MASK-APPLY)
(gimp-levels ly HISTOGRAM-VALUE 0 255 0.62 0 255)
(gimp-item-transform-matrix ly 0.09 0 1069.4 0 0.09 587.71 0 0 1)
(gimp-layer-resize-to-image-size ly)
(gimp-layer-set-mode ly MULTIPLY-MODE)
(gimp-layer-set-opacity ly 30)
)
(let* ((ly (car (gimp-file-load-layer RUN-NONINTERACTIVE img "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/s054-duel/batch7/independent/black-ward-contact-donor.png"))) (mask 0))
(gimp-image-insert-layer img ly 0 0)
(gimp-item-set-name ly "Rear knee ward seam")
(gimp-layer-add-alpha ly)
(set! mask (car (gimp-layer-create-mask ly ADD-BLACK-MASK)))
(gimp-layer-add-mask ly mask)
(gimp-image-select-polygon img CHANNEL-OP-REPLACE 10 (vector 0 0 680 0 720 440 670 540 0 540))
(gimp-selection-feather img 25)
(gimp-context-set-foreground "white")
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none img)
(gimp-layer-remove-mask ly MASK-APPLY)
(gimp-levels ly HISTOGRAM-VALUE 0 255 0.62 0 255)
(gimp-item-transform-matrix ly 0.08 0 1457.8 0 0.08 678.52 0 0 1)
(gimp-layer-resize-to-image-size ly)
(gimp-layer-set-mode ly MULTIPLY-MODE)
(gimp-layer-set-opacity ly 30)
)
(gimp-xcf-save RUN-NONINTERACTIVE img (car (gimp-image-get-active-layer img)) "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/s054-duel/batch7/independent/deterministic-master.xcf" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/s054-duel/batch7/independent/deterministic-master.xcf")
(let* ((dup (car (gimp-image-duplicate img))) (flat (car (gimp-image-merge-visible-layers dup CLIP-TO-IMAGE))))
(file-png-save RUN-NONINTERACTIVE dup flat "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/s054-duel/batch7/independent/deterministic-native.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/s054-duel/batch7/independent/deterministic-native.png" 0 9 0 0 0 0 0)
(gimp-image-delete dup))
(gimp-image-delete img))
(let* ((re (car (gimp-file-load RUN-NONINTERACTIVE "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/s054-duel/batch7/independent/deterministic-master.xcf" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/s054-duel/batch7/independent/deterministic-master.xcf"))) (flat (car (gimp-image-merge-visible-layers re CLIP-TO-IMAGE))))
(file-png-save RUN-NONINTERACTIVE re flat "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/s054-duel/batch7/independent/deterministic-reopened.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/s054-duel/batch7/independent/deterministic-reopened.png" 0 9 0 0 0 0 0)
(gimp-image-delete re))
(gimp-context-pop)
(gimp-quit 0)
