(gimp-context-push)
(gimp-context-set-interpolation INTERPOLATION-CUBIC)
(gimp-context-set-transform-resize TRANSFORM-RESIZE-ADJUST)
(let* ((img (car (gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/s054-duel/batch7/independent/deterministic-master.xcf" "visual-novel/art/scene-studies/s054-duel/batch7/independent/deterministic-master.xcf")))
       (old (gimp-image-get-layers img))
       (n (car old))
       (layers (cadr old))
       (group (car (gimp-layer-group-new img)))
       (i 0))
 (gimp-image-insert-layer img group 0 0)
 (gimp-item-set-name group "Reviewed native composition — uniform factor 1920/1672")
 (while (< i n)
  (gimp-image-reorder-item img (aref layers i) group i)
  (set! i (+ i 1)))
 (gimp-item-transform-matrix group (/ 1920.0 1672.0) 0 0 0 (/ 1920.0 1672.0) 0 0 0 1)
 (gimp-image-resize img 1920 1080 0 0)
 ; Cubic transform adds fractional alpha on the rectangular plate boundary.
 ; Preserve its sampled RGB and restore full plate coverage through alpha transfer.
 (let* ((base (aref layers (- n 1))) (mask (car (gimp-layer-create-mask base ADD-ALPHA-TRANSFER-MASK))))
  (gimp-layer-add-mask base mask)
  (gimp-context-set-foreground "white")
  (gimp-edit-fill mask FOREGROUND-FILL)
  (gimp-layer-remove-mask base MASK-APPLY))
 (gimp-xcf-save RUN-NONINTERACTIVE img group "visual-novel/art/scene-studies/s054-duel/batch7/independent/delivery-master.xcf" "visual-novel/art/scene-studies/s054-duel/batch7/independent/delivery-master.xcf")
 (let* ((dup (car (gimp-image-duplicate img))) (flat (car (gimp-image-merge-visible-layers dup CLIP-TO-IMAGE))))
  (file-png-save RUN-NONINTERACTIVE dup flat "visual-novel/art/scene-studies/s054-duel/batch7/independent/delivery.png" "visual-novel/art/scene-studies/s054-duel/batch7/independent/delivery.png" 0 9 0 0 0 0 0)
  (gimp-image-delete dup))
 (gimp-image-delete img))
(let* ((img (car (gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/s054-duel/batch7/independent/delivery-master.xcf" "visual-novel/art/scene-studies/s054-duel/batch7/independent/delivery-master.xcf")))
       (flat (car (gimp-image-merge-visible-layers img CLIP-TO-IMAGE))))
 (file-png-save RUN-NONINTERACTIVE img flat "visual-novel/art/scene-studies/s054-duel/batch7/independent/delivery-reopened.png" "visual-novel/art/scene-studies/s054-duel/batch7/independent/delivery-reopened.png" 0 9 0 0 0 0 0)
 (gimp-image-delete img))
(gimp-context-pop)
(gimp-quit 0)
