(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/s057-citadel-lower-gate/gate-source.png" "gate-source.png"))) (base (car (gimp-image-get-active-layer im))) (clean 0) (bg 0) (mask 0) (flat 0))
(gimp-context-set-interpolation INTERPOLATION-NOHALO)
(gimp-item-set-name base "Original cast, horse, harness and wagon geometry preserved")
(set! clean (car (gimp-file-load-layer RUN-NONINTERACTIVE im "visual-novel/art/scene-studies/s057-citadel-lower-gate/symbol-donor.png")))
(gimp-image-insert-layer im clean 0 -1)
(gimp-item-set-name clean "Seven bounded cloth and wood symbol removals; no actor repaint")
(set! mask (car (gimp-layer-create-mask clean ADD-BLACK-MASK))) (gimp-layer-add-mask clean mask)
(for-each (lambda (r)
(gimp-image-select-rectangle im CHANNEL-OP-REPLACE (car r) (cadr r) (caddr r) (cadddr r))
(gimp-selection-feather im 3) (gimp-edit-fill mask WHITE-FILL) (gimp-selection-none im))
'((568 163 59 65) (778 218 53 48) (971 214 50 51) (784 306 46 72) (896 310 40 49) (875 393 28 32) (738 369 28 27)))
(gimp-image-resize im 1920 1080 124 20)
(set! bg (car (gimp-file-load-layer RUN-NONINTERACTIVE im "visual-novel/art/scene-studies/s057-citadel-lower-gate/peripheral-donor.png")))
(gimp-image-insert-layer im bg 0 -1) (gimp-image-lower-item-to-bottom im bg)
(gimp-item-set-name bg "Generated peripheral context only; original actors retained above")
(gimp-layer-scale bg 1920 1080 TRUE) (gimp-layer-set-offsets bg 0 0)
(set! mask (car (gimp-layer-create-mask base ADD-WHITE-MASK))) (gimp-layer-add-mask base mask)
(gimp-image-select-rectangle im CHANNEL-OP-REPLACE 128 24 1664 933)
(gimp-selection-feather im 7) (gimp-selection-invert im) (gimp-context-set-foreground '(0 0 0)) (gimp-edit-fill mask FOREGROUND-FILL) (gimp-selection-none im)
(set! clean (car (gimp-file-load-layer RUN-NONINTERACTIVE im "visual-novel/art/scene-studies/s057-citadel-lower-gate/seam-donor.png")))
(gimp-image-insert-layer im clean 0 -1) (gimp-layer-scale clean 1920 1080 TRUE) (gimp-layer-set-offsets clean 0 0)
(gimp-item-set-name clean "Two silhouette-aware outer boot and paving seam repairs")
(set! mask (car (gimp-layer-create-mask clean ADD-BLACK-MASK))) (gimp-layer-add-mask clean mask)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 16 #(95 740 166 737 191 805 205 924 170 959 91 949 82 846 95 740))
(gimp-selection-feather im 12) (gimp-edit-fill mask WHITE-FILL) (gimp-selection-none im)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 16 #(1727 730 1824 726 1847 822 1868 964 1795 993 1711 968 1713 842 1727 730))
(gimp-selection-feather im 12) (gimp-edit-fill mask WHITE-FILL) (gimp-selection-none im)
(gimp-xcf-save RUN-NONINTERACTIVE im base "visual-novel/art/scene-studies/s057-citadel-lower-gate/gate-master.xcf" "gate-master.xcf")
(set! flat (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save RUN-NONINTERACTIVE im flat "/tmp/s057-final-candidate.png" "/tmp/s057-final-candidate.png" 0 9 0 0 0 0 0)
(gimp-image-delete im)) (gimp-quit 0)
