(gimp-context-push)
(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s021-rescue/source.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s021-rescue/source.png"))))
(gimp-item-set-name (car (gimp-image-get-active-layer im)) "Current source with Claude repairs")
(let* ((ly (car (gimp-file-load-layer RUN-NONINTERACTIVE im "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s021-rescue/face-donor.png"))) (mask 0))
(gimp-image-insert-layer im ly 0 0)
(gimp-item-set-name ly "Iven lower face: clean-shaven, source eyes and hair protected")
(gimp-layer-scale ly 150 169 TRUE)
(gimp-layer-set-offsets ly 722 229)
(set! mask (car (gimp-layer-create-mask ly ADD-BLACK-MASK)))
(gimp-layer-add-mask ly mask)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 18 (vector 773 277 783 278 793 278 803 280 803 290 799 295 791 297 780 292 773 285))
(gimp-selection-feather im 0.7)
(gimp-context-set-foreground "white")
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none im)
)
(let* ((ly (car (gimp-file-load-layer RUN-NONINTERACTIVE im "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s021-rescue/bow-donor.png"))) (mask 0))
(gimp-image-insert-layer im ly 0 0)
(gimp-item-set-name ly "Spent lower bow assembly: continuous string and cleared old diagonals")
(gimp-layer-scale ly 180 245 TRUE)
(gimp-layer-set-offsets ly 320 410)
(set! mask (car (gimp-layer-create-mask ly ADD-BLACK-MASK)))
(gimp-layer-add-mask ly mask)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 10 (vector 339 535 415 535 463 572 463 612 340 614))
(gimp-selection-feather im 1.6)
(gimp-context-set-foreground "white")
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none im)
)
(gimp-xcf-save RUN-NONINTERACTIVE im (car (gimp-image-get-active-layer im)) "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s021-rescue/master.xcf" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s021-rescue/master.xcf")
(let* ((dup (car (gimp-image-duplicate im))))
(gimp-image-merge-visible-layers dup CLIP-TO-IMAGE)
(file-png-save RUN-NONINTERACTIVE dup (car (gimp-image-get-active-layer dup)) "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s021-rescue/candidate.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s021-rescue/candidate.png" 0 9 0 0 0 0 0)
(gimp-image-delete dup))
(let* ((dup (car (gimp-image-duplicate im))))
(gimp-image-merge-visible-layers dup CLIP-TO-IMAGE)
(gimp-image-crop dup 120 135 720 230)
(file-png-save RUN-NONINTERACTIVE dup (car (gimp-image-get-active-layer dup)) "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s021-rescue/face-after.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s021-rescue/face-after.png" 0 9 0 0 0 0 0)
(gimp-image-delete dup))
(let* ((dup (car (gimp-image-duplicate im))))
(gimp-image-merge-visible-layers dup CLIP-TO-IMAGE)
(gimp-image-crop dup 180 245 320 410)
(file-png-save RUN-NONINTERACTIVE dup (car (gimp-image-get-active-layer dup)) "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s021-rescue/bow-after.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s021-rescue/bow-after.png" 0 9 0 0 0 0 0)
(gimp-image-delete dup))
(gimp-image-delete im))
(let* ((re (car (gimp-file-load RUN-NONINTERACTIVE "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s021-rescue/master.xcf" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s021-rescue/master.xcf"))))
(gimp-image-merge-visible-layers re CLIP-TO-IMAGE)
(file-png-save RUN-NONINTERACTIVE re (car (gimp-image-get-active-layer re)) "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s021-rescue/reopened.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s021-rescue/reopened.png" 0 9 0 0 0 0 0)
(gimp-image-delete re))
(gimp-context-pop)
(gimp-quit 0)
