(let* ((dir "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/s053-bend") (im (car (gimp-file-load RUN-NONINTERACTIVE (string-append dir "/repair-master.xcf") (string-append dir "/repair-master.xcf")))) (ly (car (gimp-file-load-layer RUN-NONINTERACTIVE im (string-append dir "/window-flash-donor.png")))) (mask 0))
(gimp-image-insert-layer im ly 0 0) (gimp-layer-scale ly 305 230 TRUE) (gimp-layer-set-offsets ly 580 0) (gimp-item-set-name ly "White combat light flashes through high hall window")
(set! mask (car (gimp-layer-create-mask ly ADD-BLACK-MASK))) (gimp-layer-add-mask ly mask)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 8 #(741 0 811 0 817 124 733 124)) (gimp-selection-feather im 10) (gimp-context-set-foreground '(255 255 255)) (gimp-edit-fill mask FOREGROUND-FILL) (gimp-selection-none im)
(gimp-xcf-save RUN-NONINTERACTIVE im ly (string-append dir "/native-master.xcf") (string-append dir "/native-master.xcf"))
(gimp-image-scale im 1920 1080)
(gimp-xcf-save RUN-NONINTERACTIVE im ly (string-append dir "/delivery-master.xcf") (string-append dir "/delivery-master.xcf"))
(let ((out (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))) (file-png-save2 RUN-NONINTERACTIVE im out (string-append dir "/candidate.png") (string-append dir "/candidate.png") 0 9 0 0 0 0 0 0 0)) (gimp-image-delete im))
(let* ((dir "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/s053-bend") (im (car (gimp-file-load RUN-NONINTERACTIVE (string-append dir "/delivery-master.xcf") (string-append dir "/delivery-master.xcf")))) (out (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))) (file-png-save2 RUN-NONINTERACTIVE im out (string-append dir "/reopened.png") (string-append dir "/reopened.png") 0 9 0 0 0 0 0 0 0) (gimp-image-delete im))
(gimp-quit 0)
