(define (crop tag x y w h)
(let* ((p "visual-novel/art/scene-studies/batch8-stair/s055-morning-completion/candidate.png") (img (car (gimp-file-load RUN-NONINTERACTIVE p p))) (d (car (gimp-image-get-active-layer img))))
(gimp-image-crop img w h x y)
(file-jpeg-save RUN-NONINTERACTIVE img d (string-append "visual-novel/art/scene-studies/batch8-stair/s055-morning-completion/" tag "-native.jpg") tag 0.95 0 1 0 "" 0 1 0 1)
(gimp-image-delete img)))
(crop "grief" 200 245 885 500)
(crop "olan-lucan" 1035 70 470 495)
(crop "escorts" 1450 290 470 550)
(crop "floor-contact" 725 585 755 315)
(crop "junction-final" 1040 550 820 530)
(let* ((p "visual-novel/art/scene-studies/batch8-stair/s055-morning-completion/candidate.xcf") (img (car (gimp-file-load RUN-NONINTERACTIVE p p))))
(gimp-message (string-append "Reopened master layer count: " (number->string (car (gimp-image-get-layers img)))))
(gimp-image-delete img))
(gimp-quit 0)
