(define (star im name scale x y opacity)
(let* ((l (car (gimp-file-load-layer RUN-NONINTERACTIVE im "visual-novel/art/prop-keys/emblems/northern-split-star.png"))))
(gimp-image-insert-layer im l 0 -1) (gimp-item-set-name l name)
(gimp-layer-scale l scale scale TRUE) (gimp-layer-set-offsets l x y) (gimp-layer-set-opacity l opacity) l))
(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/s046-valcair-private-room/private-room-source.png" "private-room-source.png"))) (base (car (gimp-image-get-active-layer im))) (clean 0) (back 0) (mask 0) (l 0) (flat 0))
(gimp-context-set-interpolation INTERPOLATION-NOHALO)
(gimp-item-set-name base "Original confrontation: figures, left dressing, offered clothes")
(set! clean (car (gimp-layer-new im 1672 941 RGBA-IMAGE "Cloth-only cleanup under three canonical split stars" 100 NORMAL-MODE)))
(gimp-image-insert-layer im clean 0 -1)
(gimp-context-set-brush "2. Hardness 075") (gimp-context-set-brush-size 20)
(gimp-clone clean base CLONE-IMAGE 414 278 2 #(400 258))
(gimp-context-set-brush-size 29) (gimp-clone clean base CLONE-IMAGE 1026 439 2 #(1055 415))
(gimp-context-set-brush-size 46)
(for-each (lambda (xx) (for-each (lambda (yy) (gimp-clone clean base CLONE-IMAGE 1461 221 2 (vector xx yy))) '(84 116 148 180 201))) '(1492 1521 1550 1570))
(star im "Lucan small white split-star badge" 32 384 241 83)
(star im "Offered coat split-star badge" 38 1036 396 80)
(star im "Woven northern split star on private-room hanging" 172 1441 50 22)
; Add only small peripheral context margin, preserving central source pixels.
(set! back (car (gimp-layer-copy base TRUE))) (gimp-image-insert-layer im back 0 0)
(gimp-image-lower-item-to-bottom im back) (gimp-item-set-name back "Peripheral wall/floor context margin; figures preserved above")
(gimp-image-resize im 1696 954 12 13)
(gimp-layer-scale back 1696 954 TRUE) (gimp-layer-set-offsets back 0 0)
(set! mask (car (gimp-layer-create-mask base ADD-WHITE-MASK))) (gimp-layer-add-mask base mask)
; Small feather only at original source's outer edges.
(gimp-image-select-rectangle im CHANNEL-OP-REPLACE 17 18 1662 931)
(gimp-selection-feather im 6) (gimp-selection-invert im) (gimp-context-set-foreground '(0 0 0)) (gimp-edit-fill mask FOREGROUND-FILL) (gimp-selection-none im)
(gimp-image-scale im 1920 1080)
(gimp-xcf-save RUN-NONINTERACTIVE im base "visual-novel/art/scene-studies/s046-valcair-private-room/private-room-master.xcf" "private-room-master.xcf")
(set! flat (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save RUN-NONINTERACTIVE im flat "/tmp/s046-final-candidate.png" "/tmp/s046-final-candidate.png" 0 9 0 0 0 0 0)
(gimp-image-delete im)) (gimp-quit 0)
