(gimp-context-push)
(let* ((img (car (gimp-file-load RUN-NONINTERACTIVE "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s051-north-infirmary-court/source.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s051-north-infirmary-court/source.png"))))
(gimp-item-set-name (car (gimp-image-get-active-layer img)) "Current source, Claude repairs preserved")
(let* ((ly (car (gimp-file-load-layer RUN-NONINTERACTIVE img "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s051-north-infirmary-court/crossbow-hand-donor.png"))) (mask 0))
(gimp-image-insert-layer img ly 0 0)
(gimp-item-set-name ly "Level crossbow: edge-on bow, restored stone, and articulated hands")
(gimp-layer-scale ly 320 170 TRUE)
(gimp-layer-set-offsets ly 300 390)
(set! mask (car (gimp-layer-create-mask ly ADD-BLACK-MASK)))
(gimp-layer-add-mask ly mask)
(gimp-image-select-polygon img CHANNEL-OP-REPLACE 38 (vector 320 408 408 403 422 416 516 443 529 443 554 446 577 460 580 481 590 498 552 506 549 538 527 553 487 545 454 544 442 536 444 519 435 507 392 507 320 500))
(gimp-selection-feather img 1.5)
(gimp-context-set-foreground "white")
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none img)
)
(gimp-xcf-save RUN-NONINTERACTIVE img (car (gimp-image-get-active-layer img)) "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s051-north-infirmary-court/master.xcf" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s051-north-infirmary-court/master.xcf")
(let* ((dup (car (gimp-image-duplicate img))))
(gimp-image-merge-visible-layers dup CLIP-TO-IMAGE)
(file-png-save RUN-NONINTERACTIVE dup (car (gimp-image-get-active-layer dup)) "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s051-north-infirmary-court/candidate.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s051-north-infirmary-court/candidate.png" 0 9 0 0 0 0 0)
(gimp-image-crop dup 320 170 300 390)
(file-png-save RUN-NONINTERACTIVE dup (car (gimp-image-get-active-layer dup)) "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s051-north-infirmary-court/after-native.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s051-north-infirmary-court/after-native.png" 0 9 0 0 0 0 0)
(gimp-image-delete dup))
(gimp-image-delete img))
(let* ((re (car (gimp-file-load RUN-NONINTERACTIVE "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s051-north-infirmary-court/master.xcf" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s051-north-infirmary-court/master.xcf"))))
(gimp-image-merge-visible-layers re CLIP-TO-IMAGE)
(file-png-save RUN-NONINTERACTIVE re (car (gimp-image-get-active-layer re)) "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s051-north-infirmary-court/reopened.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s051-north-infirmary-court/reopened.png" 0 9 0 0 0 0 0)
(gimp-image-delete re))
(gimp-context-pop)
(gimp-quit 0)
