(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/renpy/game/art/base/opening/cg/rested-hand.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/renpy/game/art/base/opening/cg/rested-hand.png"))) (l 0) (mask 0) (out 0))
(gimp-item-set-name (car (gimp-image-get-active-layer im)) "Current neutral original — unchanged")
(set! l (car (gimp-file-load-layer RUN-NONINTERACTIVE im "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-opening/components/rested-hand-donor.png")))
(gimp-image-insert-layer im l 0 0)
(gimp-layer-scale l 220 230 TRUE)
(gimp-layer-set-offsets l 0 170)
(gimp-item-set-name l "Right hand \u2014 remove ring digit; original dressing retained")
(set! mask (car (gimp-layer-create-mask l ADD-BLACK-MASK)))
(gimp-layer-add-mask l mask)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 24 #(12 297 28 280 51 275 76 273 97 284 98 307 95 324 86 344 96 357 72 360 25 359 9 346))
(gimp-selection-feather im 1.5)
(gimp-context-set-foreground '(255 255 255))
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none im)
(gimp-xcf-save RUN-NONINTERACTIVE im l "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-opening/rested-hand-master.xcf" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-opening/rested-hand-master.xcf")
(set! out (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save2 RUN-NONINTERACTIVE im out "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-opening/rested-hand-candidate.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-opening/rested-hand-candidate.png" 0 9 0 0 0 0 0 0 0)
(gimp-image-delete im))
(gimp-quit 0)
