(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/renpy/game/art/base/rovel/details/treatment-white.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/renpy/game/art/base/rovel/details/treatment-white.png"))) (l 0) (mask 0) (out 0))
(gimp-item-set-name (car (gimp-image-get-active-layer im)) "Current neutral original — unchanged")
(set! l (car (gimp-file-load-layer RUN-NONINTERACTIVE im "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-opening/components/treatment-white-donor.png")))
(gimp-image-insert-layer im l 0 0)
(gimp-layer-scale l 640 300 TRUE)
(gimp-layer-set-offsets l 0 0)
(gimp-item-set-name l "Smooth ulnar palm edge after removal of extra ring digit")
(set! mask (car (gimp-layer-create-mask l ADD-BLACK-MASK)))
(gimp-layer-add-mask l mask)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 26 #(93 206 102 202 120 202 142 207 164 210 190 217 220 225 224 235 201 242 157 247 124 246 90 228 90 215))
(gimp-selection-feather im 1.5)
(gimp-context-set-foreground '(255 255 255))
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none im)
(gimp-xcf-save RUN-NONINTERACTIVE im l "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-opening/treatment-white-master.xcf" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-opening/treatment-white-master.xcf")
(set! out (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save2 RUN-NONINTERACTIVE im out "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-opening/treatment-white-candidate.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-opening/treatment-white-candidate.png" 0 9 0 0 0 0 0 0 0)
(gimp-image-delete im))
(gimp-quit 0)
