(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-opening/arrival-master.xcf" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-opening/arrival-master.xcf"))) (layers (gimp-image-get-layers im)) (mi (car (gimp-image-new 1672 941 RGB))) (bg (car (gimp-layer-new mi 1672 941 RGBA-IMAGE "Black outside repair masks" 100 NORMAL-MODE))) (j 0) (l 0) (mask 0) (ml 0) (off 0) (merged 0))
(gimp-image-insert-layer mi bg 0 0)
(gimp-context-set-foreground '(0 0 0))
(gimp-edit-fill bg FOREGROUND-FILL)
(while (< j (car layers))
 (set! l (vector-ref (cadr layers) j))
 (set! mask (car (gimp-layer-get-mask l)))
 (if (> mask -1)
  (begin
   (set! off (gimp-drawable-offsets l))
   (set! ml (car (gimp-layer-new-from-drawable mask mi)))
   (gimp-image-insert-layer mi ml 0 0)
   (gimp-layer-set-offsets ml (car off) (cadr off))
   (gimp-layer-set-mode ml LIGHTEN-ONLY-MODE)))
 (set! j (+ j 1)))
(set! merged (car (gimp-image-merge-visible-layers mi CLIP-TO-IMAGE)))
(file-png-save2 RUN-NONINTERACTIVE mi merged "/tmp/batch6-opening-checks/arrival-mask.png" "mask" 0 9 0 0 0 0 0 0 0)
(set! merged (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save2 RUN-NONINTERACTIVE im merged "/tmp/batch6-opening-checks/arrival-reopened.png" "reopened" 0 9 0 0 0 0 0 0 0)
(gimp-image-delete mi)
(gimp-image-delete im))
(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-opening/attempted-return-master.xcf" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-opening/attempted-return-master.xcf"))) (layers (gimp-image-get-layers im)) (mi (car (gimp-image-new 1672 941 RGB))) (bg (car (gimp-layer-new mi 1672 941 RGBA-IMAGE "Black outside repair masks" 100 NORMAL-MODE))) (j 0) (l 0) (mask 0) (ml 0) (off 0) (merged 0))
(gimp-image-insert-layer mi bg 0 0)
(gimp-context-set-foreground '(0 0 0))
(gimp-edit-fill bg FOREGROUND-FILL)
(while (< j (car layers))
 (set! l (vector-ref (cadr layers) j))
 (set! mask (car (gimp-layer-get-mask l)))
 (if (> mask -1)
  (begin
   (set! off (gimp-drawable-offsets l))
   (set! ml (car (gimp-layer-new-from-drawable mask mi)))
   (gimp-image-insert-layer mi ml 0 0)
   (gimp-layer-set-offsets ml (car off) (cadr off))
   (gimp-layer-set-mode ml LIGHTEN-ONLY-MODE)))
 (set! j (+ j 1)))
(set! merged (car (gimp-image-merge-visible-layers mi CLIP-TO-IMAGE)))
(file-png-save2 RUN-NONINTERACTIVE mi merged "/tmp/batch6-opening-checks/attempted-return-mask.png" "mask" 0 9 0 0 0 0 0 0 0)
(set! merged (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save2 RUN-NONINTERACTIVE im merged "/tmp/batch6-opening-checks/attempted-return-reopened.png" "reopened" 0 9 0 0 0 0 0 0 0)
(gimp-image-delete mi)
(gimp-image-delete im))
(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-opening/closure-master.xcf" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-opening/closure-master.xcf"))) (layers (gimp-image-get-layers im)) (mi (car (gimp-image-new 1672 941 RGB))) (bg (car (gimp-layer-new mi 1672 941 RGBA-IMAGE "Black outside repair masks" 100 NORMAL-MODE))) (j 0) (l 0) (mask 0) (ml 0) (off 0) (merged 0))
(gimp-image-insert-layer mi bg 0 0)
(gimp-context-set-foreground '(0 0 0))
(gimp-edit-fill bg FOREGROUND-FILL)
(while (< j (car layers))
 (set! l (vector-ref (cadr layers) j))
 (set! mask (car (gimp-layer-get-mask l)))
 (if (> mask -1)
  (begin
   (set! off (gimp-drawable-offsets l))
   (set! ml (car (gimp-layer-new-from-drawable mask mi)))
   (gimp-image-insert-layer mi ml 0 0)
   (gimp-layer-set-offsets ml (car off) (cadr off))
   (gimp-layer-set-mode ml LIGHTEN-ONLY-MODE)))
 (set! j (+ j 1)))
(set! merged (car (gimp-image-merge-visible-layers mi CLIP-TO-IMAGE)))
(file-png-save2 RUN-NONINTERACTIVE mi merged "/tmp/batch6-opening-checks/closure-mask.png" "mask" 0 9 0 0 0 0 0 0 0)
(set! merged (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save2 RUN-NONINTERACTIVE im merged "/tmp/batch6-opening-checks/closure-reopened.png" "reopened" 0 9 0 0 0 0 0 0 0)
(gimp-image-delete mi)
(gimp-image-delete im))
(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-opening/treatment-blue-master.xcf" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-opening/treatment-blue-master.xcf"))) (layers (gimp-image-get-layers im)) (mi (car (gimp-image-new 640 300 RGB))) (bg (car (gimp-layer-new mi 640 300 RGBA-IMAGE "Black outside repair masks" 100 NORMAL-MODE))) (j 0) (l 0) (mask 0) (ml 0) (off 0) (merged 0))
(gimp-image-insert-layer mi bg 0 0)
(gimp-context-set-foreground '(0 0 0))
(gimp-edit-fill bg FOREGROUND-FILL)
(while (< j (car layers))
 (set! l (vector-ref (cadr layers) j))
 (set! mask (car (gimp-layer-get-mask l)))
 (if (> mask -1)
  (begin
   (set! off (gimp-drawable-offsets l))
   (set! ml (car (gimp-layer-new-from-drawable mask mi)))
   (gimp-image-insert-layer mi ml 0 0)
   (gimp-layer-set-offsets ml (car off) (cadr off))
   (gimp-layer-set-mode ml LIGHTEN-ONLY-MODE)))
 (set! j (+ j 1)))
(set! merged (car (gimp-image-merge-visible-layers mi CLIP-TO-IMAGE)))
(file-png-save2 RUN-NONINTERACTIVE mi merged "/tmp/batch6-opening-checks/treatment-blue-mask.png" "mask" 0 9 0 0 0 0 0 0 0)
(set! merged (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save2 RUN-NONINTERACTIVE im merged "/tmp/batch6-opening-checks/treatment-blue-reopened.png" "reopened" 0 9 0 0 0 0 0 0 0)
(gimp-image-delete mi)
(gimp-image-delete im))
(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-opening/stretcher-passes-master.xcf" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-opening/stretcher-passes-master.xcf"))) (layers (gimp-image-get-layers im)) (mi (car (gimp-image-new 1672 941 RGB))) (bg (car (gimp-layer-new mi 1672 941 RGBA-IMAGE "Black outside repair masks" 100 NORMAL-MODE))) (j 0) (l 0) (mask 0) (ml 0) (off 0) (merged 0))
(gimp-image-insert-layer mi bg 0 0)
(gimp-context-set-foreground '(0 0 0))
(gimp-edit-fill bg FOREGROUND-FILL)
(while (< j (car layers))
 (set! l (vector-ref (cadr layers) j))
 (set! mask (car (gimp-layer-get-mask l)))
 (if (> mask -1)
  (begin
   (set! off (gimp-drawable-offsets l))
   (set! ml (car (gimp-layer-new-from-drawable mask mi)))
   (gimp-image-insert-layer mi ml 0 0)
   (gimp-layer-set-offsets ml (car off) (cadr off))
   (gimp-layer-set-mode ml LIGHTEN-ONLY-MODE)))
 (set! j (+ j 1)))
(set! merged (car (gimp-image-merge-visible-layers mi CLIP-TO-IMAGE)))
(file-png-save2 RUN-NONINTERACTIVE mi merged "/tmp/batch6-opening-checks/stretcher-passes-mask.png" "mask" 0 9 0 0 0 0 0 0 0)
(set! merged (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save2 RUN-NONINTERACTIVE im merged "/tmp/batch6-opening-checks/stretcher-passes-reopened.png" "reopened" 0 9 0 0 0 0 0 0 0)
(gimp-image-delete mi)
(gimp-image-delete im))
(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-opening/unanswered-cloak-master.xcf" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-opening/unanswered-cloak-master.xcf"))) (layers (gimp-image-get-layers im)) (mi (car (gimp-image-new 1672 941 RGB))) (bg (car (gimp-layer-new mi 1672 941 RGBA-IMAGE "Black outside repair masks" 100 NORMAL-MODE))) (j 0) (l 0) (mask 0) (ml 0) (off 0) (merged 0))
(gimp-image-insert-layer mi bg 0 0)
(gimp-context-set-foreground '(0 0 0))
(gimp-edit-fill bg FOREGROUND-FILL)
(while (< j (car layers))
 (set! l (vector-ref (cadr layers) j))
 (set! mask (car (gimp-layer-get-mask l)))
 (if (> mask -1)
  (begin
   (set! off (gimp-drawable-offsets l))
   (set! ml (car (gimp-layer-new-from-drawable mask mi)))
   (gimp-image-insert-layer mi ml 0 0)
   (gimp-layer-set-offsets ml (car off) (cadr off))
   (gimp-layer-set-mode ml LIGHTEN-ONLY-MODE)))
 (set! j (+ j 1)))
(set! merged (car (gimp-image-merge-visible-layers mi CLIP-TO-IMAGE)))
(file-png-save2 RUN-NONINTERACTIVE mi merged "/tmp/batch6-opening-checks/unanswered-cloak-mask.png" "mask" 0 9 0 0 0 0 0 0 0)
(set! merged (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save2 RUN-NONINTERACTIVE im merged "/tmp/batch6-opening-checks/unanswered-cloak-reopened.png" "reopened" 0 9 0 0 0 0 0 0 0)
(gimp-image-delete mi)
(gimp-image-delete im))
(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-opening/ward-entrance-master.xcf" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-opening/ward-entrance-master.xcf"))) (layers (gimp-image-get-layers im)) (mi (car (gimp-image-new 1672 941 RGB))) (bg (car (gimp-layer-new mi 1672 941 RGBA-IMAGE "Black outside repair masks" 100 NORMAL-MODE))) (j 0) (l 0) (mask 0) (ml 0) (off 0) (merged 0))
(gimp-image-insert-layer mi bg 0 0)
(gimp-context-set-foreground '(0 0 0))
(gimp-edit-fill bg FOREGROUND-FILL)
(while (< j (car layers))
 (set! l (vector-ref (cadr layers) j))
 (set! mask (car (gimp-layer-get-mask l)))
 (if (> mask -1)
  (begin
   (set! off (gimp-drawable-offsets l))
   (set! ml (car (gimp-layer-new-from-drawable mask mi)))
   (gimp-image-insert-layer mi ml 0 0)
   (gimp-layer-set-offsets ml (car off) (cadr off))
   (gimp-layer-set-mode ml LIGHTEN-ONLY-MODE)))
 (set! j (+ j 1)))
(set! merged (car (gimp-image-merge-visible-layers mi CLIP-TO-IMAGE)))
(file-png-save2 RUN-NONINTERACTIVE mi merged "/tmp/batch6-opening-checks/ward-entrance-mask.png" "mask" 0 9 0 0 0 0 0 0 0)
(set! merged (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save2 RUN-NONINTERACTIVE im merged "/tmp/batch6-opening-checks/ward-entrance-reopened.png" "reopened" 0 9 0 0 0 0 0 0 0)
(gimp-image-delete mi)
(gimp-image-delete im))
(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-opening/rested-hand-master.xcf" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-opening/rested-hand-master.xcf"))) (layers (gimp-image-get-layers im)) (mi (car (gimp-image-new 880 495 RGB))) (bg (car (gimp-layer-new mi 880 495 RGBA-IMAGE "Black outside repair masks" 100 NORMAL-MODE))) (j 0) (l 0) (mask 0) (ml 0) (off 0) (merged 0))
(gimp-image-insert-layer mi bg 0 0)
(gimp-context-set-foreground '(0 0 0))
(gimp-edit-fill bg FOREGROUND-FILL)
(while (< j (car layers))
 (set! l (vector-ref (cadr layers) j))
 (set! mask (car (gimp-layer-get-mask l)))
 (if (> mask -1)
  (begin
   (set! off (gimp-drawable-offsets l))
   (set! ml (car (gimp-layer-new-from-drawable mask mi)))
   (gimp-image-insert-layer mi ml 0 0)
   (gimp-layer-set-offsets ml (car off) (cadr off))
   (gimp-layer-set-mode ml LIGHTEN-ONLY-MODE)))
 (set! j (+ j 1)))
(set! merged (car (gimp-image-merge-visible-layers mi CLIP-TO-IMAGE)))
(file-png-save2 RUN-NONINTERACTIVE mi merged "/tmp/batch6-opening-checks/rested-hand-mask.png" "mask" 0 9 0 0 0 0 0 0 0)
(set! merged (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save2 RUN-NONINTERACTIVE im merged "/tmp/batch6-opening-checks/rested-hand-reopened.png" "reopened" 0 9 0 0 0 0 0 0 0)
(gimp-image-delete mi)
(gimp-image-delete im))
(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-opening/treatment-pause-master.xcf" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-opening/treatment-pause-master.xcf"))) (layers (gimp-image-get-layers im)) (mi (car (gimp-image-new 1672 941 RGB))) (bg (car (gimp-layer-new mi 1672 941 RGBA-IMAGE "Black outside repair masks" 100 NORMAL-MODE))) (j 0) (l 0) (mask 0) (ml 0) (off 0) (merged 0))
(gimp-image-insert-layer mi bg 0 0)
(gimp-context-set-foreground '(0 0 0))
(gimp-edit-fill bg FOREGROUND-FILL)
(while (< j (car layers))
 (set! l (vector-ref (cadr layers) j))
 (set! mask (car (gimp-layer-get-mask l)))
 (if (> mask -1)
  (begin
   (set! off (gimp-drawable-offsets l))
   (set! ml (car (gimp-layer-new-from-drawable mask mi)))
   (gimp-image-insert-layer mi ml 0 0)
   (gimp-layer-set-offsets ml (car off) (cadr off))
   (gimp-layer-set-mode ml LIGHTEN-ONLY-MODE)))
 (set! j (+ j 1)))
(set! merged (car (gimp-image-merge-visible-layers mi CLIP-TO-IMAGE)))
(file-png-save2 RUN-NONINTERACTIVE mi merged "/tmp/batch6-opening-checks/treatment-pause-mask.png" "mask" 0 9 0 0 0 0 0 0 0)
(set! merged (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save2 RUN-NONINTERACTIVE im merged "/tmp/batch6-opening-checks/treatment-pause-reopened.png" "reopened" 0 9 0 0 0 0 0 0 0)
(gimp-image-delete mi)
(gimp-image-delete im))
(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-opening/after-first-treatment-master.xcf" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-opening/after-first-treatment-master.xcf"))) (layers (gimp-image-get-layers im)) (mi (car (gimp-image-new 1672 941 RGB))) (bg (car (gimp-layer-new mi 1672 941 RGBA-IMAGE "Black outside repair masks" 100 NORMAL-MODE))) (j 0) (l 0) (mask 0) (ml 0) (off 0) (merged 0))
(gimp-image-insert-layer mi bg 0 0)
(gimp-context-set-foreground '(0 0 0))
(gimp-edit-fill bg FOREGROUND-FILL)
(while (< j (car layers))
 (set! l (vector-ref (cadr layers) j))
 (set! mask (car (gimp-layer-get-mask l)))
 (if (> mask -1)
  (begin
   (set! off (gimp-drawable-offsets l))
   (set! ml (car (gimp-layer-new-from-drawable mask mi)))
   (gimp-image-insert-layer mi ml 0 0)
   (gimp-layer-set-offsets ml (car off) (cadr off))
   (gimp-layer-set-mode ml LIGHTEN-ONLY-MODE)))
 (set! j (+ j 1)))
(set! merged (car (gimp-image-merge-visible-layers mi CLIP-TO-IMAGE)))
(file-png-save2 RUN-NONINTERACTIVE mi merged "/tmp/batch6-opening-checks/after-first-treatment-mask.png" "mask" 0 9 0 0 0 0 0 0 0)
(set! merged (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save2 RUN-NONINTERACTIVE im merged "/tmp/batch6-opening-checks/after-first-treatment-reopened.png" "reopened" 0 9 0 0 0 0 0 0 0)
(gimp-image-delete mi)
(gimp-image-delete im))
(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-opening/treatment-white-master.xcf" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-opening/treatment-white-master.xcf"))) (layers (gimp-image-get-layers im)) (mi (car (gimp-image-new 640 300 RGB))) (bg (car (gimp-layer-new mi 640 300 RGBA-IMAGE "Black outside repair masks" 100 NORMAL-MODE))) (j 0) (l 0) (mask 0) (ml 0) (off 0) (merged 0))
(gimp-image-insert-layer mi bg 0 0)
(gimp-context-set-foreground '(0 0 0))
(gimp-edit-fill bg FOREGROUND-FILL)
(while (< j (car layers))
 (set! l (vector-ref (cadr layers) j))
 (set! mask (car (gimp-layer-get-mask l)))
 (if (> mask -1)
  (begin
   (set! off (gimp-drawable-offsets l))
   (set! ml (car (gimp-layer-new-from-drawable mask mi)))
   (gimp-image-insert-layer mi ml 0 0)
   (gimp-layer-set-offsets ml (car off) (cadr off))
   (gimp-layer-set-mode ml LIGHTEN-ONLY-MODE)))
 (set! j (+ j 1)))
(set! merged (car (gimp-image-merge-visible-layers mi CLIP-TO-IMAGE)))
(file-png-save2 RUN-NONINTERACTIVE mi merged "/tmp/batch6-opening-checks/treatment-white-mask.png" "mask" 0 9 0 0 0 0 0 0 0)
(set! merged (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save2 RUN-NONINTERACTIVE im merged "/tmp/batch6-opening-checks/treatment-white-reopened.png" "reopened" 0 9 0 0 0 0 0 0 0)
(gimp-image-delete mi)
(gimp-image-delete im))
(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-opening/phone-message-master.xcf" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-opening/phone-message-master.xcf"))) (layers (gimp-image-get-layers im)) (mi (car (gimp-image-new 1672 941 RGB))) (bg (car (gimp-layer-new mi 1672 941 RGBA-IMAGE "Black outside repair masks" 100 NORMAL-MODE))) (j 0) (l 0) (mask 0) (ml 0) (off 0) (merged 0))
(gimp-image-insert-layer mi bg 0 0)
(gimp-context-set-foreground '(0 0 0))
(gimp-edit-fill bg FOREGROUND-FILL)
(while (< j (car layers))
 (set! l (vector-ref (cadr layers) j))
 (set! mask (car (gimp-layer-get-mask l)))
 (if (> mask -1)
  (begin
   (set! off (gimp-drawable-offsets l))
   (set! ml (car (gimp-layer-new-from-drawable mask mi)))
   (gimp-image-insert-layer mi ml 0 0)
   (gimp-layer-set-offsets ml (car off) (cadr off))
   (gimp-layer-set-mode ml LIGHTEN-ONLY-MODE)))
 (set! j (+ j 1)))
(set! merged (car (gimp-image-merge-visible-layers mi CLIP-TO-IMAGE)))
(file-png-save2 RUN-NONINTERACTIVE mi merged "/tmp/batch6-opening-checks/phone-message-mask.png" "mask" 0 9 0 0 0 0 0 0 0)
(set! merged (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save2 RUN-NONINTERACTIVE im merged "/tmp/batch6-opening-checks/phone-message-reopened.png" "reopened" 0 9 0 0 0 0 0 0 0)
(gimp-image-delete mi)
(gimp-image-delete im))
(gimp-quit 0)
