(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/renpy/game/art/base/opening/cg/ward-entrance.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/renpy/game/art/base/opening/cg/ward-entrance.png"))) (l 0) (mask 0) (out 0))
(gimp-item-set-name (car (gimp-image-get-active-layer im)) "Current neutral original — unchanged")
(set! l (car (gimp-file-load-layer RUN-NONINTERACTIVE im "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-opening/components/ward-entrance-head-donor.png")))
(gimp-image-insert-layer im l 0 0)
(gimp-layer-scale l 265 320 TRUE)
(gimp-layer-set-offsets l 285 20)
(gimp-item-set-name l "Mara \u2014 established mature facial identity and dark pinned hair")
(set! mask (car (gimp-layer-create-mask l ADD-BLACK-MASK)))
(gimp-layer-add-mask l mask)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 44 #(310 135 321 95 360 55 394 37 448 43 482 70 524 113 530 156 529 192 521 224 512 272 498 290 469 298 449 313 431 339 407 339 386 297 367 275 350 268 323 250 312 236 304 204))
(gimp-selection-feather im 1.5)
(gimp-context-set-foreground '(255 255 255))
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none im)
(gimp-xcf-save RUN-NONINTERACTIVE im l "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-opening/ward-entrance-master.xcf" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-opening/ward-entrance-master.xcf")
(set! out (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save2 RUN-NONINTERACTIVE im out "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-opening/ward-entrance-candidate.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-opening/ward-entrance-candidate.png" 0 9 0 0 0 0 0 0 0)
(gimp-image-delete im))
(gimp-quit 0)
