(define (layer-from-crop img source name sx sy sw sh dx dy dw dh)
  (let* ((src (car (gimp-file-load RUN-NONINTERACTIVE source source))) (layer 0))
    (gimp-image-crop src sw sh sx sy)
    (set! layer (car (gimp-layer-new-from-drawable (car (gimp-image-get-active-layer src)) img)))
    (gimp-image-insert-layer img layer 0 0)
    (gimp-item-set-name layer name)
    (gimp-layer-scale layer dw dh FALSE)
    (gimp-layer-set-offsets layer dx dy)
    (gimp-image-delete src)
    layer))
(define (mask-poly img layer points feather)
  (let* ((mask (car (gimp-layer-create-mask layer ADD-BLACK-MASK))))
    (gimp-layer-add-mask layer mask)
    (gimp-image-select-polygon img CHANNEL-OP-REPLACE (vector-length points) points)
    (if (> feather 0) (gimp-selection-feather img feather))
    (gimp-context-set-foreground '(255 255 255))
    (gimp-edit-fill mask FOREGROUND-FILL)
    (gimp-selection-none img)
    mask))
(define (exclude-poly img mask points feather)
  (gimp-image-select-polygon img CHANNEL-OP-REPLACE (vector-length points) points)
  (if (> feather 0) (gimp-selection-feather img feather))
  (gimp-context-set-foreground '(0 0 0))
  (gimp-edit-fill mask FOREGROUND-FILL)
  (gimp-selection-none img))
(define (export-master img stem)
  (gimp-xcf-save RUN-NONINTERACTIVE img (car (gimp-image-get-active-layer img)) (string-append stem ".xcf") stem)
  (let* ((copy (car (gimp-image-duplicate img))) (merged (car (gimp-image-merge-visible-layers copy CLIP-TO-IMAGE))))
    (file-png-save RUN-NONINTERACTIVE copy merged (string-append stem ".png") stem 0 9 0 0 0 0 0)
    (file-jpeg-save RUN-NONINTERACTIVE copy merged (string-append stem ".jpg") stem 0.90 0 1 0 "" 0 1 0 1)
    (gimp-image-delete copy))
  (gimp-image-delete img))
