(let* ((img (car (gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/s050-guard/margin-and-weapon-component.png" "visual-novel/art/scene-studies/s050-guard/margin-and-weapon-component.png"))) (base (car (gimp-image-get-active-layer img))))
(gimp-item-set-name base "Completed margins and removed wrong RIGHT hip sword")
(let* ((a (car (gimp-file-load-layer RUN-NONINTERACTIVE img "visual-novel/art/scene-studies/s050-guard/generation-initial.png"))))
(gimp-image-insert-layer img a 0 0)(gimp-layer-add-alpha a)(gimp-item-set-name a "Original faces coats and precise buckle contact - uniform registration")
(gimp-context-set-interpolation INTERPOLATION-NOHALO)(gimp-layer-scale a 1323 745 TRUE)(gimp-layer-set-offsets a 182 58)
(gimp-image-select-rectangle img CHANNEL-OP-REPLACE 194 70 1299 721)(gimp-selection-feather img 18)
(gimp-image-select-polygon img CHANNEL-OP-SUBTRACT 20 #(468 549 509 559 514 608 477 684 434 745 409 780 392 753 430 667 451 594 458 557))
(gimp-selection-feather img 1.5)(gimp-layer-add-mask a (car (gimp-layer-create-mask a ADD-SELECTION-MASK)))(gimp-selection-none img))
(gimp-image-scale img 1920 1080)
(gimp-xcf-save RUN-NONINTERACTIVE img (car (gimp-image-get-active-layer img)) "visual-novel/art/scene-studies/s050-guard/guard-master.xcf" "visual-novel/art/scene-studies/s050-guard/guard-master.xcf")
(let* ((dup (car (gimp-image-duplicate img))) (merged (car (gimp-image-merge-visible-layers dup CLIP-TO-IMAGE))))
(file-png-save RUN-NONINTERACTIVE dup merged "/tmp/s050-guard-final-candidate.png" "/tmp/s050-guard-final-candidate.png" 0 9 0 0 0 0 0)(gimp-image-delete dup))
(gimp-image-delete img))(gimp-quit 0)
