(let* ((img (car (gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/s054-wound/wound-local-master.xcf" "master")))
 (release (car (gimp-file-load-layer RUN-NONINTERACTIVE img "visual-novel/art/scene-studies/s054-wound/rear-release-component.png"))))
 (gimp-image-insert-layer img release 0 0)
 (gimp-layer-scale release 520 400 FALSE)
 (gimp-layer-set-offsets release 560 150)
 (gimp-item-set-name release "Rear entrance release and shallow walking space behind throne")
 (gimp-image-select-rectangle img CHANNEL-OP-REPLACE 570 170 495 365)
 (gimp-selection-feather img 7)
 (let ((mask (car (gimp-layer-create-mask release ADD-SELECTION-MASK)))) (gimp-layer-add-mask release mask))
 (gimp-selection-none img)
 (gimp-xcf-save RUN-NONINTERACTIVE img release "visual-novel/art/scene-studies/s054-wound/wound-local-master.xcf" "master")
 (let* ((copy (car (gimp-image-duplicate img))) (flat (car (gimp-image-merge-visible-layers copy CLIP-TO-IMAGE))))
  (file-png-save RUN-NONINTERACTIVE copy flat "/tmp/s054-wound-room-complete.png" "review" 0 9 0 0 0 0 0)
  (gimp-image-delete copy))
 (gimp-image-resize img 2352 1323 340 100)
 (let ((blank (car (gimp-layer-new img 2352 1323 RGBA-IMAGE "Gray unpainted framing guide" 100 NORMAL-MODE))))
  (gimp-image-insert-layer img blank 0 3)
  (gimp-context-set-foreground '(130 130 130))
  (gimp-drawable-fill blank FOREGROUND-FILL))
 (let ((flat (car (gimp-image-merge-visible-layers img CLIP-TO-IMAGE))))
 (file-png-save RUN-NONINTERACTIVE img flat "/tmp/s054-wound-margin-guide.png" "guide" 0 9 0 0 0 0 0))
 (gimp-image-delete img))
