(let* ((img (car (gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/s054-wound/wound-local-master.xcf" "master")))
       (layers (cadr (gimp-image-get-layers img)))
       (group (car (gimp-layer-group-new img))))
 (gimp-image-insert-layer img group 0 0)
 (gimp-item-set-name group "Original central action and bounded room repairs; no body rescaling")
 (gimp-image-reorder-item img (vector-ref layers 0) group 0)
 (gimp-image-reorder-item img (vector-ref layers 1) group 1)
 (gimp-image-reorder-item img (vector-ref layers 2) group 2)
 (gimp-image-resize img 2352 1323 340 100)
 (let ((border (car (gimp-file-load-layer RUN-NONINTERACTIVE img "visual-novel/art/scene-studies/s054-wound/framing-component.png"))))
  (gimp-image-insert-layer img border 0 1)
  (gimp-layer-scale border 2352 1323 FALSE)
  (gimp-layer-set-offsets border 0 0)
  (gimp-item-set-name border "Only outpainted stone perimeter and horn tip beyond retained source")
  (gimp-image-select-rectangle img CHANNEL-OP-REPLACE 348 105 1656 928)
  (gimp-selection-feather img 14)
  (let ((mask (car (gimp-layer-create-mask group ADD-SELECTION-MASK)))) (gimp-layer-add-mask group mask))
  (gimp-selection-none img)
  (gimp-xcf-save RUN-NONINTERACTIVE img border "visual-novel/art/scene-studies/s054-wound/wound-framed-master.xcf" "master")
  (gimp-context-set-interpolation INTERPOLATION-NOHALO)
  (gimp-image-scale img 1920 1080)
  (gimp-xcf-save RUN-NONINTERACTIVE img border "visual-novel/art/scene-studies/s054-wound/wound-delivery-master.xcf" "master")
  (let ((flat (car (gimp-image-merge-visible-layers img CLIP-TO-IMAGE))))
   (file-png-save RUN-NONINTERACTIVE img flat "/tmp/s054-wound-final-review.png" "review" 0 9 0 0 0 0 0)))
 (gimp-image-delete img))
