(let* ((img (car (gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/s054-wound/wound-delivery-master.xcf" "master")))
 (horn (car (gimp-file-load-layer RUN-NONINTERACTIVE img "visual-novel/art/scene-studies/s054-wound/horn-edge-component.png"))))
 (gimp-image-insert-layer img horn 0 0) (gimp-layer-scale horn 200 150 FALSE) (gimp-layer-set-offsets horn 1135 90)
 (gimp-item-set-name horn "Bounded horn edge and matching stone only; face and all actors retained")
 (gimp-image-select-polygon img CHANNEL-OP-REPLACE 18 (vector 1175 94 1331 94 1331 181 1298 179 1260 165 1220 164 1194 192 1180 193 1174 164))
 (gimp-selection-feather img 3)
 (let ((mask (car (gimp-layer-create-mask horn ADD-SELECTION-MASK)))) (gimp-layer-add-mask horn mask))
 (gimp-selection-none img)
 (gimp-xcf-save RUN-NONINTERACTIVE img horn "visual-novel/art/scene-studies/s054-wound/wound-delivery-master.xcf" "master")
 (let ((flat (car (gimp-image-merge-visible-layers img CLIP-TO-IMAGE)))) (file-png-save RUN-NONINTERACTIVE img flat "/tmp/s054-wound-final-review.png" "review" 0 9 0 0 0 0 0))
 (gimp-image-delete img))
