(let* ((img (car (gimp-file-load RUN-NONINTERACTIVE "/home/kir/.codex/generated_images/01a0d813-b01b-7003-ac1a-13c396875d28/exec-0b23b5cf-7866-41d1-ab48-accbf0bac9ac.png" "source"))) (lyr (car (gimp-image-get-active-layer img))) (bg (car (gimp-layer-new img 1672 941 RGB-IMAGE "Extension guide background" 100 NORMAL-MODE))))
(gimp-context-set-interpolation INTERPOLATION-NOHALO)
(gimp-image-scale img 1504 847)
(gimp-image-resize img 1672 941 84 28)
(gimp-image-insert-layer img bg 0 1)
(gimp-context-set-foreground '(156 156 156))
(gimp-drawable-fill bg FOREGROUND-FILL)
(gimp-item-set-name lyr "Source scaled uniformly; preserve this interior")
(gimp-xcf-save RUN-NONINTERACTIVE img lyr "/tmp/s043-frame-guide.xcf" "/tmp/s043-frame-guide.xcf")
(let ((flat (car (gimp-image-merge-visible-layers img CLIP-TO-IMAGE)))) (file-png-save RUN-NONINTERACTIVE img flat "/tmp/s043-frame-guide.png" "/tmp/s043-frame-guide.png" 0 9 0 0 0 0 0))
(gimp-image-delete img))
(gimp-quit 0)
