(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-temple-emblems/ceremony-mantle/before.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-temple-emblems/ceremony-mantle/before.png"))) (l 0) (mask 0) (out 0) (base 0))
(gimp-item-set-name (car (gimp-image-get-active-layer im)) "Current neutral original — unchanged")
(set! base (car (gimp-image-get-active-layer im)))
(set! l (car (gimp-file-load-layer RUN-NONINTERACTIVE im "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-temple-emblems/components/s004-blank-banner-cloth-donor.png")))
(gimp-image-insert-layer im l 0 0)
(gimp-layer-scale l 160 230 TRUE)
(gimp-layer-set-offsets l 415 -5)
(gimp-item-set-name l "Local same-banner blue cloth clears wrong ray count")
(gimp-brightness-contrast l 20 -8)
(set! mask (car (gimp-layer-create-mask l ADD-BLACK-MASK)))
(gimp-layer-add-mask l mask)
(gimp-context-set-sample-threshold-int 44)
(gimp-image-select-color im CHANNEL-OP-REPLACE base '(185 160 108))
(gimp-image-select-rectangle im CHANNEL-OP-INTERSECT 444 0 105 143)
(gimp-selection-grow im 2)
(gimp-selection-feather im 1.4)
(gimp-context-set-foreground '(255 255 255))
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none im)
(set! l (car (gimp-file-load-layer RUN-NONINTERACTIVE im "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-temple-emblems/components/s004-embroidered-sun-donor.png")))
(gimp-image-insert-layer im l 0 0)
(gimp-layer-scale l 126 147 TRUE)
(gimp-layer-set-offsets l 432 -2)
(gimp-item-set-name l "Twelve-ray embroidered sun \u2014 material-matched donor")
(plug-in-gauss-iir RUN-NONINTERACTIVE im l 2.3 TRUE TRUE)
(gimp-brightness-contrast l 15 -10)
(set! mask (car (gimp-layer-create-mask l ADD-BLACK-MASK)))
(gimp-layer-add-mask l mask)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 8 #(392 -42 597 -42 597 183 392 183))
(gimp-selection-feather im 0)
(gimp-context-set-foreground '(255 255 255))
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none im)
(set! l (car (gimp-file-load-layer RUN-NONINTERACTIVE im "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-temple-emblems/components/s004-blank-banner-cloth-donor.png")))
(gimp-image-insert-layer im l 0 0)
(gimp-layer-scale l 215 300 TRUE)
(gimp-layer-set-offsets l 1585 0)
(gimp-item-set-name l "Local same-banner blue cloth clears wrong right sun")
(set! mask (car (gimp-layer-create-mask l ADD-BLACK-MASK)))
(gimp-layer-add-mask l mask)
(gimp-context-set-sample-threshold-int 44)
(gimp-image-select-color im CHANNEL-OP-REPLACE base '(185 160 108))
(gimp-image-select-rectangle im CHANNEL-OP-INTERSECT 1608 0 175 182)
(gimp-selection-grow im 2)
(gimp-selection-feather im 1.4)
(gimp-context-set-foreground '(255 255 255))
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none im)
(set! l (car (gimp-file-load-layer RUN-NONINTERACTIVE im "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-temple-emblems/components/s004-embroidered-sun-donor.png")))
(gimp-image-insert-layer im l 0 0)
(gimp-layer-scale l 181 187 TRUE)
(gimp-layer-set-offsets l 1601 -12)
(gimp-item-set-name l "Twelve-ray embroidered sun \u2014 material-matched donor")
(plug-in-gauss-iir RUN-NONINTERACTIVE im l 2.3 TRUE TRUE)
(gimp-brightness-contrast l 15 -10)
(set! mask (car (gimp-layer-create-mask l ADD-BLACK-MASK)))
(gimp-layer-add-mask l mask)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 8 #(1549 -66 1834 -66 1834 229 1549 229))
(gimp-selection-feather im 0)
(gimp-context-set-foreground '(255 255 255))
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none im)
(set! l (car (gimp-file-load-layer RUN-NONINTERACTIVE im "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-temple-emblems/components/s004-blank-banner-cloth-donor.png")))
(gimp-image-insert-layer im l 0 0)
(gimp-layer-resize l 700 600 -150 -20)
(gimp-layer-scale l 60 98 TRUE)
(gimp-layer-set-offsets l 982 -4)
(gimp-item-set-name l "Local cloth removes northern-style star behind Senn")
(set! mask (car (gimp-layer-create-mask l ADD-BLACK-MASK)))
(gimp-layer-add-mask l mask)
(gimp-context-set-sample-threshold-int 44)
(gimp-image-select-color im CHANNEL-OP-REPLACE base '(185 160 108))
(gimp-image-select-rectangle im CHANNEL-OP-INTERSECT 994 0 40 88)
(gimp-selection-grow im 2)
(gimp-selection-feather im 1.4)
(gimp-context-set-foreground '(255 255 255))
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none im)
(set! l (car (gimp-file-load-layer RUN-NONINTERACTIVE im "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-temple-emblems/components/s004-embroidered-sun-donor.png")))
(gimp-image-insert-layer im l 0 0)
(gimp-layer-scale l 45 62 TRUE)
(gimp-layer-set-offsets l 990 8)
(gimp-item-set-name l "Twelve-ray embroidered sun \u2014 material-matched donor")
(plug-in-gauss-iir RUN-NONINTERACTIVE im l 2.3 TRUE TRUE)
(gimp-brightness-contrast l 15 -10)
(set! mask (car (gimp-layer-create-mask l ADD-BLACK-MASK)))
(gimp-layer-add-mask l mask)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 8 #(977 -7 1047 -7 1047 81 977 81))
(gimp-selection-feather im 0)
(gimp-context-set-foreground '(255 255 255))
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none im)
(gimp-xcf-save RUN-NONINTERACTIVE im l "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-temple-emblems/ceremony-mantle/repair-master.xcf" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-temple-emblems/ceremony-mantle/repair-master.xcf")
(set! out (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save2 RUN-NONINTERACTIVE im out "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-temple-emblems/ceremony-mantle/candidate.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-temple-emblems/ceremony-mantle/candidate.png" 0 9 0 0 0 0 0 0 0)
(gimp-image-delete im))
(gimp-quit 0)
