(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/s047-citadel-north-infirmary-before-dawn/toe-source.png" "toe.png")))
 (base (car (gimp-image-get-active-layer im))) (wide 0) (action 0) (mask 0) (flat 0))
 (gimp-context-set-interpolation INTERPOLATION-NOHALO)
 (gimp-image-scale im 1728 972)
 (gimp-item-set-name base "Only completed thin side margins, bottom floor and captain toe")
 (set! wide (car (gimp-file-load-layer RUN-NONINTERACTIVE im "visual-novel/art/scene-studies/s047-citadel-north-infirmary-before-dawn/outpaint-source.png")))
 (gimp-image-insert-layer im wide 0 -1)
 (gimp-layer-set-offsets wide 28 0)
 (gimp-item-set-name wide "Protected first wider room — six separate standing bodies and feet")
 (set! mask (car (gimp-layer-create-mask wide ADD-BLACK-MASK)))
 (gimp-layer-add-mask wide mask)
 (gimp-image-select-rectangle im CHANNEL-OP-REPLACE 30 0 1668 939)
 (gimp-selection-feather im 3)
 (gimp-edit-fill mask WHITE-FILL)
 (gimp-selection-none im)
 (set! action (car (gimp-file-load-layer RUN-NONINTERACTIVE im "visual-novel/art/scene-studies/s047-citadel-north-infirmary-before-dawn/sleeve-corrected-source.png")))
 (gimp-image-insert-layer im action 0 -1)
 (gimp-layer-scale action 1066 600 TRUE)
 (gimp-layer-set-offsets action 325 58)
 (gimp-item-set-name action "Exact original acting and bed contacts with local healthy-right-sleeve correction")
 (set! mask (car (gimp-layer-create-mask action ADD-BLACK-MASK)))
 (gimp-layer-add-mask action mask)
 (gimp-image-select-polygon im CHANNEL-OP-REPLACE 14 #(329 62 1387 62 1387 490 1290 490 1290 622 329 622 329 62))
 (gimp-selection-feather im 8)
 (gimp-edit-fill mask WHITE-FILL)
 (gimp-selection-none im)
 (gimp-xcf-save RUN-NONINTERACTIVE im action "visual-novel/art/scene-studies/s047-citadel-north-infirmary-before-dawn/ward-master.xcf" "ward-master.xcf")
 (set! flat (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
 (file-png-save RUN-NONINTERACTIVE im flat "/tmp/s047-native-assembled.png" "/tmp/s047-native-assembled.png" 0 9 0 0 0 0 0)
 (gimp-image-scale im 1920 1080)
 (set! flat (car (gimp-image-get-active-layer im)))
 (file-png-save RUN-NONINTERACTIVE im flat "/tmp/s047-final-candidate.png" "/tmp/s047-final-candidate.png" 0 9 0 0 0 0 0)
 (gimp-image-delete im))
(gimp-quit 0)
