(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/s047-citadel-north-infirmary-before-dawn/generation-initial.png" "initial.png"))) (base (car (gimp-image-get-active-layer im))) (patch 0) (mask 0) (flat 0) (bg 0))
 (gimp-context-set-interpolation INTERPOLATION-NOHALO)
 (gimp-item-set-name base "Original six officers and shared ward")
 (set! patch (car (gimp-file-load-layer RUN-NONINTERACTIVE im "visual-novel/art/scene-studies/s047-citadel-north-infirmary-before-dawn/right-sleeve-source.png")))
 (gimp-image-insert-layer im patch 0 -1)
 (gimp-layer-scale patch 290 340 TRUE)
 (gimp-layer-set-offsets patch 130 560)
 (gimp-item-set-name patch "Only healthy RIGHT sleeve/cuff — removes false bandage")
 (set! mask (car (gimp-layer-create-mask patch ADD-BLACK-MASK)))
 (gimp-layer-add-mask patch mask)
 (gimp-image-select-polygon im CHANNEL-OP-REPLACE 22 #(168 628 209 612 264 624 295 665 309 714 310 749 288 765 237 779 212 741 178 691 168 628))
 (gimp-selection-feather im 2)
 (gimp-edit-fill mask WHITE-FILL)
 (gimp-selection-none im)
 (gimp-xcf-save RUN-NONINTERACTIVE im patch "visual-novel/art/scene-studies/s047-citadel-north-infirmary-before-dawn/sleeve-master.xcf" "sleeve-master.xcf")
 (set! flat (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
 (file-png-save RUN-NONINTERACTIVE im flat "/tmp/s047-sleeve-fixed.png" "/tmp/s047-sleeve-fixed.png" 0 9 0 0 0 0 0)
 (gimp-image-scale im 1170 659)
 (gimp-image-resize im 1920 1080 375 70)
 (set! bg (car (gimp-layer-new im 1920 1080 RGB-IMAGE "Blank margins for natural complete standing supports" 100 NORMAL-MODE)))
 (gimp-image-insert-layer im bg 0 1)
 (gimp-context-set-background '(170 170 160))
 (gimp-drawable-fill bg BACKGROUND-FILL)
 (set! flat (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
 (file-png-save RUN-NONINTERACTIVE im flat "/tmp/s047-headroom-guide.png" "/tmp/s047-headroom-guide.png" 0 9 0 0 0 0 0)
 (gimp-image-delete im))
(gimp-quit 0)
