(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/s047-citadel-north-infirmary-before-dawn/outpaint-source.png" "outpaint.png"))) (flat 0) (bg 0))
 (gimp-image-resize im 1728 972 28 0)
 (set! bg (car (gimp-layer-new im 1728 972 RGB-IMAGE "Only toe and thin side margins" 100 NORMAL-MODE)))
 (gimp-image-insert-layer im bg 0 1)
 (gimp-context-set-background '(170 170 160))
 (gimp-drawable-fill bg BACKGROUND-FILL)
 (set! flat (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
 (file-png-save RUN-NONINTERACTIVE im flat "/tmp/s047-toe-guide.png" "/tmp/s047-toe-guide.png" 0 9 0 0 0 0 0)
 (gimp-image-delete im))
(gimp-quit 0)
