(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/s047-citadel-north-infirmary-before-dawn/ward-master.xcf" "ward-master.xcf"))) (flat (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE))))
 (file-png-save RUN-NONINTERACTIVE im flat "/tmp/s047-reopened-native.png" "/tmp/s047-reopened-native.png" 0 9 0 0 0 0 0)
 (gimp-context-set-interpolation INTERPOLATION-NOHALO)
 (gimp-image-scale im 1920 1080)
 (set! flat (car (gimp-image-get-active-layer im)))
 (file-png-save RUN-NONINTERACTIVE im flat "/tmp/s047-reopened-final.png" "/tmp/s047-reopened-final.png" 0 9 0 0 0 0 0)
 (gimp-image-delete im))
(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/s047-citadel-north-infirmary-before-dawn/sleeve-master.xcf" "sleeve-master.xcf"))) (flat (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE))))
 (file-png-save RUN-NONINTERACTIVE im flat "/tmp/s047-reopened-sleeve.png" "/tmp/s047-reopened-sleeve.png" 0 9 0 0 0 0 0)
 (gimp-image-delete im))
(gimp-quit 0)
