(let* ((src "visual-novel/art/scene-studies/s048-examination-tent/outpaint-supports.png") (img (car (gimp-file-load RUN-NONINTERACTIVE src src))) (layer (car (gimp-image-get-active-layer img))))
(gimp-context-set-interpolation INTERPOLATION-NOHALO)
(gimp-image-scale img 1920 1080)
(gimp-layer-add-alpha layer)
(gimp-image-resize img 1920 1080 0 -50)
(gimp-layer-resize-to-image-size layer)
(file-png-save RUN-NONINTERACTIVE img layer "/tmp/s048-lower-supports-target.png" "/tmp/s048-lower-supports-target.png" 0 9 0 0 0 0 0)
(gimp-image-delete img))
(gimp-quit 0)
