(define (reveal-rectangle img layer x y w h radius)
 (let ((mask (car (gimp-layer-create-mask layer ADD-BLACK-MASK))))
  (gimp-layer-add-mask layer mask)
  (gimp-image-select-rectangle img CHANNEL-OP-REPLACE x y w h)
  (gimp-selection-feather img radius)
  (gimp-context-set-foreground '(255 255 255))
  (gimp-edit-fill mask FOREGROUND-FILL)
  (gimp-selection-none img)))
(let* ((src "visual-novel/art/scene-studies/s048-examination-tent/outpaint-lower-edge.png")
       (img (car (gimp-file-load RUN-NONINTERACTIVE src src)))
       (lower (car (gimp-image-get-active-layer img))))
 (gimp-context-set-interpolation INTERPOLATION-NOHALO)
 (gimp-image-scale img 1920 1080)
 (gimp-item-set-name lower "Generated final 50px lower edge — complete existing boot toes and floor")
 (let ((wider (car (gimp-file-load-layer RUN-NONINTERACTIVE img "visual-novel/art/scene-studies/s048-examination-tent/outpaint-supports.png"))))
  (gimp-image-insert-layer img wider 0 0)
  (gimp-layer-scale wider 1920 1080 FALSE)
  (gimp-layer-set-offsets wider 0 -50)
  (gimp-item-set-name wider "First wider outpaint — chair supports and surrounding tent; lower edge feather")
  (reveal-rectangle img wider 0 0 1920 1026 5))
 (let ((original (car (gimp-file-load-layer RUN-NONINTERACTIVE img "visual-novel/art/scene-studies/s048-examination-tent/generation-initial.png"))))
  (gimp-image-insert-layer img original 0 0)
  (gimp-layer-set-offsets original 124 -20)
  (gimp-item-set-name original "Exact original cast, hands, papers and light — no resampling; masked boundary joins")
  (reveal-rectangle img original 128 0 1664 917 5)
  (gimp-xcf-save RUN-NONINTERACTIVE img original "visual-novel/art/scene-studies/s048-examination-tent/examination-tent-master.xcf" "visual-novel/art/scene-studies/s048-examination-tent/examination-tent-master.xcf"))
 (let ((flat (car (gimp-image-merge-visible-layers img CLIP-TO-IMAGE))))
  (file-png-save RUN-NONINTERACTIVE img flat "/tmp/s048-final-candidate.png" "/tmp/s048-final-candidate.png" 0 9 0 0 0 0 0))
 (gimp-image-delete img))
(gimp-quit 0)
