(let* ((im(car(gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/batch6-continuity/s042-cart/before.png" "visual-novel/art/scene-studies/batch6-continuity/s042-cart/before.png")))(l 0)(m 0)(f 0))
(set! l(car(gimp-file-load-layer RUN-NONINTERACTIVE im "visual-novel/art/scene-studies/batch6-continuity/s042-cart/cart-donor.png")))
(gimp-image-insert-layer im l 0 0)(gimp-layer-scale l 410 510 FALSE)(gimp-layer-set-offsets l 980 280)
(gimp-item-set-name l "Blade-length held scabbard")
(set! m(car(gimp-layer-create-mask l ADD-BLACK-MASK)))(gimp-layer-add-mask l m)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 16 #(1234 453 1259 449 1310 650 1313 682 1303 694 1289 687 1242 509 1232 461))
(gimp-selection-feather im 2)(gimp-edit-fill m WHITE-FILL)(gimp-selection-none im)
(set! l(car(gimp-file-load-layer RUN-NONINTERACTIVE im "visual-novel/art/scene-studies/batch6-continuity/s042-cart/cart-donor.png")))
(gimp-image-insert-layer im l 0 0)(gimp-layer-scale l 410 510 FALSE)(gimp-layer-set-offsets l 980 280)
(gimp-item-set-name l "Remove false spokes under footboard")
(set! m(car(gimp-layer-create-mask l ADD-BLACK-MASK)))(gimp-layer-add-mask l m)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 14 #(1142 636 1208 655 1257 665 1257 710 1153 720 1135 704 1133 681))
(gimp-selection-feather im 2)(gimp-edit-fill m WHITE-FILL)(gimp-selection-none im)
(gimp-xcf-save RUN-NONINTERACTIVE im l "visual-novel/art/scene-studies/batch6-continuity/s042-cart/repair-master.xcf" "visual-novel/art/scene-studies/batch6-continuity/s042-cart/repair-master.xcf")
(set! f(car(gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save RUN-NONINTERACTIVE im f "visual-novel/art/scene-studies/batch6-continuity/s042-cart/candidate.png" "visual-novel/art/scene-studies/batch6-continuity/s042-cart/candidate.png" 0 9 0 0 0 0 0)
(gimp-image-delete im))(gimp-quit 0)