(let* ((im(car(gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/batch6-continuity/s046-valcair-private-room/before.png" "visual-novel/art/scene-studies/batch6-continuity/s046-valcair-private-room/before.png")))(l 0)(m 0)(f 0))
(set! l(car(gimp-file-load-layer RUN-NONINTERACTIVE im "visual-novel/art/scene-studies/batch6-continuity/s046-valcair-private-room/intact-hem-donor.png")))
(gimp-image-insert-layer im l 0 0)(gimp-layer-scale l 365 440 FALSE)(gimp-layer-set-offsets l 230 430)
(gimp-item-set-name l "Intact lower coat panels; source face, wrap and room")
(set! m(car(gimp-layer-create-mask l ADD-BLACK-MASK)))(gimp-layer-add-mask l m)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 10 #(269 670 350 669 346 794 257 794 259 739))
(gimp-selection-feather im 4)(gimp-edit-fill m WHITE-FILL)(gimp-selection-none im)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 12 #(474 669 556 669 580 761 565 790 480 797 465 772))
(gimp-selection-feather im 4)(gimp-edit-fill m WHITE-FILL)(gimp-selection-none im)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 12 #(393 677 430 667 439 710 469 752 451 775 390 773))
(gimp-selection-feather im 4)(gimp-edit-fill m WHITE-FILL)(gimp-selection-none im)
(gimp-xcf-save RUN-NONINTERACTIVE im l "visual-novel/art/scene-studies/batch6-continuity/s046-valcair-private-room/repair-master.xcf" "visual-novel/art/scene-studies/batch6-continuity/s046-valcair-private-room/repair-master.xcf")
(set! f(car(gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save RUN-NONINTERACTIVE im f "visual-novel/art/scene-studies/batch6-continuity/s046-valcair-private-room/candidate.png" "visual-novel/art/scene-studies/batch6-continuity/s046-valcair-private-room/candidate.png" 0 9 0 0 0 0 0)
(gimp-image-delete im))(gimp-quit 0)
