(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/s045-citadel-north-infirmary/outpaint-source.png" "outpaint.png")))
 (base (car (gimp-image-get-active-layer im))) (src 0) (mask 0) (flat 0) (clean 0) (horn 0) (leftcloth 0))
 (gimp-context-set-interpolation INTERPOLATION-NOHALO)
 (gimp-image-scale im 1920 1080)
 (gimp-item-set-name base "Generated wider ward margins and completed boots — native 1672x941")
 (set! src (car (gimp-file-load-layer RUN-NONINTERACTIVE im "visual-novel/art/scene-studies/s045-citadel-north-infirmary/generation-initial.png")))
 (gimp-image-insert-layer im src 0 -1)
 (gimp-layer-scale src 1404 790 TRUE)
 (gimp-layer-set-offsets src 258 60)
 (gimp-item-set-name src "Original five-person action restored at uniform scale — soft margin join")
 (set! mask (car (gimp-layer-create-mask src ADD-BLACK-MASK)))
 (gimp-layer-add-mask src mask)
 (gimp-image-select-rectangle im CHANNEL-OP-REPLACE 262 64 1396 782)
 (gimp-selection-feather im 4)
 (gimp-edit-fill mask WHITE-FILL)
 (gimp-selection-none im)
 (set! flat (car (gimp-layer-new-from-visible im im "Reference composite for local repairs")))
 (gimp-image-insert-layer im flat 0 -1)
 (gimp-item-set-visible flat FALSE)
 (set! horn (car (gimp-file-load-layer RUN-NONINTERACTIVE im "visual-novel/art/scene-studies/s045-citadel-north-infirmary/serat-horn-source.png")))
 (gimp-image-insert-layer im horn 0 -1)
 (gimp-layer-scale horn 143 139 TRUE)
 (gimp-layer-set-offsets horn 749 60)
 (gimp-item-set-name horn "Only Serat near horn and underlying hair — short upright design")
 (set! mask (car (gimp-layer-create-mask horn ADD-BLACK-MASK)))
 (gimp-layer-add-mask horn mask)
 (gimp-image-select-polygon im CHANNEL-OP-REPLACE 18 #(822 82 845 79 871 89 874 121 869 136 855 144 833 134 822 113 822 82))
 (gimp-selection-feather im 2)
 (gimp-edit-fill mask WHITE-FILL)
 (gimp-selection-none im)
 (set! flat (car (gimp-layer-new-from-visible im im "Horn-corrected reference for cloth-only emblem repairs")))
 (gimp-image-insert-layer im flat 0 -1)
 (gimp-item-set-visible flat FALSE)
 (set! clean (car (gimp-layer-new-from-drawable flat im)))
 (gimp-image-insert-layer im clean 0 -1)
 (gimp-item-set-visible clean TRUE)
 (gimp-item-set-name clean "Left banner motif cleanup — only its own cloth sampled")
 (gimp-layer-resize clean 67 41 -40 -194)
 (gimp-layer-scale clean 67 143 TRUE)
 (gimp-layer-set-offsets clean 40 43)
 (set! mask (car (gimp-layer-create-mask clean ADD-BLACK-MASK)))
 (gimp-layer-add-mask clean mask)
 (gimp-image-select-rectangle im CHANNEL-OP-REPLACE 42 45 63 139)
 (gimp-selection-feather im 3)
 (gimp-edit-fill mask WHITE-FILL)
 (gimp-selection-none im)
 (set! leftcloth clean)
 (set! clean (car (gimp-layer-new-from-drawable flat im)))
 (gimp-image-insert-layer im clean 0 -1)
 (gimp-item-set-visible clean TRUE)
 (gimp-item-set-name clean "Right banner cloth restored from matching left banner folds")
 (gimp-image-remove-layer im clean)
 (set! clean (car (gimp-layer-copy leftcloth TRUE)))
 (gimp-image-insert-layer im clean 0 -1)
 (gimp-item-set-visible clean TRUE)
 (gimp-layer-remove-mask clean MASK-APPLY)
 (gimp-layer-scale clean 49 185 TRUE)
 (gimp-layer-set-offsets clean 1578 65)
 (set! mask (car (gimp-layer-create-mask clean ADD-BLACK-MASK)))
 (gimp-layer-add-mask clean mask)
 (gimp-image-select-rectangle im CHANNEL-OP-REPLACE 1580 67 45 181)
 (gimp-selection-feather im 3)
 (gimp-edit-fill mask WHITE-FILL)
 (gimp-selection-none im)
 (set! clean (car (gimp-layer-new-from-drawable flat im)))
 (gimp-image-insert-layer im clean 0 -1)
 (gimp-item-set-visible clean TRUE)
 (gimp-item-set-name clean "Lucan badge cloth")
 (gimp-layer-resize clean 29 32 -530 -454)
 (gimp-layer-set-offsets clean 531 400)
 (set! mask (car (gimp-layer-create-mask clean ADD-BLACK-MASK)))
 (gimp-layer-add-mask clean mask)
 (gimp-image-select-ellipse im CHANNEL-OP-REPLACE 533 402 25 28)
 (gimp-selection-feather im 2)
 (gimp-edit-fill mask WHITE-FILL)
 (gimp-selection-none im)
 (set! clean (car (gimp-layer-new-from-drawable flat im)))
 (gimp-image-insert-layer im clean 0 -1)
 (gimp-item-set-visible clean TRUE)
 (gimp-item-set-name clean "Serat badge cloth")
 (gimp-layer-resize clean 22 25 -833 -195)
 (gimp-layer-set-offsets clean 837 224)
 (set! mask (car (gimp-layer-create-mask clean ADD-BLACK-MASK)))
 (gimp-layer-add-mask clean mask)
 (gimp-image-select-ellipse im CHANNEL-OP-REPLACE 839 226 18 21)
 (gimp-selection-feather im 2)
 (gimp-edit-fill mask WHITE-FILL)
 (gimp-selection-none im)
 (set! clean (car (gimp-file-load-layer RUN-NONINTERACTIVE im "visual-novel/art/prop-keys/emblems/northern-split-star.png")))
 (gimp-image-insert-layer im clean 0 -1)
 (gimp-item-set-visible clean TRUE)
 (gimp-item-set-name clean "Left banner canonical split star")
 (gimp-layer-scale clean 72 72 TRUE)
 (gimp-layer-set-offsets clean 39 78)
 (gimp-layer-set-opacity clean 58)
 (set! clean (car (gimp-file-load-layer RUN-NONINTERACTIVE im "visual-novel/art/prop-keys/emblems/northern-split-star.png")))
 (gimp-image-insert-layer im clean 0 -1)
 (gimp-item-set-visible clean TRUE)
 (gimp-item-set-name clean "Right banner canonical split star")
 (gimp-layer-scale clean 49 49 TRUE)
 (gimp-layer-set-offsets clean 1577 127)
 (gimp-layer-set-opacity clean 66)
 (set! clean (car (gimp-file-load-layer RUN-NONINTERACTIVE im "visual-novel/art/prop-keys/emblems/northern-split-star.png")))
 (gimp-image-insert-layer im clean 0 -1)
 (gimp-item-set-visible clean TRUE)
 (gimp-item-set-name clean "Lucan canonical split star")
 (gimp-layer-scale clean 31 31 TRUE)
 (gimp-layer-set-offsets clean 528 398)
 (gimp-layer-set-opacity clean 92)
 (set! clean (car (gimp-file-load-layer RUN-NONINTERACTIVE im "visual-novel/art/prop-keys/emblems/northern-split-star.png")))
 (gimp-image-insert-layer im clean 0 -1)
 (gimp-item-set-visible clean TRUE)
 (gimp-item-set-name clean "Serat canonical split star")
 (gimp-layer-scale clean 27 27 TRUE)
 (gimp-layer-set-offsets clean 835 223)
 (gimp-layer-set-opacity clean 86)
 (gimp-xcf-save RUN-NONINTERACTIVE im horn "visual-novel/art/scene-studies/s045-citadel-north-infirmary/ward-master.xcf" "ward-master.xcf")
 (set! flat (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
 (file-png-save RUN-NONINTERACTIVE im flat "/tmp/s045-assembled.png" "/tmp/s045-assembled.png" 0 9 0 0 0 0 0)
 (gimp-image-delete im))
(gimp-quit 0)
