(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/s045-citadel-north-infirmary/generation-initial.png" "initial.png"))) (l (car (gimp-image-get-active-layer im))) (bg 0))
 (gimp-context-set-interpolation INTERPOLATION-NOHALO)
 (gimp-image-scale im 1404 790)
 (gimp-image-resize im 1920 1080 258 60)
 (set! bg (car (gimp-layer-new im 1920 1080 RGB-IMAGE "Neutral empty margins to extend" 100 NORMAL-MODE)))
 (gimp-image-insert-layer im bg 0 1)
 (gimp-context-set-background '(190 190 185))
 (gimp-drawable-fill bg BACKGROUND-FILL)
 (set! l (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
 (file-png-save RUN-NONINTERACTIVE im l "/tmp/s045-reframe-guide.png" "/tmp/s045-reframe-guide.png" 0 9 0 0 0 0 0)
 (gimp-image-delete im))
(gimp-quit 0)
