(define (poly im pts) (gimp-image-select-polygon im CHANNEL-OP-REPLACE (vector-length pts) pts))
(for-each (lambda (name)
(let* ((dir (string-append "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-citadel/" name))
 (im (car (gimp-file-load RUN-NONINTERACTIVE (string-append dir "/repair-master.xcf") (string-append dir "/repair-master.xcf"))))
 (ly (vector-ref (cadr (gimp-image-get-layers im)) 0)) (mask (car (gimp-layer-get-mask ly))))
 ; Generous keep-out around complete original hand, arm and Olan hair. Feather transition lies in masonry.
 (gimp-image-select-rectangle im CHANNEL-OP-REPLACE 975 100 285 340) (gimp-selection-feather im 14)
 (gimp-context-set-foreground '(0 0 0)) (gimp-edit-fill mask FOREGROUND-FILL) (gimp-selection-none im)
 (gimp-image-select-rectangle im CHANNEL-OP-REPLACE 995 130 245 280) (gimp-edit-fill mask FOREGROUND-FILL) (gimp-selection-none im)
 (gimp-xcf-save RUN-NONINTERACTIVE im ly (string-append dir "/repair-master.xcf") (string-append dir "/repair-master.xcf"))
 (let ((out (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))) (file-png-save2 RUN-NONINTERACTIVE im out (string-append dir "/candidate.png") (string-append dir "/candidate.png") 0 9 0 0 0 0 0 0 0)) (gimp-image-delete im))) '("s052-citadel-inner-landing" "s052-entrance-ward"))
(let* ((dir "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch6-citadel/s055-citadel-lower-stair-morning")
 (im (car (gimp-file-load RUN-NONINTERACTIVE (string-append dir "/repair-master.xcf") (string-append dir "/repair-master.xcf"))))
 (src (car (gimp-layer-new-from-visible im im "Sampling: current Lucan trousers"))) (clean 0))
 (gimp-image-insert-layer im src 0 0) (gimp-item-set-visible src FALSE)
 (set! clean (car (gimp-layer-new im 1920 1080 RGBA-IMAGE "Torn coat reveals charcoal fabric, never bare thigh" 100 NORMAL-MODE)))
 (gimp-image-insert-layer im clean 0 0) (gimp-context-set-brush "2. Hardness 075") (gimp-context-set-brush-size 42)
 (poly im #(1396 482 1402 487 1406 497 1410 506 1412 512 1407 510 1403 506 1400 501 1397 491)) (gimp-selection-feather im 0.8)
 (gimp-clone clean src CLONE-IMAGE 1428 580 4 #(1402 493 1406 507)) (gimp-selection-none im)
 ; Upper sleeve rupture exposes dark garment lining rather than another invented wound.
 (poly im #(1390 245 1403 238 1405 254 1394 260 1380 261 1381 253)) (gimp-selection-feather im 0.8)
 (gimp-clone clean src CLONE-IMAGE 1446 464 2 #(1393 249)) (gimp-selection-none im)
 (poly im #(1364 267 1381 260 1379 271 1363 275)) (gimp-selection-feather im 0.8)
 (gimp-clone clean src CLONE-IMAGE 1446 464 2 #(1372 267)) (gimp-selection-none im)
 (gimp-xcf-save RUN-NONINTERACTIVE im clean (string-append dir "/repair-master.xcf") (string-append dir "/repair-master.xcf"))
 (let ((out (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))) (file-png-save2 RUN-NONINTERACTIVE im out (string-append dir "/candidate.png") (string-append dir "/candidate.png") 0 9 0 0 0 0 0 0 0)) (gimp-image-delete im))
(gimp-quit 0)
