(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/batch6-gray-scar/s018-gray-scar-ferry-approach-master.xcf" "visual-novel/art/scene-studies/batch6-gray-scar/s018-gray-scar-ferry-approach-master.xcf"))) (info (gimp-image-get-layers im)) (count (car info)) (layers (cadr info)) (i 0) (channel 0) (proof 0) (ly 0))
 (let ((flat (car (gimp-layer-new-from-visible im im "Reopened master projection"))))
  (gimp-image-insert-layer im flat 0 0)
  (file-png-save RUN-NONINTERACTIVE im flat "/tmp/s018-gray-scar-ferry-approach-reopened.png" "/tmp/s018-gray-scar-ferry-approach-reopened.png" 0 9 0 0 0 0 0)
  (gimp-image-remove-layer im flat))
 (gimp-selection-none im)
 (while (< i (- count 1))
  (let* ((layer (vector-ref layers i)) (mask (car (gimp-layer-get-mask layer))))
   (if (= mask -1) (gimp-image-select-item im CHANNEL-OP-ADD layer) (gimp-image-select-item im CHANNEL-OP-ADD mask)))
  (set! i (+ i 1)))
 (set! channel (car (gimp-selection-save im)))
 (set! proof (car (gimp-image-new 1920 1080 RGB)))
 (set! ly (car (gimp-layer-new-from-drawable channel proof)))
 (gimp-image-insert-layer proof ly 0 0)
 (file-png-save RUN-NONINTERACTIVE proof ly "/tmp/s018-gray-scar-ferry-approach-allowed-mask.png" "/tmp/s018-gray-scar-ferry-approach-allowed-mask.png" 0 9 0 0 0 0 0)
 (gimp-image-delete proof) (gimp-image-delete im))
(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/batch6-gray-scar/s019-gray-scar-ferryhouse-master.xcf" "visual-novel/art/scene-studies/batch6-gray-scar/s019-gray-scar-ferryhouse-master.xcf"))) (info (gimp-image-get-layers im)) (count (car info)) (layers (cadr info)) (i 0) (channel 0) (proof 0) (ly 0))
 (let ((flat (car (gimp-layer-new-from-visible im im "Reopened master projection"))))
  (gimp-image-insert-layer im flat 0 0)
  (file-png-save RUN-NONINTERACTIVE im flat "/tmp/s019-gray-scar-ferryhouse-reopened.png" "/tmp/s019-gray-scar-ferryhouse-reopened.png" 0 9 0 0 0 0 0)
  (gimp-image-remove-layer im flat))
 (gimp-selection-none im)
 (while (< i (- count 1))
  (let* ((layer (vector-ref layers i)) (mask (car (gimp-layer-get-mask layer))))
   (if (= mask -1) (gimp-image-select-item im CHANNEL-OP-ADD layer) (gimp-image-select-item im CHANNEL-OP-ADD mask)))
  (set! i (+ i 1)))
 (set! channel (car (gimp-selection-save im)))
 (set! proof (car (gimp-image-new 1920 1080 RGB)))
 (set! ly (car (gimp-layer-new-from-drawable channel proof)))
 (gimp-image-insert-layer proof ly 0 0)
 (file-png-save RUN-NONINTERACTIVE proof ly "/tmp/s019-gray-scar-ferryhouse-allowed-mask.png" "/tmp/s019-gray-scar-ferryhouse-allowed-mask.png" 0 9 0 0 0 0 0)
 (gimp-image-delete proof) (gimp-image-delete im))
(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/batch6-gray-scar/s020-gray-scar-riverbank-master.xcf" "visual-novel/art/scene-studies/batch6-gray-scar/s020-gray-scar-riverbank-master.xcf"))) (info (gimp-image-get-layers im)) (count (car info)) (layers (cadr info)) (i 0) (channel 0) (proof 0) (ly 0))
 (let ((flat (car (gimp-layer-new-from-visible im im "Reopened master projection"))))
  (gimp-image-insert-layer im flat 0 0)
  (file-png-save RUN-NONINTERACTIVE im flat "/tmp/s020-gray-scar-riverbank-reopened.png" "/tmp/s020-gray-scar-riverbank-reopened.png" 0 9 0 0 0 0 0)
  (gimp-image-remove-layer im flat))
 (gimp-selection-none im)
 (while (< i (- count 1))
  (let* ((layer (vector-ref layers i)) (mask (car (gimp-layer-get-mask layer))))
   (if (= mask -1) (gimp-image-select-item im CHANNEL-OP-ADD layer) (gimp-image-select-item im CHANNEL-OP-ADD mask)))
  (set! i (+ i 1)))
 (set! channel (car (gimp-selection-save im)))
 (set! proof (car (gimp-image-new 1920 1080 RGB)))
 (set! ly (car (gimp-layer-new-from-drawable channel proof)))
 (gimp-image-insert-layer proof ly 0 0)
 (file-png-save RUN-NONINTERACTIVE proof ly "/tmp/s020-gray-scar-riverbank-allowed-mask.png" "/tmp/s020-gray-scar-riverbank-allowed-mask.png" 0 9 0 0 0 0 0)
 (gimp-image-delete proof) (gimp-image-delete im))
(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/batch6-gray-scar/s021-gray-scar-covered-landing-master.xcf" "visual-novel/art/scene-studies/batch6-gray-scar/s021-gray-scar-covered-landing-master.xcf"))) (info (gimp-image-get-layers im)) (count (car info)) (layers (cadr info)) (i 0) (channel 0) (proof 0) (ly 0))
 (let ((flat (car (gimp-layer-new-from-visible im im "Reopened master projection"))))
  (gimp-image-insert-layer im flat 0 0)
  (file-png-save RUN-NONINTERACTIVE im flat "/tmp/s021-gray-scar-covered-landing-reopened.png" "/tmp/s021-gray-scar-covered-landing-reopened.png" 0 9 0 0 0 0 0)
  (gimp-image-remove-layer im flat))
 (gimp-selection-none im)
 (while (< i (- count 1))
  (let* ((layer (vector-ref layers i)) (mask (car (gimp-layer-get-mask layer))))
   (if (= mask -1) (gimp-image-select-item im CHANNEL-OP-ADD layer) (gimp-image-select-item im CHANNEL-OP-ADD mask)))
  (set! i (+ i 1)))
 (set! channel (car (gimp-selection-save im)))
 (set! proof (car (gimp-image-new 1920 1080 RGB)))
 (set! ly (car (gimp-layer-new-from-drawable channel proof)))
 (gimp-image-insert-layer proof ly 0 0)
 (file-png-save RUN-NONINTERACTIVE proof ly "/tmp/s021-gray-scar-covered-landing-allowed-mask.png" "/tmp/s021-gray-scar-covered-landing-allowed-mask.png" 0 9 0 0 0 0 0)
 (gimp-image-delete proof) (gimp-image-delete im))
(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/batch6-gray-scar/s021-lucan-returns-master.xcf" "visual-novel/art/scene-studies/batch6-gray-scar/s021-lucan-returns-master.xcf"))) (info (gimp-image-get-layers im)) (count (car info)) (layers (cadr info)) (i 0) (channel 0) (proof 0) (ly 0))
 (let ((flat (car (gimp-layer-new-from-visible im im "Reopened master projection"))))
  (gimp-image-insert-layer im flat 0 0)
  (file-png-save RUN-NONINTERACTIVE im flat "/tmp/s021-lucan-returns-reopened.png" "/tmp/s021-lucan-returns-reopened.png" 0 9 0 0 0 0 0)
  (gimp-image-remove-layer im flat))
 (gimp-selection-none im)
 (while (< i (- count 1))
  (let* ((layer (vector-ref layers i)) (mask (car (gimp-layer-get-mask layer))))
   (if (= mask -1) (gimp-image-select-item im CHANNEL-OP-ADD layer) (gimp-image-select-item im CHANNEL-OP-ADD mask)))
  (set! i (+ i 1)))
 (set! channel (car (gimp-selection-save im)))
 (set! proof (car (gimp-image-new 1920 1080 RGB)))
 (set! ly (car (gimp-layer-new-from-drawable channel proof)))
 (gimp-image-insert-layer proof ly 0 0)
 (file-png-save RUN-NONINTERACTIVE proof ly "/tmp/s021-lucan-returns-allowed-mask.png" "/tmp/s021-lucan-returns-allowed-mask.png" 0 9 0 0 0 0 0)
 (gimp-image-delete proof) (gimp-image-delete im))
(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/batch6-gray-scar/s021-rescue-master.xcf" "visual-novel/art/scene-studies/batch6-gray-scar/s021-rescue-master.xcf"))) (info (gimp-image-get-layers im)) (count (car info)) (layers (cadr info)) (i 0) (channel 0) (proof 0) (ly 0))
 (let ((flat (car (gimp-layer-new-from-visible im im "Reopened master projection"))))
  (gimp-image-insert-layer im flat 0 0)
  (file-png-save RUN-NONINTERACTIVE im flat "/tmp/s021-rescue-reopened.png" "/tmp/s021-rescue-reopened.png" 0 9 0 0 0 0 0)
  (gimp-image-remove-layer im flat))
 (gimp-selection-none im)
 (while (< i (- count 1))
  (let* ((layer (vector-ref layers i)) (mask (car (gimp-layer-get-mask layer))))
   (if (= mask -1) (gimp-image-select-item im CHANNEL-OP-ADD layer) (gimp-image-select-item im CHANNEL-OP-ADD mask)))
  (set! i (+ i 1)))
 (set! channel (car (gimp-selection-save im)))
 (set! proof (car (gimp-image-new 1920 1080 RGB)))
 (set! ly (car (gimp-layer-new-from-drawable channel proof)))
 (gimp-image-insert-layer proof ly 0 0)
 (file-png-save RUN-NONINTERACTIVE proof ly "/tmp/s021-rescue-allowed-mask.png" "/tmp/s021-rescue-allowed-mask.png" 0 9 0 0 0 0 0)
 (gimp-image-delete proof) (gimp-image-delete im))
(gimp-quit 0)
