(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/s057-father/bearer-complexion-correction/repair-master.xcf" "master"))) (l 0) (m 0) (mi 0) (bg 0) (ml 0) (off 0) (out 0))
(set! l (vector-ref (cadr (gimp-image-get-layers im)) 0))
(set! m (car (gimp-layer-get-mask l)))
(set! off (gimp-drawable-offsets l))
(set! mi (car (gimp-image-new 2240 1260 RGB)))
(set! bg (car (gimp-layer-new mi 2240 1260 RGBA-IMAGE "Black outside new correction mask" 100 NORMAL-MODE)))
(gimp-image-insert-layer mi bg 0 0)
(gimp-context-set-foreground '(0 0 0))
(gimp-edit-fill bg FOREGROUND-FILL)
(set! ml (car (gimp-layer-new-from-drawable m mi)))
(gimp-image-insert-layer mi ml 0 0)
(gimp-layer-set-offsets ml (car off) (cadr off))
(set! out (car (gimp-image-merge-visible-layers mi CLIP-TO-IMAGE)))
(file-png-save2 RUN-NONINTERACTIVE mi out "visual-novel/art/scene-studies/s057-father/bearer-complexion-correction/actual-mask.png" "mask" 0 9 0 0 0 0 0 0 0)
(set! out (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save2 RUN-NONINTERACTIVE im out "visual-novel/art/scene-studies/s057-father/bearer-complexion-correction/reopened.png" "reopened" 0 9 0 0 0 0 0 0 0)
(gimp-image-delete im)(gimp-image-delete mi))
(gimp-quit 0)
