(let* ((im(car(gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/batch6-hall/s054-wound/before.png" "visual-novel/art/scene-studies/batch6-hall/s054-wound/before.png"))) (l(car(gimp-file-load-layer RUN-NONINTERACTIVE im "visual-novel/art/scene-studies/batch6-hall/s054-wound/torn-glove-donor.png"))) (m 0)(f 0))
(gimp-image-insert-layer im l 0 0)(gimp-layer-scale l 460 360 FALSE)(gimp-layer-set-offsets l 490 430)
(gimp-item-set-name l "Torn right glove and restrained wound; all five digits retained")
(set! m(car(gimp-layer-create-mask l ADD-BLACK-MASK)))(gimp-layer-add-mask l m)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 22 #(620 571 651 566 684 577 706 595 722 605 728 629 717 647 683 648 656 634 636 622 620 605))
(gimp-selection-feather im 1.5)(gimp-edit-fill m WHITE-FILL)(gimp-selection-none im)
(gimp-xcf-save RUN-NONINTERACTIVE im l "visual-novel/art/scene-studies/batch6-hall/s054-wound/repair-master.xcf" "visual-novel/art/scene-studies/batch6-hall/s054-wound/repair-master.xcf")
(set! f(car(gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save RUN-NONINTERACTIVE im f "visual-novel/art/scene-studies/batch6-hall/s054-wound/candidate.png" "visual-novel/art/scene-studies/batch6-hall/s054-wound/candidate.png" 0 9 0 0 0 0 0)
(gimp-image-delete im))(gimp-quit 0)