(gimp-context-push)
(let* ((img (car (gimp-file-load RUN-NONINTERACTIVE "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch7-gray-scar/s020-gray-scar-riverbank/source.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch7-gray-scar/s020-gray-scar-riverbank/source.png"))))
(gimp-item-set-name (car (gimp-image-get-active-layer img)) "Current source — protected base")
(let* ((ly (car (gimp-file-load-layer RUN-NONINTERACTIVE img "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch7-gray-scar/s020-gray-scar-riverbank/heads-donor.png"))) (mask 0))
(gimp-image-insert-layer img ly 0 0)
(gimp-item-set-name ly "Tessa youthful identity and chestnut ponytail")
(gimp-layer-scale ly 457 415 TRUE)
(gimp-layer-set-offsets ly 478 210)
(set! mask (car (gimp-layer-create-mask ly ADD-BLACK-MASK)))
(gimp-layer-add-mask ly mask)
(gimp-image-select-polygon img CHANNEL-OP-REPLACE 24 (vector 705 435 722 418 744 407 768 389 801 389 838 406 851 445 840 484 823 506 783 500 751 480 713 476))
(gimp-selection-feather img 3)
(gimp-context-set-foreground "white")
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none img)
)
(let* ((ly (car (gimp-file-load-layer RUN-NONINTERACTIVE img "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch7-gray-scar/s020-gray-scar-riverbank/horns-visible-donor.png"))) (mask 0))
(gimp-image-insert-layer img ly 0 0)
(gimp-item-set-name ly "Lucan smooth paired backward horns")
(gimp-layer-scale ly 238 140 TRUE)
(gimp-layer-set-offsets ly 590 237)
(set! mask (car (gimp-layer-create-mask ly ADD-BLACK-MASK)))
(gimp-layer-add-mask ly mask)
(gimp-image-select-polygon img CHANNEL-OP-REPLACE 28 (vector 630 280 642 257 674 245 704 251 739 258 753 280 749 306 721 313 704 316 704 287 680 282 658 283 645 300 634 310))
(gimp-selection-feather img 3)
(gimp-context-set-foreground "white")
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none img)
)
(let* ((ly (car (gimp-file-load-layer RUN-NONINTERACTIVE img "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch7-gray-scar/s020-gray-scar-riverbank/patient-hair-donor.png"))) (mask 0))
(gimp-image-insert-layer img ly 0 0)
(gimp-item-set-name ly "Adult patient light-brown hair from S019 continuity")
(gimp-layer-scale ly 297 265 TRUE)
(gimp-layer-set-offsets ly 908 392)
(set! mask (car (gimp-layer-create-mask ly ADD-BLACK-MASK)))
(gimp-layer-add-mask ly mask)
(gimp-image-select-polygon img CHANNEL-OP-REPLACE 40 (vector 973 521 980 506 995 496 1013 491 1035 490 1044 498 1039 501 1038 506 1035 515 1033 524 1031 529 1026 533 1027 540 1032 541 1041 546 1041 552 1029 559 1007 557 994 550 978 546))
(gimp-selection-feather img 0.8)
(gimp-context-set-foreground "white")
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none img)
)
(gimp-xcf-save RUN-NONINTERACTIVE img (car (gimp-image-get-active-layer img)) "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch7-gray-scar/s020-gray-scar-riverbank/master.xcf" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch7-gray-scar/s020-gray-scar-riverbank/master.xcf")
(let* ((dup (car (gimp-image-duplicate img))) (flat (car (gimp-image-merge-visible-layers dup CLIP-TO-IMAGE))))
(file-png-save RUN-NONINTERACTIVE dup flat "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch7-gray-scar/s020-gray-scar-riverbank/candidate.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch7-gray-scar/s020-gray-scar-riverbank/candidate.png" 0 9 0 0 0 0 0)
(gimp-image-delete dup))
(gimp-image-delete img))
(let* ((re (car (gimp-file-load RUN-NONINTERACTIVE "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch7-gray-scar/s020-gray-scar-riverbank/master.xcf" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch7-gray-scar/s020-gray-scar-riverbank/master.xcf"))) (flat (car (gimp-image-merge-visible-layers re CLIP-TO-IMAGE))))
(file-png-save RUN-NONINTERACTIVE re flat "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch7-gray-scar/s020-gray-scar-riverbank/reopened.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch7-gray-scar/s020-gray-scar-riverbank/reopened.png" 0 9 0 0 0 0 0)
(gimp-image-delete re))
(gimp-context-pop)
(gimp-quit 0)
