# Player-only adaptation writing. Provenance and limits are recorded separately
# in investigation-content.md; none of these variables enters character dialogue.
init python:
    evidence = {
        'phone': dict(round=1, title='The interrupted errand', source='Observed · summoning and apartment', body="Tessa is nineteen. She steps off an ordinary sidewalk with groceries. Her mother’s message asks whether she got the milk. The message is already on the phone; receiving it is not evidence that the temple can send anything back.\n\nTessa repeatedly tries to call. The phone reports no service, then loses its charge that night. She begins drawing her mother’s kitchen on the back of the welcome letter. This is an attempt to hold on to a particular home, not evidence that she has accepted the new one.", detail='The original message and the later failed calls establish different things. A stored message is not a working connection.'),
        'promise': dict(round=1, title='A promise, without a demonstration', source='Observed · Senn at the sealed arch', body="Senn tells Tessa she will go home when the work is over. He offers his word. Neither he nor the scholar demonstrates a way to reopen the passage. When Tessa asks them to contact her mother, both leave her waiting.\n\nThe promise matters because she has just been taken somewhere without consenting. At this point the player can distinguish an assurance from a demonstrated capability. There is not yet enough evidence to decide why the assurance was given.", detail='No return journey, outgoing message or tested return procedure is shown.'),
        'olan': dict(round=1, title='What changes in Olan’s arm', source='Observed · palace infirmary', body="An older healer closes the bleeding edges with blue light, but the darkness under Olan’s skin continues spreading. Tessa’s white light clears that darkness. Olan feels Iven touch the skin that has cleared.\n\nTwo fingers were already missing from Olan’s right hand. They remain missing afterward. Iven says they will not grow back. The successful treatment and the permanent loss are both visible in the same encounter; success does not mean every kind of damage can be undone.", detail='Blue light closes the wound; white light removes the curse; neither replaces the missing fingers.'),
        'public_role': dict(round=1, title='The announcement and the afternoon', source='Observed · audience hall and infirmary', body="Senn places the badge and mantle on Tessa and announces the next day’s convoy. Tessa asks when she agreed to go. Iven has not cleared her for travel and intervenes when Orra asks him.\n\nAfterward, he can give her an afternoon. He cannot promise to stop the demands people will make of her. When she asks whether he is coming, he promises to travel with her. This is companionship with a practical limit, not institutional permission for Tessa to go home.", detail='Iven’s promise concerns what he himself can do. Senn’s promise concerns a return nobody has shown.'),
        'cut_pages': dict(round=2, title='Translations and the cut original', source='Observed · Elin’s inquiry', body="Elin compares translations, then uses her master’s seal to obtain the original summoning book. Four pages have been cut out. The physical absence is something the translations alone did not show her.\n\nA missing passage can establish that the surviving book is incomplete. It does not, on its own, establish that the missing pages describe a return, who removed them, or whether any return procedure would work. Elin risks her access to let Tessa see the actual problem.", detail='Absence is evidence of incompleteness, not proof of what the missing text contained.'),
        'scholar': dict(round=2, title='What the scholar actually said', source='Observed · scholar and Elin, without Tessa', body="The scholar admits that he never promised Senn a way back. His admission concerns what was known and represented before this summoning. It gives the player firmer grounds to question Senn’s assurance than the failed phone calls alone supplied.\n\nThe scholar asks for secrecy. He does not offer a newly discovered return spell. Keep the scene’s audience distinct from its participants: the player witnessed this exchange before Tessa’s confrontation with Senn.", detail='Uncertainty existed before Tessa was brought here; it was not a new complication that appeared afterward.'),
        'hearing': dict(round=2, title='What the hearing changes', source='Observed · council room and corridor', body="At the hearing the deception is confronted. Tessa leaves the mantle behind. Confinement ends, but Elin loses access and Senn retains the original book. These are different outcomes; the hearing does not hand Tessa the means to return.\n\nOutside, Mara acknowledges knowing that Tessa wanted to leave. A change in the orders does not erase the role Mara played in keeping her confined. The injury to their relationship remains part of the scene rather than becoming another problem solved by the hearing.", detail='Freedom of movement, access to the book, and a way home are three separate questions.'),
        'portrait': dict(round=3, title='A search made possible', source='Observed · Gray Scar and the river camp', body="After the mixed group escapes Gray Scar, Tessa gives Lucan a portrait of Orren and Hest’s address. The portrait helps connect a missing person to a specific family. Lucan still has to find someone inside a system that keeps people moving.\n\nWhen Orren is reunited with his family, the result is real. It does not establish that Lucan controls every prison, transport order or labor detachment. The apprentice remains a separate person to search for, not an item automatically covered by Orren’s release.", detail='A useful introduction and a successful search do not amount to unrestricted authority.'),
        'launch': dict(round=3, title='Loan, return, ownership', source='Observed · successive river visits', body="Lucan’s launch has several distinct states. It is lent, returned, used for travel and later offered in a bargain over the missing apprentice. Keep those acts separate. Borrowing a craft for a journey does not transfer ownership of it.\n\nRiver access carries costs in crew, transport and leverage. Lucan’s rank cannot simply make those costs disappear. His later offer gives up something he can actually offer; it is not proof that he could have ordered every desired release all along.", detail='Track who has use of the boat, who owns it, and what is offered in the final exchange.'),
        'grain': dict(round=3, title='Pressure at the grain wharf', source='Observed · autumn grain negotiations', body="Crews refuse, grain creates pressure, and the delay lasts three days. The eventual exchange order is a specific result of that pressure. It does not abolish the military’s other interests or return every missing person at once.\n\nMedical treatment, transport, labor and release are connected by the river, but they are not the same negotiation. Cooperation becomes possible through concrete promises and costs. A friendly conversation alone has not made the war’s institutions harmless.", detail='Limited success is still success. Its limits remain visible in what must be negotiated next.'),
        'inspection': dict(round=4, title='The inspection before Harrow', source='Observed · covered bridge', body="The bridge housings and tool wagons are inspected before the exchange. Lucan promises to remain beside Orren’s cart. The return of families is anticipated as something worth bringing the children to see.\n\nA genuine inspection at one time cannot certify that cargo stays untouched afterward. To understand the failure, compare this encounter with the later cargo shed rather than assuming the original inspection must have been a sham.", detail='The important question is what changes after clearance, and who can authorize that change.'),
        'order': dict(round=4, title='The order the player witnessed', source='Observed · Valcair and Vask, without Tessa or Lucan', body="Valcair orders the sabotage. Vask knowingly agrees. The timing is set for four o’clock, and a recall is intended to remove Lucan from danger. This is information the player receives directly in a scene outside Tessa’s viewpoint.\n\nThe recall offers selective protection to one person while returning families remain exposed. It does not make the order an accident or erase responsibility for the people on the bridge. Lucan’s relationship to Valcair also does not prove that Lucan heard this private order.", detail='This inquiry reconstructs an atrocity already shown to the player. Its author is not an undisclosed suspect.'),
        'cargo': dict(round=4, title='New seals, the same axles', source='Observed · cargo shed and stores inquiry', body="Marren is excluded from the cargo work. Seals are cut; charges are concealed behind southern plates. The old axles remain in place and a false clearance is countersigned. Later, Lucan questions an axle explanation that does not fit what was done.\n\nThese observations connect the sabotage to altered cargo and misleading records. Marren’s signature will matter, but signing a clearance does not let him see the contents of work from which he was excluded.", detail='Separate the physical alteration, the signature and the later explanation. They are not interchangeable evidence.'),
        'aftermath': dict(round=4, title='The account that travels afterward', source='Observed · south bank, relief camp and northern town', body="Tessa sees the recall after the collapse. She has lost Iven and rejects Lucan’s touch. Mara sets a boundary around contact. The player’s view of events does not oblige Tessa to share the player’s certainty or forgive someone on command.\n\nLater, a public account recasts the catastrophe. Recruitment follows, including a son wearing his dead father’s coat. A northern family’s loss is real even when the account used to direct their anger is false.", detail='People can be harmed by the atrocity and then used again by the explanation offered for it.'),
        'marren': dict(round=5, title='A signature and a limited witness', source='Observed · examination tent', body="Marren testifies to his signature and to what he could observe. Tessa questions him; the testimony is written and signed. He remains culpable for what he signed without becoming an all-seeing witness to what happened beyond his sight.\n\nHis account supports parts of the chain. It cannot, by itself, prove every hidden decision or Lucan’s state of mind. The player can compare it with earlier cutaways; the cast cannot treat those unseen scenes as evidence they possess.", detail='Ask what Marren saw, what he did, and what somebody else would have to establish.'),
        'plans': dict(round=5, title='Two plans, not one certainty', source='Observed · command tent', body="Lucan’s plan and Olan’s exterior sketch are compared. Olan supplies a correction. Changed watches matter, and Tessa questions whether the release mechanism will work as claimed.\n\nThe plan concerns entry and the entrance ward. It is not a guarantee that Valcair’s defenses will vanish. The scene deliberately keeps useful cooperation and remaining uncertainty together. The player’s investigation does not secretly give the assault party a perfect map.", detail='A corrected route can improve a plan without verifying every mechanism inside the hall.'),
        'letter': dict(round=5, title='The letter is separate', source='Observed · delivery and examination tent', body="Lucan sends a personal letter separately from the plan and witness material. Tessa opens it after questioning Marren. The screenplay does not disclose its complete text.\n\nIt would be tempting to turn that private page into a hidden confession or proof of forgiveness. Neither follows from what is shown. The reader can respect the letter’s existence without supplying words Tessa was never written as reading.", detail='The personal letter, the military plan and the signed testimony have different purposes.'),
        'h_first': dict(round=2, title='There was an earlier summoning', source='Historical context · presented to the reader', body="Tessa is not the first summoned Saint. The first Saint summoning belongs to the deeper history of the conflict, before the events you are following. Distinguishing those events prevents a basic error: Tessa’s arrival did not start the ancient war.\n\nThis is historical context available to you, not a newly legible passage in Elin’s damaged book. The first Saint’s identity, consent and personal motives are not established by knowing that a human institution summoned someone.", detail='A later summoned person cannot inherit personal responsibility for the decisions that produced an earlier summoning.'),
        'h_memory': dict(round=3, title='What a later account can hide', source='Historical context · presented to the reader', body="Humanity’s part in the ancient conflict was later forgotten, obscured or recast. An institution’s familiar account can therefore begin too late, leaving out the action that made its opponents respond.\n\nThe present suffering of human civilians is not imaginary. But evidence of present suffering alone cannot establish who acted first in a much older conflict. Compare the time each claim describes before treating one as a complete account of the other.", detail='Who is suffering now and who initiated a conflict are different historical questions.'),
        'h_distrust': dict(round=4, title='History and Valcair’s choice', source='Historical context, compared with witnessed events', body="Valcair’s distrust is rooted in the history obscured by the human account. He treats future institutions and successors as a threat even when his son has reasons to trust particular people.\n\nThe player has also watched Valcair choose Harrow and Vask knowingly participate. An older grievance can help explain distrust without making those decisions inevitable or excusable. Nor does Valcair’s connection to that history prove that he personally witnessed every ancient event.", detail='Explanation is not absolution. Contemporary responsibility remains visible in contemporary choices.'),
        'h_origin': dict(round=5, title='The first Saint and the initiating act', source='Historical context · established underlying history', body="Humans initiated the ancient war through the first Saint summoning. The later human account forgot, obscured or recast that initiating aggression. The summoning was part of the origin of the conflict; it was not merely a later response to an already established ancient northern attack.\n\nThat establishes institutional human responsibility for the beginning. It does not establish the first Saint’s willing participation, a specific first battlefield operation, or collective guilt for every human born afterward. Tessa’s much later abduction remains an act done to her.\n\nYou can know this while Tessa, Iven, Mara, Elin and Lucan do not. Nothing in this inquiry inserts the discovery into their conversations or gives them another plan.", detail='The reliable finding is specific: human initiation through the first Saint summoning. Motives and acts not established here remain open.')
    }

    cases = {
        'limits': dict(round=1, title='Promises and limits', question='Which conclusion is supported by what you have seen?', evidence=['phone', 'promise', 'olan', 'public_role'], options=['The light can undo any injury if Tessa tries hard enough.', 'The curse can be removed; regrowth and a route home have not been demonstrated.', 'Olan’s treatment proves Senn can send Tessa home.'], answer=1, finding='Purification, healing and replacing lost tissue are different capabilities. Olan’s curse clears; his fingers do not return. Senn’s assurance of a way home is still a promise, not a demonstrated procedure.', limit='This round does not yet establish why Senn made the promise.', hint='Compare what changes in Olan’s arm with what remains missing. Then look for an actual return procedure, rather than an assurance.'),
        'return': dict(round=2, title='What was known?', question='What do the admission and the damaged book establish together?', evidence=['cut_pages', 'scholar', 'hearing'], options=['A return route was uncertain when the promise was made; the missing text does not prove a solution.', 'The four pages certainly contained a working return spell.', 'The hearing gives Tessa the original book and a way home.'], answer=0, finding='The return promise exceeded what was known at the summoning. The original is incomplete; the hearing changes confinement without delivering a return method or unrestricted access to the book.', limit='Who cut the pages, what they contained and whether Tessa can return remain unresolved.', hint='The scholar’s admission establishes earlier uncertainty. Four missing pages establish absence, not their contents.'),
        'river': dict(round=3, title='The cost of cooperation', question='What connects the search, launch and grain negotiations?', evidence=['portrait', 'launch', 'grain'], options=['Lucan can order any release because of his rank.', 'Borrowing the launch transfers ownership to its passengers.', 'Each success depends on particular access, promises and costs.'], answer=2, finding='Cooperation produces real results through specific commitments. Portraits help identify people, boats make journeys possible, and grain creates pressure. None grants unrestricted control over the whole system.', limit='Finding Orren does not automatically find the apprentice or end captivity elsewhere.', hint='Compare what Lucan can offer himself with what other people still control.'),
        'harrow': dict(round=4, title='Harrow: event and account', question='Which reconstruction fits the complete sequence?', evidence=['inspection', 'order', 'cargo', 'aftermath'], options=['A genuine inspection is bypassed later; sabotage is ordered and then concealed by another account.', 'The original inspection proves no later cargo alteration was possible.', 'The recall proves Lucan agreed to the sabotage.'], answer=0, finding='Valcair and Vask arrange the sabotage after a genuine inspection. Altered cargo and false clearance bypass it. The recall selectively protects Lucan; the later public account redirects grief toward continued war.', limit='Player knowledge does not restore Tessa’s trust. Marren has not become an omniscient witness.', hint='Put the bridge inspection before the cargo shed. Then separate the private order from what Lucan and Tessa actually see.'),
        'witness': dict(round=5, title='What can be relied on?', question='What can the assault party responsibly take from the material?', evidence=['marren', 'plans', 'letter'], options=['The personal letter proves that trust has been repaired.', 'A limited signed account and a corrected but imperfect plan.', 'Marren’s signature proves every unseen decision.'], answer=1, finding='Marren can attest to his acts and observations. The two plans can be compared and corrected without making the release certain. The personal letter remains separate from that evidentiary work.', limit='This does not provide a way to avert the original ending or reveal the unwritten contents of the letter.', hint='For each item, ask who made it, what they could know, and what the item is meant to do.'),
        'origin': dict(round=2, resolve_round=5, title='Before this war', question='Which account of the ancient origin is supported?', evidence=['h_first', 'h_memory', 'h_distrust', 'h_origin'], options=['Tessa’s arrival began the ancient conflict.', 'An old grievance makes the decisions at Harrow unavoidable.', 'Humans initiated it through the first Saint summoning; that does not establish the summoned person’s consent.'], answer=2, finding='Humans began the ancient war through the first Saint summoning. The later human account obscured that origin. Tessa is a later summoned person, not its initiator. Historical aggression explains part of Valcair’s distrust without excusing his choices at Harrow.', limit='The first Saint’s identity and agency, the precise initiating operation, and Valcair’s firsthand experience are not established here. This finding belongs to the player alone.', hint='Separate the first summoning from Tessa’s, and institutional initiation from an abducted person’s willing participation.')
    }

    def available_cases():
        return [key for key, case in cases.items() if case['round'] <= unlocked_round]

    def readable_evidence(case_id):
        return [eid for eid in cases[case_id]['evidence'] if evidence[eid]['round'] <= unlocked_round]

    def case_ready(case_id):
        case = cases[case_id]
        return unlocked_round >= case.get('resolve_round', case['round']) and all(eid in viewed_evidence for eid in case['evidence'])
