(gimp-context-push)
(let* ((img (car (gimp-file-load RUN-NONINTERACTIVE "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch7-gray-scar/s021-lucan-returns/source.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch7-gray-scar/s021-lucan-returns/source.png"))))
(gimp-item-set-name (car (gimp-image-get-active-layer img)) "Current source — protected base")
(let* ((ly (car (gimp-file-load-layer RUN-NONINTERACTIVE img "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch7-gray-scar/s021-lucan-returns/adult-litter-donor.png"))) (mask 0))
(gimp-image-insert-layer img ly 0 0)
(gimp-item-set-name ly "Same adult woman and full-length litter at return beat")
(gimp-layer-scale ly 521 439 TRUE)
(gimp-layer-set-offsets ly 349 190)
(set! mask (car (gimp-layer-create-mask ly ADD-BLACK-MASK)))
(gimp-layer-add-mask ly mask)
(gimp-image-select-polygon img CHANNEL-OP-REPLACE 40 (vector 447 329 467 326 490 331 509 333 529 341 549 349 565 356 585 362 602 369 609 381 604 393 592 397 574 395 551 391 529 387 507 385 485 383 462 380 451 373 448 357))
(gimp-selection-feather img 1.5)
(gimp-context-set-foreground "white")
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none img)
)
(gimp-xcf-save RUN-NONINTERACTIVE img (car (gimp-image-get-active-layer img)) "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch7-gray-scar/s021-lucan-returns/master.xcf" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch7-gray-scar/s021-lucan-returns/master.xcf")
(let* ((dup (car (gimp-image-duplicate img))) (flat (car (gimp-image-merge-visible-layers dup CLIP-TO-IMAGE))))
(file-png-save RUN-NONINTERACTIVE dup flat "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch7-gray-scar/s021-lucan-returns/candidate.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch7-gray-scar/s021-lucan-returns/candidate.png" 0 9 0 0 0 0 0)
(gimp-image-delete dup))
(gimp-image-delete img))
(let* ((re (car (gimp-file-load RUN-NONINTERACTIVE "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch7-gray-scar/s021-lucan-returns/master.xcf" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch7-gray-scar/s021-lucan-returns/master.xcf"))) (flat (car (gimp-image-merge-visible-layers re CLIP-TO-IMAGE))))
(file-png-save RUN-NONINTERACTIVE re flat "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch7-gray-scar/s021-lucan-returns/reopened.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch7-gray-scar/s021-lucan-returns/reopened.png" 0 9 0 0 0 0 0)
(gimp-image-delete re))
(gimp-context-pop)
(gimp-quit 0)
