(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/s056-hand/contact-local-master.xcf" "local contact master"))) (layers (cadr (gimp-image-get-layers im))) (margin (vector-ref layers 1)) (left 0) (mask 0) (flat 0) (patch 0) (sun 0) (disk 0) (bottom 0))
(set! left (car (gimp-file-load-layer RUN-NONINTERACTIVE im "visual-novel/art/scene-studies/s056-hand/left-perimeter-source.png")))
(gimp-image-insert-layer im left 0 2)
(gimp-item-set-name left "Only left window and empty table continuation used")
(set! mask (car (gimp-layer-create-mask margin ADD-BLACK-MASK)))
(gimp-layer-add-mask margin mask)
(gimp-image-select-rectangle im CHANNEL-OP-REPLACE 360 0 1320 941)
(gimp-selection-feather im 6)
(gimp-edit-fill mask WHITE-FILL)
(gimp-selection-none im)
(gimp-image-select-rectangle im CHANNEL-OP-REPLACE 280 610 355 190)
(gimp-selection-feather im 10)
(gimp-context-set-foreground '(0 0 0))
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none im)
; Bounded coat replacement, canonical twelve rays, original metallic center.
(set! patch (car (gimp-file-load-layer RUN-NONINTERACTIVE im "visual-novel/art/scene-studies/s056-hand/pre-emblem-composite.png")))
(gimp-image-insert-layer im patch 0 0)
(gimp-layer-resize patch 70 62 -1407 -481)
(gimp-layer-set-offsets patch 1407 415)
(gimp-item-set-name patch "Coat-only removal of extra generated sun rays")
(set! mask (car (gimp-layer-create-mask patch ADD-BLACK-MASK)))
(gimp-layer-add-mask patch mask)
(gimp-image-select-ellipse im CHANNEL-OP-REPLACE 1410 419 65 55)
(gimp-selection-feather im 4)
(gimp-edit-fill mask WHITE-FILL)
(gimp-selection-none im)
(set! sun (car (gimp-file-load-layer RUN-NONINTERACTIVE im "visual-novel/art/prop-keys/emblems/human-temple-sun.png")))
(gimp-image-insert-layer im sun 0 0)
(gimp-layer-resize sun 295 320 -109 -96)
(gimp-context-set-interpolation INTERPOLATION-NOHALO)
(gimp-layer-scale sun 46 50 TRUE)
(gimp-layer-set-offsets sun 1419 419)
(gimp-item-set-name sun "Fixed twelve-ray temple sun geometry")
(set! disk (car (gimp-file-load-layer RUN-NONINTERACTIVE im "visual-novel/art/scene-studies/s056-hand/pre-emblem-composite.png")))
(gimp-image-insert-layer im disk 0 0)
(gimp-item-set-name disk "Original lit brass center retained inside canonical rays")
(set! mask (car (gimp-layer-create-mask disk ADD-BLACK-MASK)))
(gimp-layer-add-mask disk mask)
(gimp-image-select-ellipse im CHANNEL-OP-REPLACE 1431 433 22 21)
(gimp-selection-feather im 0.75)
(gimp-edit-fill mask WHITE-FILL)
(gimp-selection-none im)
; Shift the complete composition, never a body region. Continue only 13px of quiet bottom cloth.
(set! bottom (car (gimp-file-load-layer RUN-NONINTERACTIVE im "visual-novel/art/scene-studies/s056-hand/pre-emblem-composite.png")))
(gimp-image-insert-layer im bottom 0 0)
(gimp-layer-resize bottom 1672 14 0 -927)
(gimp-layer-set-offsets bottom 0 941)
(gimp-item-set-name bottom "Thirteen-pixel lower drapery continuation for whole-frame lift")
(gimp-image-resize im 1672 941 0 -13)
(gimp-xcf-save RUN-NONINTERACTIVE im left "visual-novel/art/scene-studies/s056-hand/hand-examination-master.xcf" "hand-examination-master.xcf")
(set! flat (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save RUN-NONINTERACTIVE im flat "/tmp/s056-key-native.png" "/tmp/s056-key-native.png" 0 9 0 0 0 0 0)
(gimp-context-set-interpolation INTERPOLATION-NOHALO)
(gimp-image-scale im 1920 1080)
(set! flat (car (gimp-image-get-active-layer im)))
(file-png-save RUN-NONINTERACTIVE im flat "/tmp/s056-key-final-candidate.png" "/tmp/s056-key-final-candidate.png" 0 9 0 0 0 0 0)
(gimp-image-delete im))
(gimp-quit 0)
