(let* ((im (car (gimp-image-new 1672 941 RGB))) (bg (car (gimp-layer-new im 1672 941 RGB-IMAGE "Left perimeter guide" 100 NORMAL-MODE))) (margin 0) (src 0) (mask 0) (flat 0))
(gimp-image-insert-layer im bg 0 -1)
(gimp-context-set-background '(112 112 112))
(gimp-drawable-fill bg BACKGROUND-FILL)
(set! margin (car (gimp-file-load-layer RUN-NONINTERACTIVE im "visual-novel/art/scene-studies/s056-hand/perimeter-source.png")))
(gimp-image-insert-layer im margin 0 -1)
(gimp-layer-resize margin 1320 941 0 0)
(gimp-layer-set-offsets margin 352 0)
(gimp-item-set-name margin "Limited upper/lower margins; rejected right-head region excluded")
(set! src (car (gimp-file-load-layer RUN-NONINTERACTIVE im "visual-novel/art/scene-studies/s056-hand/generation-initial.png")))
(gimp-image-insert-layer im src 0 -1)
(gimp-context-set-interpolation INTERPOLATION-NOHALO)
(gimp-layer-scale src 1306 735 TRUE)
(gimp-layer-set-offsets src 536 107)
(gimp-item-set-name src "Original close contact and two faces; lamp enters from right")
(set! mask (car (gimp-layer-create-mask src ADD-BLACK-MASK)))
(gimp-layer-add-mask src mask)
(gimp-image-select-rectangle im CHANNEL-OP-REPLACE 541 114 1288 720)
(gimp-selection-feather im 8)
(gimp-edit-fill mask WHITE-FILL)
(gimp-selection-none im)
(gimp-image-select-rectangle im CHANNEL-OP-REPLACE 0 625 920 316)
(gimp-selection-feather im 10)
(gimp-context-set-foreground '(0 0 0))
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none im)
(gimp-xcf-save RUN-NONINTERACTIVE im src "visual-novel/art/scene-studies/s056-hand/contact-local-master.xcf" "contact-local-master.xcf")
(set! flat (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save RUN-NONINTERACTIVE im flat "/tmp/s056-key-left-guide.png" "/tmp/s056-key-left-guide.png" 0 9 0 0 0 0 0)
(gimp-image-delete im))
(gimp-quit 0)
