(let* ((im (car (gimp-image-new 2144 1206 RGB))) (bg (car (gimp-layer-new im 2144 1206 RGB-IMAGE "Quiet perimeter guide" 100 NORMAL-MODE))) (src 0) (flat 0))
(gimp-image-insert-layer im bg 0 -1)
(gimp-context-set-background '(112 112 112))
(gimp-drawable-fill bg BACKGROUND-FILL)
(set! src (car (gimp-file-load-layer RUN-NONINTERACTIVE im "visual-novel/art/scene-studies/s056-hand/generation-initial.png")))
(gimp-image-insert-layer im src 0 -1)
(gimp-layer-set-offsets src 236 140)
(set! flat (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save RUN-NONINTERACTIVE im flat "/tmp/s056-key-margin-guide.png" "/tmp/s056-key-margin-guide.png" 0 9 0 0 0 0 0)
(gimp-image-delete im))
(gimp-quit 0)
