(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/s056-hand/hand-examination-master.xcf" "master"))) (flat (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE))))
(file-png-save RUN-NONINTERACTIVE im flat "/tmp/s056-key-native-reopened.png" "/tmp/s056-key-native-reopened.png" 0 9 0 0 0 0 0)
(gimp-context-set-interpolation INTERPOLATION-NOHALO)
(gimp-image-scale im 1920 1080)
(set! flat (car (gimp-image-get-active-layer im)))
(file-png-save RUN-NONINTERACTIVE im flat "/tmp/s056-key-final-reopened.png" "/tmp/s056-key-final-reopened.png" 0 9 0 0 0 0 0)
(gimp-image-delete im))
(gimp-quit 0)
