(let* ((dir "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/s054-duel/batch6-grip-rebuild") (im (car (gimp-file-load RUN-NONINTERACTIVE (string-append dir "/blockout-led-candidate.png") (string-append dir "/blockout-led-candidate.png")))) (ly (car (gimp-file-load-layer RUN-NONINTERACTIVE im (string-append dir "/underhand-donor.png")))) (mask 0))
(gimp-item-set-name (car (gimp-image-get-active-layer im)) "Fresh coherent full scene and weapon path")
(gimp-image-insert-layer im ly 0 0) (gimp-layer-scale ly 240 165 TRUE) (gimp-layer-set-offsets ly 595 120) (gimp-item-set-name ly "Valcair left supinated supporting forearm and secure spear grip")
(set! mask (car (gimp-layer-create-mask ly ADD-BLACK-MASK))) (gimp-layer-add-mask ly mask)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 28 #(599 170 627 158 647 158 679 172 717 178 752 186 771 196 776 223 769 244 743 247 721 237 683 237 633 228 599 224))
(gimp-selection-feather im 3) (gimp-context-set-foreground '(255 255 255)) (gimp-edit-fill mask FOREGROUND-FILL) (gimp-selection-none im)
(gimp-xcf-save RUN-NONINTERACTIVE im ly (string-append dir "/repair-master.xcf") (string-append dir "/repair-master.xcf"))
(let ((out (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))) (file-png-save2 RUN-NONINTERACTIVE im out (string-append dir "/candidate.png") (string-append dir "/candidate.png") 0 9 0 0 0 0 0 0 0)) (gimp-image-delete im))
(gimp-quit 0)
