(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "/home/kir/.codex/generated_images/01a0cf96-3dfc-7501-b20b-81a2b39d7ac6/exec-8c13bdcc-d587-412a-8fd7-ceebe9c2693e.png" "/home/kir/.codex/generated_images/01a0cf96-3dfc-7501-b20b-81a2b39d7ac6/exec-8c13bdcc-d587-412a-8fd7-ceebe9c2693e.png")))
(base (car (gimp-image-get-active-layer im))) (edit 0) (mask 0) (clean 0) (hanging 0) (horn 0) (star 0) (flat 0))
(gimp-item-set-name base "Reviewed extended room — natural adults and supported issuing counter")
(set! edit (car (gimp-file-load-layer RUN-NONINTERACTIVE im "/home/kir/.codex/generated_images/01a0cf96-3dfc-7501-b20b-81a2b39d7ac6/exec-a36ff0b6-55ce-40ff-ae8a-373f33cffa54.png")))
(gimp-image-insert-layer im edit 0 -1)
(gimp-item-set-name edit "Only left-facing Vask head and two circled cargo rows")
(set! mask (car (gimp-layer-create-mask edit ADD-BLACK-MASK)))
(gimp-layer-add-mask edit mask)
(gimp-image-select-rectangle im CHANNEL-OP-REPLACE 1098 96 140 147)
(gimp-selection-feather im 3)
(gimp-edit-fill mask WHITE-FILL)
(gimp-selection-none im)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 8 #(622 421 765 420 839 440 695 466))
(gimp-selection-feather im 1.5)
(gimp-edit-fill mask WHITE-FILL)
(gimp-selection-none im)
(set! clean (car (gimp-layer-new im 1672 941 RGBA-IMAGE "Local emblem cloth and unmarked office hanging" 100 NORMAL-MODE)))
(gimp-image-insert-layer im clean 0 -1)
(gimp-context-set-brush "2. Hardness 075")
(gimp-context-set-brush-size 34)
(gimp-clone clean base CLONE-IMAGE 535 292 2 #(512 270))
(gimp-image-select-rectangle im CHANNEL-OP-REPLACE 1203 243 23 25)
(gimp-selection-feather im 0.7)
(gimp-context-set-brush-size 42)
(gimp-clone clean base CLONE-IMAGE 1244 257 2 #(1214 257))
(gimp-selection-none im)
(set! hanging (car (gimp-layer-new-from-drawable base im)))
(gimp-image-insert-layer im hanging 0 -1)
(gimp-item-set-name hanging "Plain office hanging — remove invented rank display using its own unmarked cloth")
(gimp-layer-resize hanging 48 10 -1340 -184)
(gimp-context-set-interpolation INTERPOLATION-NOHALO)
(gimp-layer-scale hanging 59 120 TRUE)
(gimp-layer-set-offsets hanging 1335 116)
(set! mask (car (gimp-layer-create-mask hanging ADD-BLACK-MASK)))
(gimp-layer-add-mask hanging mask)
(gimp-image-select-rectangle im CHANNEL-OP-REPLACE 1337 119 55 115)
(gimp-selection-feather im 3)
(gimp-edit-fill mask WHITE-FILL)
(gimp-selection-none im)
(set! horn (car (gimp-layer-new-from-drawable base im)))
(gimp-image-insert-layer im horn 0 -1)
(gimp-item-set-name horn "Small rounded near horn for subordinate northern officer")
(set! mask (car (gimp-layer-create-mask horn ADD-BLACK-MASK)))
(gimp-layer-add-mask horn mask)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 16 #(724 156 729 156 734 164 732 172 726 173 722 168 721 163 722 159))
(gimp-selection-feather im 0.8)
(gimp-edit-fill mask WHITE-FILL)
(gimp-selection-none im)
(gimp-context-set-interpolation INTERPOLATION-NOHALO)
(gimp-item-transform-matrix horn 0.6 0 893.2 0 0.6 154.6 0 0 1)
(set! star (car (gimp-file-load-layer RUN-NONINTERACTIVE im "visual-novel/art/prop-keys/emblems/northern-split-star.png")))
(gimp-image-insert-layer im star 0 -1)
(gimp-item-set-name star "Lucan canonical split eight-point star")
(gimp-layer-scale star 34 34 TRUE)
(gimp-layer-set-offsets star 495 253)
(gimp-layer-set-opacity star 88)
(set! star (car (gimp-file-load-layer RUN-NONINTERACTIVE im "visual-novel/art/prop-keys/emblems/northern-split-star.png")))
(gimp-image-insert-layer im star 0 -1)
(gimp-item-set-name star "Vask canonical split star above original three bars")
(gimp-layer-scale star 30 30 TRUE)
(gimp-layer-set-offsets star 1199 243)
(gimp-layer-set-opacity star 86)
(gimp-xcf-save RUN-NONINTERACTIVE im star "visual-novel/art/scene-studies/s038-northern-stores-office/office-local-master.xcf" "visual-novel/art/scene-studies/s038-northern-stores-office/office-local-master.xcf")
(set! flat (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save RUN-NONINTERACTIVE im flat "/tmp/s038-finish-native.png" "/tmp/s038-finish-native.png" 0 9 0 0 0 0 0)
(gimp-image-crop im 1664 936 4 2)
(gimp-image-scale im 1920 1080)
(set! flat (car (gimp-image-get-active-layer im)))
(file-png-save RUN-NONINTERACTIVE im flat "/tmp/s038-final-review.png" "/tmp/s038-final-review.png" 0 9 0 0 0 0 0)
(gimp-image-delete im))
(gimp-quit 0)
