(define (source-delivery path)
 (let* ((im (car (gimp-file-load RUN-NONINTERACTIVE path path))) (flat (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE))))
 (gimp-context-set-interpolation INTERPOLATION-NOHALO)
 (gimp-image-crop im 1664 936 4 2) (gimp-image-scale im 1920 1080) im))
(define (horn im name points tx ty)
 (let* ((l (car (gimp-file-load-layer RUN-NONINTERACTIVE im "visual-novel/renpy/game/art/portraits/marren-speaking.png"))) (m 0))
  (gimp-image-insert-layer im l 0 -1) (gimp-item-set-name l name)
  (set! m (car (gimp-layer-create-mask l ADD-BLACK-MASK))) (gimp-layer-add-mask l m)
  (gimp-image-select-polygon im CHANNEL-OP-REPLACE (vector-length points) points)
  (gimp-selection-feather im 1.2) (gimp-edit-fill m WHITE-FILL) (gimp-selection-none im)
  (gimp-context-set-interpolation INTERPOLATION-NOHALO)
  (gimp-item-transform-matrix l 0.22 0 tx 0 0.22 ty 0 0 1) l))
(let* ((im (source-delivery "visual-novel/art/scene-studies/s038-northern-stores-office/office-local-master.xcf"))
 (base (car (gimp-image-get-active-layer im))) (l 0) (flat 0))
(gimp-item-set-name base "Delivered office before requested readable Marren horns correction")
(set! l (horn im "Marren near rounded horn from current portrait; native uniform scale" #(479 262 473 271 468 285 466 301 470 316 481 329 503 341 518 336 520 323 510 306 496 291 488 272) 728.78 123.86))
(set! l (horn im "Marren far rounded horn from same portrait; slight foreshortening preserved" #(816 278 825 261 834 268 842 285 843 306 832 324 824 326 820 306) 721.1 126.3))
(gimp-xcf-save RUN-NONINTERACTIVE im l "visual-novel/art/scene-studies/s038-northern-stores-office/office-horns-correction-master.xcf" "visual-novel/art/scene-studies/s038-northern-stores-office/office-horns-correction-master.xcf")
(set! flat (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save RUN-NONINTERACTIVE im flat "/tmp/s038-horns-candidate.png" "/tmp/s038-horns-candidate.png" 0 9 0 0 0 0 0)
(gimp-image-delete im)) (gimp-quit 0)
