(let* ((im(car(gimp-file-load RUN-NONINTERACTIVE "visual-novel/renpy/game/art/scenes/s042-cart.png" "visual-novel/renpy/game/art/scenes/s042-cart.png")))(l 0))
(gimp-image-crop im 44 46 315 318)(set! l(car(gimp-image-get-active-layer im)))
(file-png-save RUN-NONINTERACTIVE im l "visual-novel/art/scene-studies/batch6-optional-emblems/twelve-ray-shield-component.png" "visual-novel/art/scene-studies/batch6-optional-emblems/twelve-ray-shield-component.png" 0 9 0 0 0 0 0)(gimp-image-delete im))
(let* ((im(car(gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/batch6-optional-emblems/s042-mill-town-later/before.png" "visual-novel/art/scene-studies/batch6-optional-emblems/s042-mill-town-later/before.png")))(l 0)(m 0)(f 0))
(set! l(car(gimp-file-load-layer RUN-NONINTERACTIVE im "visual-novel/art/scene-studies/batch6-optional-emblems/twelve-ray-shield-component.png")))
(gimp-image-insert-layer im l 0 0)(gimp-layer-set-offsets l 337 308)(gimp-item-set-name l "Matching twelve-ray disk from current S042 cart shield")
(set! m(car(gimp-layer-create-mask l ADD-BLACK-MASK)))(gimp-layer-add-mask l m)
(gimp-image-select-ellipse im CHANNEL-OP-REPLACE 338 309 42 44)(gimp-selection-feather im 3)(gimp-edit-fill m WHITE-FILL)(gimp-selection-none im)
(gimp-xcf-save RUN-NONINTERACTIVE im l "visual-novel/art/scene-studies/batch6-optional-emblems/s042-mill-town-later/repair-master.xcf" "visual-novel/art/scene-studies/batch6-optional-emblems/s042-mill-town-later/repair-master.xcf")
(set! f(car(gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save RUN-NONINTERACTIVE im f "visual-novel/art/scene-studies/batch6-optional-emblems/s042-mill-town-later/candidate.png" "visual-novel/art/scene-studies/batch6-optional-emblems/s042-mill-town-later/candidate.png" 0 9 0 0 0 0 0)(gimp-image-delete im))
(let* ((im(car(gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/batch6-optional-emblems/s042-mara-hand/before.png" "visual-novel/art/scene-studies/batch6-optional-emblems/s042-mara-hand/before.png")))(l 0)(m 0)(f 0))
(set! l(car(gimp-file-load-layer RUN-NONINTERACTIVE im "visual-novel/art/scene-studies/batch6-optional-emblems/twelve-ray-shield-component.png")))
(gimp-image-insert-layer im l 0 0)(gimp-layer-set-offsets l 333 275)(gimp-item-set-name l "Matching twelve-ray disk from current S042 cart shield")
(set! m(car(gimp-layer-create-mask l ADD-BLACK-MASK)))(gimp-layer-add-mask l m)
(gimp-image-select-ellipse im CHANNEL-OP-REPLACE 334 276 42 44)(gimp-selection-feather im 3)(gimp-edit-fill m WHITE-FILL)(gimp-selection-none im)
(gimp-xcf-save RUN-NONINTERACTIVE im l "visual-novel/art/scene-studies/batch6-optional-emblems/s042-mara-hand/repair-master.xcf" "visual-novel/art/scene-studies/batch6-optional-emblems/s042-mara-hand/repair-master.xcf")
(set! f(car(gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save RUN-NONINTERACTIVE im f "visual-novel/art/scene-studies/batch6-optional-emblems/s042-mara-hand/candidate.png" "visual-novel/art/scene-studies/batch6-optional-emblems/s042-mara-hand/candidate.png" 0 9 0 0 0 0 0)(gimp-image-delete im))
(gimp-quit 0)