(let* ((im(car(gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/batch6-optional-emblems/s044-upper-stores-landing/before.png" "visual-novel/art/scene-studies/batch6-optional-emblems/s044-upper-stores-landing/before.png")))(l 0)(f 0))
(set! l(car(gimp-layer-new im 1920 1080 RGBA-IMAGE "White principal star points; center split preserved" 100 NORMAL-MODE)))
(gimp-image-insert-layer im l 0 0)(gimp-drawable-fill l TRANSPARENT-FILL)
(gimp-context-set-foreground '(215 214 203))
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 6 #(881.4 184.5 881.4 194 878.2 191))(gimp-edit-fill l FOREGROUND-FILL)(gimp-selection-none im)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 6 #(882.6 184.5 886 191 882.6 194))(gimp-edit-fill l FOREGROUND-FILL)(gimp-selection-none im)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 6 #(881.4 194 881.4 203.5 878.2 197.5))(gimp-edit-fill l FOREGROUND-FILL)(gimp-selection-none im)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 6 #(882.6 194 886 197.5 882.6 203.5))(gimp-edit-fill l FOREGROUND-FILL)(gimp-selection-none im)
(gimp-xcf-save RUN-NONINTERACTIVE im l "visual-novel/art/scene-studies/batch6-optional-emblems/s044-upper-stores-landing/repair-master.xcf" "visual-novel/art/scene-studies/batch6-optional-emblems/s044-upper-stores-landing/repair-master.xcf")
(set! f(car(gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save RUN-NONINTERACTIVE im f "visual-novel/art/scene-studies/batch6-optional-emblems/s044-upper-stores-landing/candidate.png" "visual-novel/art/scene-studies/batch6-optional-emblems/s044-upper-stores-landing/candidate.png" 0 9 0 0 0 0 0)
(gimp-image-delete im))
(let* ((im(car(gimp-file-load RUN-NONINTERACTIVE "visual-novel/renpy/game/art/scenes/s042-cart.png" "visual-novel/renpy/game/art/scenes/s042-cart.png")))(l 0))
(gimp-image-crop im 84 120 310 285)(set! l(car(gimp-image-get-active-layer im)))
(file-png-save RUN-NONINTERACTIVE im l "visual-novel/art/scene-studies/batch6-optional-emblems/s042-cart-shield-reference.png" "visual-novel/art/scene-studies/batch6-optional-emblems/s042-cart-shield-reference.png" 0 9 0 0 0 0 0)
(gimp-image-delete im))(gimp-quit 0)