(let* ((im(car(gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/batch6-gray-scar/new-moments/s018-cats-master.xcf" "visual-novel/art/scene-studies/batch6-gray-scar/new-moments/s018-cats-master.xcf")))(f 0))
(gimp-message (string-append "s018-cats layers=" (number->string (car(gimp-image-get-layers im)))))
(set! f(car(gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save RUN-NONINTERACTIVE im f "/tmp/batch6-new-s018-cats-reopened.png" "/tmp/batch6-new-s018-cats-reopened.png" 0 9 0 0 0 0 0)(gimp-image-delete im))
(let* ((im(car(gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/batch6-gray-scar/new-moments/s021-serat-master.xcf" "visual-novel/art/scene-studies/batch6-gray-scar/new-moments/s021-serat-master.xcf")))(f 0))
(gimp-message (string-append "s021-serat layers=" (number->string (car(gimp-image-get-layers im)))))
(set! f(car(gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save RUN-NONINTERACTIVE im f "/tmp/batch6-new-s021-serat-reopened.png" "/tmp/batch6-new-s021-serat-reopened.png" 0 9 0 0 0 0 0)(gimp-image-delete im))
(let* ((im(car(gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/batch6-gray-scar/new-moments/s021-boat-master.xcf" "visual-novel/art/scene-studies/batch6-gray-scar/new-moments/s021-boat-master.xcf")))(f 0))
(gimp-message (string-append "s021-boat layers=" (number->string (car(gimp-image-get-layers im)))))
(set! f(car(gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save RUN-NONINTERACTIVE im f "/tmp/batch6-new-s021-boat-reopened.png" "/tmp/batch6-new-s021-boat-reopened.png" 0 9 0 0 0 0 0)(gimp-image-delete im))
(gimp-quit 0)
