(let* ((dir "visual-novel/art/scene-studies/s054-lever/")(im(car(gimp-file-load RUN-NONINTERACTIVE (string-append dir "framed-generation.png") (string-append dir "framed-generation.png"))))(l 0)(m 0)(f 0))
(gimp-item-set-name (car(gimp-image-get-active-layer im)) "Complete expanded lever scene: reviewed action and room")
(set! l(car(gimp-file-load-layer RUN-NONINTERACTIVE im (string-append dir "framed-generation.png"))))(gimp-image-insert-layer im l 0 0)(gimp-layer-set-offsets l 0 -47)(gimp-item-set-name l "Adjacent same-coat cloth removes excess generated badge rays")
(set! m(car(gimp-layer-create-mask l ADD-BLACK-MASK)))(gimp-layer-add-mask l m)(gimp-image-select-ellipse im CHANNEL-OP-REPLACE 715 277 41 44)(gimp-selection-feather im 4)(gimp-edit-fill m WHITE-FILL)(gimp-selection-none im)
(set! l(car(gimp-file-load-layer RUN-NONINTERACTIVE im "visual-novel/art/prop-keys/emblems/human-temple-sun.png")))(gimp-image-insert-layer im l 0 0)(gimp-layer-scale l 44 44 TRUE)(gimp-layer-set-offsets l 713 277)(gimp-item-set-name l "Twelve-ray temple badge, matched to campaign key")
(set! l(car(gimp-file-load-layer RUN-NONINTERACTIVE im (string-append dir "framed-generation.png"))))(gimp-image-insert-layer im l 0 0)(gimp-item-set-name l "Original painted metallic badge center")
(set! m(car(gimp-layer-create-mask l ADD-BLACK-MASK)))(gimp-layer-add-mask l m)(gimp-image-select-ellipse im CHANNEL-OP-REPLACE 731 294 9 11)(gimp-selection-feather im 1)(gimp-edit-fill m WHITE-FILL)(gimp-selection-none im)
(gimp-xcf-save RUN-NONINTERACTIVE im l (string-append dir "native-master.xcf") (string-append dir "native-master.xcf"))
(gimp-image-scale im 1920 1081)(gimp-image-resize im 1920 1080 0 0)
(gimp-xcf-save RUN-NONINTERACTIVE im l (string-append dir "delivery-master.xcf") (string-append dir "delivery-master.xcf"))
(set! f(car(gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save RUN-NONINTERACTIVE im f (string-append dir "candidate.png") (string-append dir "candidate.png") 0 9 0 0 0 0 0)(gimp-image-delete im))
(let* ((dir "visual-novel/art/scene-studies/s054-lever/")(im(car(gimp-file-load RUN-NONINTERACTIVE (string-append dir "delivery-master.xcf") (string-append dir "delivery-master.xcf"))))(f(car(gimp-image-merge-visible-layers im CLIP-TO-IMAGE))))
(file-png-save RUN-NONINTERACTIVE im f "/tmp/s054-lever-reopened.png" "/tmp/s054-lever-reopened.png" 0 9 0 0 0 0 0)(gimp-image-delete im))(gimp-quit 0)
