(let* ((dir "visual-novel/art/scene-studies/s054-lever/")(im(car(gimp-file-load RUN-NONINTERACTIVE (string-append dir "native-master.xcf") (string-append dir "native-master.xcf"))))(l 0)(m 0)(f 0))
(set! l(car(gimp-file-load-layer RUN-NONINTERACTIVE im "visual-novel/renpy/game/art/scenes/s054-strike.png")))(gimp-image-insert-layer im l 0 0)(gimp-layer-scale l 1248 702 TRUE)(gimp-layer-set-offsets l 200 85)
(gimp-item-set-name l "Same right-glove dorsal tear from adjacent strike; pose and fingers preserved")
(gimp-levels l HISTOGRAM-VALUE 0 255 1.0 0 205)
(set! m(car(gimp-layer-create-mask l ADD-BLACK-MASK)))(gimp-layer-add-mask l m)(gimp-image-select-ellipse im CHANNEL-OP-REPLACE 641 296 26 30)(gimp-selection-feather im 2)(gimp-edit-fill m WHITE-FILL)(gimp-selection-none im)
(gimp-xcf-save RUN-NONINTERACTIVE im l (string-append dir "native-master.xcf") (string-append dir "native-master.xcf"))
(gimp-image-scale im 1920 1081)(gimp-image-resize im 1920 1080 0 0)
(gimp-xcf-save RUN-NONINTERACTIVE im l (string-append dir "delivery-master.xcf") (string-append dir "delivery-master.xcf"))
(set! f(car(gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save RUN-NONINTERACTIVE im f (string-append dir "candidate.png") (string-append dir "candidate.png") 0 9 0 0 0 0 0)(gimp-image-delete im))
(let* ((dir "visual-novel/art/scene-studies/s054-lever/")(im(car(gimp-file-load RUN-NONINTERACTIVE (string-append dir "delivery-master.xcf") (string-append dir "delivery-master.xcf"))))(f(car(gimp-image-merge-visible-layers im CLIP-TO-IMAGE))))
(file-png-save RUN-NONINTERACTIVE im f "/tmp/s054-lever-reopened.png" "/tmp/s054-lever-reopened.png" 0 9 0 0 0 0 0)(gimp-image-delete im))(gimp-quit 0)
