(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/s051-north-infirmary-court/outpaint-source.png" "wide.png"))) (back (car (gimp-image-get-active-layer im))) (src 0) (mask 0) (flat 0))
(gimp-item-set-name back "Wider court and complete supported kneeling stance")
(set! src (car (gimp-file-load-layer RUN-NONINTERACTIVE im "visual-novel/art/scene-studies/s051-north-infirmary-court/defense-corrected-source.png")))
(gimp-image-insert-layer im src 0 -1)
(gimp-item-set-name src "Reviewed source action restored uniformly; generated lower supports retained")
(gimp-context-set-interpolation INTERPOLATION-NOHALO)
(gimp-layer-scale src 1321 743 TRUE)
(gimp-layer-set-offsets src 249 55)
(set! mask (car (gimp-layer-create-mask src ADD-BLACK-MASK)))
(gimp-layer-add-mask src mask)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 34 #(254 60 1564 60 1564 791 958 791 920 676 833 650 740 635 620 634 587 590 552 559 472 534 397 523 354 470 254 453 254 60 254 60 254 60))
(gimp-selection-feather im 8)
(gimp-edit-fill mask WHITE-FILL)
(gimp-selection-none im)
(gimp-xcf-save RUN-NONINTERACTIVE im src "visual-novel/art/scene-studies/s051-north-infirmary-court/court-master.xcf" "court-master.xcf")
(set! flat (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save RUN-NONINTERACTIVE im flat "/tmp/s051-framed-native.png" "/tmp/s051-framed-native.png" 0 9 0 0 0 0 0)
(gimp-image-scale im 1920 1080)
(set! flat (car (gimp-image-get-active-layer im)))
(file-png-save RUN-NONINTERACTIVE im flat "/tmp/s051-final-candidate.png" "/tmp/s051-final-candidate.png" 0 9 0 0 0 0 0)
(gimp-image-delete im))
(gimp-quit 0)
