(let* ((im (car (gimp-image-new 1920 1080 RGB))) (back (car (gimp-layer-new im 1920 1080 RGB-IMAGE "Extension guide" 100 NORMAL-MODE))) (act 0) (flat 0))
(gimp-image-insert-layer im back 0 -1)
(gimp-context-set-foreground '(110 113 112))
(gimp-drawable-fill back FOREGROUND-FILL)
(set! act (car (gimp-file-load-layer RUN-NONINTERACTIVE im "/tmp/s051-assembled-v3.png")))
(gimp-image-insert-layer im act 0 -1)
(gimp-context-set-interpolation INTERPOLATION-NOHALO)
(gimp-layer-scale act 1304 734 TRUE)
(gimp-layer-set-offsets act 360 65)
(set! flat (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save RUN-NONINTERACTIVE im flat "/tmp/s051-outpaint-guide.png" "/tmp/s051-outpaint-guide.png" 0 9 0 0 0 0 0)
(gimp-image-delete im))
(gimp-quit 0)
