(let* ((img (car (gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/s055-mara/mara-master.xcf" "visual-novel/art/scene-studies/s055-mara/mara-master.xcf"))))
(let* ((floor (car (gimp-file-load-layer RUN-NONINTERACTIVE img "visual-novel/art/scene-studies/s055-mara/flat-landing-component.png"))))
(gimp-image-insert-layer img floor 0 0)(gimp-layer-add-alpha floor)(gimp-item-set-name floor "Continuous level foreground paving - original grief group and contact pixels retained")
(gimp-context-set-interpolation INTERPOLATION-NOHALO)(gimp-layer-scale floor 1920 1080 TRUE)(gimp-layer-set-offsets floor 0 0)
(gimp-image-select-polygon img CHANNEL-OP-REPLACE 30 #(0 830 78 748 140 724 310 718 420 708 670 700 920 730 1100 753 1390 792 1590 811 1790 778 1840 695 1920 695 1920 1080 0 1080))
(gimp-selection-feather img 4)(gimp-layer-add-mask floor (car (gimp-layer-create-mask floor ADD-SELECTION-MASK)))(gimp-selection-none img))
(gimp-xcf-save RUN-NONINTERACTIVE img (car (gimp-image-get-active-layer img)) "visual-novel/art/scene-studies/s055-mara/mara-flat-landing-master.xcf" "visual-novel/art/scene-studies/s055-mara/mara-flat-landing-master.xcf")
(let* ((layer (car (gimp-image-merge-visible-layers img CLIP-TO-IMAGE))))
(file-png-save RUN-NONINTERACTIVE img layer "/tmp/s055-mara-flat-landing-candidate.png" "/tmp/s055-mara-flat-landing-candidate.png" 0 9 0 0 0 0 0))
(gimp-image-delete img))(gimp-quit 0)
