; Accepted S044 assembly only. Run from repository root using GIMP 2.10.36.
; Omit -d: the brush used for the small cloth cleanup and banner slit must load.
; The rejected hand-painted horns and banner repaint experiments are omitted.
(define (fixed-star img)
 (let ((star (car (gimp-file-load-layer RUN-NONINTERACTIVE img "visual-novel/art/prop-keys/emblems/northern-split-star.png"))))
  (gimp-image-insert-layer img star 0 0)
  (gimp-item-set-name star "Lucan divided eight-point badge")
  (gimp-layer-resize star 352 352 -80 -80)
  (gimp-layer-scale star 26 28 FALSE)
  (gimp-layer-set-offsets star 1038 218)
  (gimp-image-select-rectangle img CHANNEL-OP-REPLACE 1050 218 2 28)
  (gimp-edit-clear star)
  (gimp-selection-none img)
  (gimp-layer-set-opacity star 89)))
(let* ((folder "visual-novel/art/scene-studies/s044-upper-stores-landing/")
       (img (car (gimp-file-load RUN-NONINTERACTIVE (string-append folder "landing-source-candidate.png") "source")))
       (base (car (gimp-image-get-active-layer img)))
       (border (car (gimp-file-load-layer RUN-NONINTERACTIVE img (string-append folder "final-border-low-arch-component.png"))))
       (oldborder (car (gimp-file-load-layer RUN-NONINTERACTIVE img (string-append folder "environment-border-component.png"))))
       (arch (car (gimp-file-load-layer RUN-NONINTERACTIVE img (string-append folder "final-border-low-arch-component.png")))))
 (gimp-context-set-interpolation INTERPOLATION-NOHALO)
 (gimp-image-resize img 2288 1287 308 35)
 (gimp-item-set-name base "Original native scene preserved at 308,35")
 (gimp-image-insert-layer img border 0 1)
 (gimp-layer-scale border 2288 1287 FALSE)
 (gimp-layer-set-offsets border 0 0)
 (gimp-item-set-name border "Final quiet river and side margins ONLY")
 (gimp-image-insert-layer img oldborder 0 2)
 (gimp-layer-scale oldborder 2064 1161 FALSE)
 (gimp-layer-set-offsets oldborder 112 0)
 (gimp-item-set-name oldborder "Earlier environment border trial; superseded and hidden")
 (gimp-item-set-visible oldborder FALSE)
 (gimp-image-select-rectangle img CHANNEL-OP-REPLACE 308 35 1672 941)
 (gimp-selection-shrink img 5)
 (gimp-selection-feather img 7)
 (let ((mask (car (gimp-layer-create-mask base ADD-BLACK-MASK))))
  (gimp-layer-add-mask base mask)
  (gimp-context-set-foreground '(255 255 255))
  (gimp-edit-fill mask FOREGROUND-FILL))
 (gimp-selection-none img)
 (gimp-image-insert-layer img arch 0 0)
 (gimp-layer-scale arch 2288 1287 FALSE)
 (gimp-layer-set-offsets arch 0 0)
 (gimp-item-set-name arch "Low service arch only; crown reduced, water retained")
 (gimp-image-select-polygon img CHANNEL-OP-REPLACE 12 (vector 1640 280 1800 280 1800 426 1710 426 1670 385 1640 335))
 (gimp-selection-feather img 4)
 (let ((mask (car (gimp-layer-create-mask arch ADD-BLACK-MASK))))
  (gimp-layer-add-mask arch mask)
  (gimp-context-set-foreground '(255 255 255))
  (gimp-edit-fill mask FOREGROUND-FILL))
 (gimp-selection-none img)
 (let* ((src (car (gimp-layer-new-from-visible img img "Hidden pre-finish composite for local clone samples")))
        (cloth (car (gimp-layer-new img 2288 1287 RGBA-IMAGE "Clean original cloth under corrected Lucan badge" 100 NORMAL-MODE)))
        (horns (car (gimp-file-load-layer RUN-NONINTERACTIVE img (string-append folder "distant-horns-component.png"))))
        (split (car (gimp-layer-new img 2288 1287 RGBA-IMAGE "Banner original painted star; local visible vertical split" 100 NORMAL-MODE))))
  (gimp-image-insert-layer img src 0 0)
  (gimp-image-insert-layer img cloth 0 0)
  (gimp-drawable-fill cloth TRANSPARENT-FILL)
  (gimp-context-set-brush "2. Hardness 075")
  (gimp-context-set-brush-size 19)
  (for-each (lambda (pt) (gimp-clone cloth src CLONE-IMAGE (+ (car pt) 30) (+ (cadr pt) 18) 2 (vector (car pt) (cadr pt)))) '((1050 222) (1050 232) (1050 241) (1041 232) (1060 232)))
  (gimp-item-set-visible src FALSE)
  (fixed-star img)
  (gimp-image-insert-layer img horns 0 0)
  (gimp-layer-scale horns 850 315 FALSE)
  (gimp-layer-set-offsets horns 1130 125)
  (gimp-item-set-name horns "Distant northern horns; only five small heads masked")
  (gimp-image-select-rectangle img CHANNEL-OP-REPLACE 1174 160 40 35)
  (gimp-image-select-rectangle img CHANNEL-OP-ADD 1370 180 39 35)
  (gimp-image-select-rectangle img CHANNEL-OP-ADD 1451 184 43 40)
  (gimp-image-select-rectangle img CHANNEL-OP-ADD 1854 297 36 40)
  (gimp-image-select-rectangle img CHANNEL-OP-ADD 1920 290 38 42)
  (gimp-selection-feather img 1.2)
  (let ((mask (car (gimp-layer-create-mask horns ADD-BLACK-MASK))))
   (gimp-layer-add-mask horns mask)
   (gimp-context-set-foreground '(255 255 255))
   (gimp-edit-fill mask FOREGROUND-FILL))
  (gimp-selection-none img)
  (gimp-image-insert-layer img split 0 0)
  (gimp-drawable-fill split TRANSPARENT-FILL)
  (gimp-context-set-brush "2. Hardness 075")
  (gimp-context-set-brush-size 1.8)
  (gimp-context-set-foreground '(44 52 53))
  (gimp-paintbrush-default split 4 (vector 1357 134 1357 164))
  ; Rebuild writes scratch masters so the inspected originals cannot be overwritten accidentally.
  (gimp-xcf-save RUN-NONINTERACTIVE img split "/tmp/s044-rebuilt-local-master.xcf" "master")
  (gimp-image-scale img 1920 1080)
  (gimp-xcf-save RUN-NONINTERACTIVE img split "/tmp/s044-rebuilt-delivery-master.xcf" "master")
  (let ((flat (car (gimp-image-merge-visible-layers img CLIP-TO-IMAGE))))
   (file-png-save RUN-NONINTERACTIVE img flat "/tmp/s044-rebuilt-review.png" "review" 0 9 0 0 0 0 0)))
 (gimp-image-delete img))
