(gimp-context-push)
(let* ((img (car (gimp-file-load RUN-NONINTERACTIVE "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-gray-scar/s021-boat/source.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-gray-scar/s021-boat/source.png"))))
(gimp-item-set-name (car (gimp-image-get-active-layer img)) "Current source — protected base")
(let* ((ly (car (gimp-file-load-layer RUN-NONINTERACTIVE img "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-gray-scar/s021-boat/donor.png"))) (mask 0))
(gimp-image-insert-layer img ly 0 0)
(gimp-item-set-name ly "Brother \u2014 established face, ponytail, uniform, hand; water clears old pauldron")
(gimp-layer-scale ly 1920 1080 TRUE)
(gimp-layer-set-offsets ly 0 0)
(set! mask (car (gimp-layer-create-mask ly ADD-BLACK-MASK)))
(gimp-layer-add-mask ly mask)
(gimp-image-select-polygon img CHANNEL-OP-REPLACE 48 (vector 240 420 302 354 325 295 353 261 435 261 475 284 483 343 499 360 538 379 558 487 531 498 515 515 501 537 480 548 461 564 446 593 438 613 403 616 378 586 356 578 326 571 310 558 265 552 249 526))
(gimp-selection-feather img 3)
(gimp-context-set-foreground "white")
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none img)
)
(gimp-xcf-save RUN-NONINTERACTIVE img (car (gimp-image-get-active-layer img)) "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-gray-scar/s021-boat/master.xcf" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-gray-scar/s021-boat/master.xcf")
(let* ((dup (car (gimp-image-duplicate img))) (flat (car (gimp-image-merge-visible-layers dup CLIP-TO-IMAGE))))
(file-png-save RUN-NONINTERACTIVE dup flat "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-gray-scar/s021-boat/candidate.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-gray-scar/s021-boat/candidate.png" 0 9 0 0 0 0 0)
(gimp-image-delete dup))
(gimp-image-delete img))
(let* ((re (car (gimp-file-load RUN-NONINTERACTIVE "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-gray-scar/s021-boat/master.xcf" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-gray-scar/s021-boat/master.xcf"))) (flat (car (gimp-image-merge-visible-layers re CLIP-TO-IMAGE))))
(file-png-save RUN-NONINTERACTIVE re flat "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-gray-scar/s021-boat/reopened.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-gray-scar/s021-boat/reopened.png" 0 9 0 0 0 0 0)
(gimp-image-delete re))
(gimp-context-pop)
(gimp-quit 0)
