(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "/home/kir/.codex/generated_images/01a0d813-f663-7722-bc3f-28105deca2e9/exec-cb21f32d-e6b6-41f6-bdc9-751627486abe.png" "source"))) (base (car (gimp-image-get-active-layer im))) (patch 0) (mask 0) (clean 0) (sun 0) (flat 0))
 (gimp-item-set-name base "Selected wide recoil painting — whole scene up75px, no rescaling")
 (gimp-layer-set-offsets base 0 -75)
 (set! patch (car (gimp-file-load-layer RUN-NONINTERACTIVE im "/home/kir/.codex/generated_images/01a0d813-f663-7722-bc3f-28105deca2e9/exec-0f551609-9303-4b4b-ac92-a2bae2a55a9e.png")))
 (gimp-image-insert-layer im patch 0 -1)
 (gimp-item-set-name patch "Generated quiet ground only — bottom101px mask")
 (set! mask (car (gimp-layer-create-mask patch ADD-BLACK-MASK)))
 (gimp-layer-add-mask patch mask)
 (gimp-image-select-rectangle im CHANNEL-OP-REPLACE 0 850 1672 91)
 (gimp-selection-feather im 10)
 (gimp-edit-fill mask WHITE-FILL)
 (gimp-selection-none im)
 (set! flat (car (gimp-layer-new-from-visible im im "Aligned scene composite for local emblem texture")))
 (gimp-image-insert-layer im flat 0 -1)
 (set! clean (car (gimp-layer-new im 1672 941 RGBA-IMAGE "Tiny cloth and shield emblem restoration" 100 NORMAL-MODE)))
 (gimp-image-insert-layer im clean 0 -1)
 (gimp-context-set-brush "2. Hardness 075")
 (gimp-context-set-brush-size 24)
 (gimp-clone clean flat CLONE-IMAGE 1052 274 2 #(1065 246))
 (gimp-context-set-brush-size 42)
 (gimp-clone clean flat CLONE-IMAGE 305 330 2 #(297 298))
 (gimp-context-set-interpolation INTERPOLATION-NOHALO)
 (set! sun (car (gimp-file-load-layer RUN-NONINTERACTIVE im "visual-novel/art/prop-keys/emblems/human-temple-sun.png")))
 (gimp-image-insert-layer im sun 0 -1)
 (gimp-item-set-name sun "Tessa canonical twelve-short-ray brass sun")
 (gimp-layer-scale sun 26 26 TRUE)
 (gimp-layer-set-offsets sun 1052 233)
 (gimp-layer-set-opacity sun 88)
 (set! sun (car (gimp-file-load-layer RUN-NONINTERACTIVE im "visual-novel/art/prop-keys/emblems/human-temple-sun.png")))
 (gimp-image-insert-layer im sun 0 -1)
 (gimp-item-set-name sun "Olan shield canonical small sun")
 (gimp-layer-scale sun 43 43 TRUE)
 (gimp-layer-set-offsets sun 275 276)
 (gimp-layer-set-opacity sun 72)
 (gimp-xcf-save RUN-NONINTERACTIVE im base "visual-novel/art/scene-studies/s042-mill-town-later/cart-master.xcf" "cart-master.xcf")
 (set! flat (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
 (file-png-save RUN-NONINTERACTIVE im flat "/tmp/s042-cart-native.png" "/tmp/s042-cart-native.png" 0 9 0 0 0 0 0)
 (gimp-image-crop im 1664 936 4 2)
 (gimp-image-scale im 1920 1080)
 (set! flat (car (gimp-image-get-active-layer im)))
 (file-png-save RUN-NONINTERACTIVE im flat "visual-novel/renpy/game/art/scenes/s042-cart.png" "s042-cart.png" 0 9 0 0 0 0 0)
 (gimp-image-delete im))
(gimp-quit 0)
