(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "/home/kir/.codex/generated_images/01a0d813-f663-7722-bc3f-28105deca2e9/exec-4d296f55-2200-4d62-8fff-a31d49de74c6.png" "source"))) (base (car (gimp-image-get-active-layer im))) (blood 0) (flat 0) (bottom 0))
 (gimp-item-set-name base "Selected full two-adult hand-contact source")
 (set! blood (car (gimp-layer-new im 1672 941 RGBA-IMAGE "Restrained dried-blood traces in healthy RIGHT finger webs" 100 NORMAL-MODE)))
 (gimp-image-insert-layer im blood 0 -1)
 (gimp-context-set-foreground '(105 58 46)) (gimp-context-set-opacity 40)
 (gimp-context-set-brush "2. Hardness 050") (gimp-context-set-brush-size 1.5)
 (gimp-paintbrush-default blood 4 #(890 365 891 369))
 (gimp-paintbrush-default blood 4 #(900 364 901 368))
 (gimp-paintbrush-default blood 4 #(911 361 912 364))
 (gimp-context-set-opacity 100)
 (set! flat (car (gimp-layer-new-from-visible im im "Whole scene up27px — original body proportions")))
 (gimp-image-insert-layer im flat 0 -1)
 (set! bottom (car (gimp-layer-new-from-drawable flat im)))
 (gimp-image-insert-layer im bottom 0 -1)
 (gimp-item-set-name bottom "Quiet bottom ground only — native120px extended to147px")
 (gimp-layer-resize bottom 1672 120 0 -821)
 (gimp-context-set-interpolation INTERPOLATION-NOHALO)
 (gimp-layer-scale bottom 1672 147 TRUE)
 (gimp-layer-set-offsets bottom 0 794)
 (gimp-layer-set-offsets flat 0 -27)
 (gimp-item-set-visible base FALSE) (gimp-item-set-visible blood FALSE)
 (gimp-xcf-save RUN-NONINTERACTIVE im flat "visual-novel/art/scene-studies/s042-mill-town-later/hand-master.xcf" "hand-master.xcf")
 (set! flat (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
 (file-png-save RUN-NONINTERACTIVE im flat "/tmp/s042-hand-native.png" "native" 0 9 0 0 0 0 0)
 (gimp-image-crop im 1664 936 4 2) (gimp-image-scale im 1920 1080)
 (set! flat (car (gimp-image-get-active-layer im)))
 (file-png-save RUN-NONINTERACTIVE im flat "visual-novel/renpy/game/art/scenes/s042-mara-hand.png" "s042-mara-hand.png" 0 9 0 0 0 0 0)
 (gimp-image-delete im)) (gimp-quit 0)
