(let* ((img (car (gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/s058-final/offered-chair-source.png" "source")))
       (src (car (gimp-image-get-active-layer img)))
       (vest (car (gimp-layer-copy src TRUE)))
       (paper (car (gimp-layer-new img 1672 941 RGBA-IMAGE "Remove invented wax seal from reply; clean paper sample" 100 NORMAL-MODE))))
 (gimp-item-set-name src "Original eight-person offered-chair painting; natural actors and furniture")
 (gimp-image-insert-layer img vest 0 0)
 (gimp-item-set-name vest "Orren waistcoat only: warm brown shared spring state")
 (gimp-colorize vest 21 35 0)
 (gimp-image-select-polygon img CHANNEL-OP-REPLACE 28 (vector 710 154 764 134 778 185 815 252 838 187 851 133 891 156 892 233 883 290 881 349 811 353 716 345 719 245 717 168))
 (gimp-selection-feather img 1.5)
 (gimp-layer-add-mask vest (car (gimp-layer-create-mask vest ADD-SELECTION-MASK)))
 (gimp-selection-none img)
 (gimp-image-insert-layer img paper 0 0) (gimp-drawable-fill paper TRANSPARENT-FILL)
 (gimp-context-set-brush "2. Hardness 075") (gimp-context-set-brush-size 19)
 (gimp-image-select-ellipse img CHANNEL-OP-REPLACE 723 635 31 19) (gimp-selection-feather img 1)
 (gimp-clone paper src CLONE-IMAGE 773 644 2 (vector 738 644))
 (gimp-selection-none img)
 (let ((toggle (car (gimp-file-load-layer RUN-NONINTERACTIVE img "visual-novel/art/scene-studies/s058-final/two-toggle-detail-component.png"))))
  (gimp-image-insert-layer img toggle 0 0) (gimp-layer-scale toggle 100 125 FALSE) (gimp-layer-set-offsets toggle 340 450)
  (gimp-item-set-name toggle "Remove unwanted third LEFT wooden toggle only; upper two retained")
  (gimp-image-select-polygon img CHANNEL-OP-REPLACE 16 (vector 365 532 394 520 407 527 415 542 417 563 398 573 365 568 357 549))
  (gimp-selection-feather img 1.5) (gimp-layer-add-mask toggle (car (gimp-layer-create-mask toggle ADD-SELECTION-MASK))) (gimp-selection-none img))
 (gimp-xcf-save RUN-NONINTERACTIVE img paper "visual-novel/art/scene-studies/s058-final/chair-local-master.xcf" "master")
 (let ((flat (car (gimp-image-merge-visible-layers img CLIP-TO-IMAGE))))
  (file-png-save RUN-NONINTERACTIVE img flat "/tmp/s058-final-local-state.png" "state" 0 9 0 0 0 0 0)
  (gimp-context-set-interpolation INTERPOLATION-NOHALO) (gimp-image-scale img 1190 670)
  (gimp-image-resize img 1920 1080 350 80)
  (let ((bg (car (gimp-layer-new img 1920 1080 RGBA-IMAGE "Neutral space guide; generate room only here" 100 NORMAL-MODE))))
   (gimp-image-insert-layer img bg 0 1) (gimp-context-set-foreground '(125 129 130)) (gimp-drawable-fill bg FOREGROUND-FILL)
   (gimp-xcf-save RUN-NONINTERACTIVE img flat "visual-novel/art/scene-studies/s058-final/framing-guide.xcf" "guide")
   (let ((guide (car (gimp-image-merge-visible-layers img CLIP-TO-IMAGE)))) (file-png-save RUN-NONINTERACTIVE img guide "/tmp/s058-final-framing-guide.png" "guide" 0 9 0 0 0 0 0))))
 (gimp-image-delete img)) (gimp-quit 0)
