; Recreate exact pre-toggle/pre-final-warmth input used for the room-extension component.
(let* ((img (car (gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/s058-final/offered-chair-source.png" "source")))
       (src (car (gimp-image-get-active-layer img)))
       (vest (car (gimp-layer-copy src TRUE)))
       (paper (car (gimp-layer-new img 1672 941 RGBA-IMAGE "Remove invented wax seal from reply; clean paper sample" 100 NORMAL-MODE))))
 (gimp-item-set-name src "Original eight-person offered-chair painting; natural actors and furniture")
 (gimp-image-insert-layer img vest 0 0)
 (gimp-item-set-name vest "Orren waistcoat only: warm brown shared spring state")
 (gimp-colorize vest 30 28 0)
 (gimp-image-select-polygon img CHANNEL-OP-REPLACE 28 (vector 710 154 764 134 778 185 815 252 838 187 851 133 891 156 892 233 883 290 881 349 811 353 716 345 719 245 717 168))
 (gimp-selection-feather img 1.5)
 (gimp-layer-add-mask vest (car (gimp-layer-create-mask vest ADD-SELECTION-MASK)))
 (gimp-selection-none img)
 (gimp-image-insert-layer img paper 0 0) (gimp-drawable-fill paper TRANSPARENT-FILL)
 (gimp-context-set-brush "2. Hardness 075") (gimp-context-set-brush-size 19)
 (gimp-image-select-ellipse img CHANNEL-OP-REPLACE 723 635 31 19) (gimp-selection-feather img 1)
 (gimp-clone paper src CLONE-IMAGE 773 644 2 (vector 738 644))
 (gimp-selection-none img)
 (let ((flat (car (gimp-image-merge-visible-layers img CLIP-TO-IMAGE))))
  (file-png-save RUN-NONINTERACTIVE img flat "/tmp/s058-final-original-extension-state.png" "state" 0 9 0 0 0 0 0)
  (gimp-context-set-interpolation INTERPOLATION-NOHALO) (gimp-image-scale img 1190 670)
  (gimp-image-resize img 1920 1080 350 80)
  (let ((bg (car (gimp-layer-new img 1920 1080 RGBA-IMAGE "Neutral space guide; generate room only here" 100 NORMAL-MODE))))
   (gimp-image-insert-layer img bg 0 1) (gimp-context-set-foreground '(125 129 130)) (gimp-drawable-fill bg FOREGROUND-FILL)
   (let ((guide (car (gimp-image-merge-visible-layers img CLIP-TO-IMAGE)))) (file-png-save RUN-NONINTERACTIVE img guide "visual-novel/art/prompts/s058-final/environment-extension-input-guide.png" "guide" 0 9 0 0 0 0 0))))
 (gimp-image-delete img)) (gimp-quit 0)
