; Item 7 only: recover existing neutral source pixels and preserve the accepted sling geometry.
(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/ceremony-applause/sling-repair.xcf" "sling-repair.xcf")))
       (layers (cadr (gimp-image-get-layers im)))
       (patch (vector-ref layers 0))
       (old-base (vector-ref layers 1))
       (neutral 0) (archive 0) (flat 0))
 (gimp-item-set-name old-base "Hidden archive — prior overexposed painting")
 (gimp-item-set-visible old-base FALSE)
 (set! neutral (car (gimp-file-load-layer RUN-NONINTERACTIVE im "visual-novel/renpy/game/art/base/rovel/cg/ceremony-applause.png")))
 (gimp-image-insert-layer im neutral 0 1)
 (gimp-item-set-name neutral "Neutral source recovery — exact hall and other soldiers")
 (set! archive (car (gimp-layer-copy patch TRUE)))
 (gimp-image-insert-layer im archive 0 2)
 (gimp-item-set-name archive "Hidden archive — accepted sling component before exposure match")
 (gimp-item-set-visible archive FALSE)
 (gimp-item-set-name patch "Accepted sling and free palm — local neutral exposure match")
 (gimp-curves-spline patch HISTOGRAM-VALUE 22 #(0 0 32 18 64 38 96 56 128 74 160 94 192 114 224 140 240 164 248 190 255 245))
 (gimp-hue-saturation patch ALL-HUES 0 0 -20)
 (gimp-xcf-save RUN-NONINTERACTIVE im patch "visual-novel/art/scene-studies/ceremony-applause/exposure-recovery.xcf" "exposure-recovery.xcf")
 (set! flat (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
 (file-png-save RUN-NONINTERACTIVE im flat "/tmp/s004-applause-neutral-candidate.png" "/tmp/s004-applause-neutral-candidate.png" 0 9 0 0 0 0 0)
 (gimp-image-delete im))
(gimp-quit 0)
