(let* ((img (car (gimp-file-load RUN-NONINTERACTIVE "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/s037-relief-camp/relief-camp-local-repair-master.xcf" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/s037-relief-camp/relief-camp-local-repair-master.xcf")))
(layers (gimp-image-get-layers img))
(oldtop (aref (cadr layers) 3))
(patch (car (gimp-file-load-layer RUN-NONINTERACTIVE img "/home/kir/.codex/generated_images/01a0d813-b01b-7003-ac1a-13c396875d28/exec-9c48aef3-5933-4b4e-975e-a4d01bf5a893.png"))))
(gimp-item-set-name oldtop "REJECTED mirrored extension (hidden)")
(gimp-item-set-visible oldtop FALSE)
(gimp-image-insert-layer img patch 0 0)
(gimp-item-set-name patch "Repaired continuous canvas and sky; top band only")
(gimp-context-set-interpolation INTERPOLATION-NOHALO)
(gimp-layer-scale patch 1920 1080 FALSE)
(let ((mask (car (gimp-layer-create-mask patch ADD-BLACK-MASK))))
(gimp-layer-add-mask patch mask)
(gimp-context-set-foreground '(255 255 255))
(gimp-context-set-background '(0 0 0))
(gimp-edit-blend mask FG-BG-RGB-MODE NORMAL-MODE GRADIENT-LINEAR 100 0 REPEAT-NONE FALSE FALSE 1 0 TRUE 0 50 0 68))
(gimp-xcf-save RUN-NONINTERACTIVE img patch "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/s037-relief-camp/relief-camp-local-repair-master.xcf" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/s037-relief-camp/relief-camp-local-repair-master.xcf")
(let ((flat (car (gimp-image-merge-visible-layers img CLIP-TO-IMAGE))))
(file-png-save RUN-NONINTERACTIVE img flat "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/renpy/game/art/scenes/s037-relief-camp.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/renpy/game/art/scenes/s037-relief-camp.png" 0 9 0 0 0 0 0))
(gimp-image-delete img))
(gimp-quit 0)
