(let* ((im(car(gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/batch6-northern/s038-northern-stores-office/before.png" "visual-novel/art/scene-studies/batch6-northern/s038-northern-stores-office/before.png"))) (l(car(gimp-file-load-layer RUN-NONINTERACTIVE im "visual-novel/art/scene-studies/batch6-northern/s038-northern-stores-office/head-donor.png"))) (m 0) (f 0))
(gimp-image-insert-layer im l 0 0)
(gimp-layer-scale l 430 465 FALSE)
(gimp-layer-set-offsets l 350 25)
(gimp-item-set-name l "Later Lucan identity and horn pair; localized head donor")
(set! m(car(gimp-layer-create-mask l ADD-BLACK-MASK)))
(gimp-layer-add-mask l m)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 26 #(440 73 542 68 594 81 627 131 623 192 590 223 568 244 558 271 524 295 495 277 482 246 439 244 432 196))
(gimp-selection-feather im 2)
(gimp-edit-fill m WHITE-FILL)
(gimp-selection-none im)
(gimp-xcf-save RUN-NONINTERACTIVE im l "visual-novel/art/scene-studies/batch6-northern/s038-northern-stores-office/repair-master.xcf" "visual-novel/art/scene-studies/batch6-northern/s038-northern-stores-office/repair-master.xcf")
(set! f(car(gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save RUN-NONINTERACTIVE im f "visual-novel/art/scene-studies/batch6-northern/s038-northern-stores-office/candidate.png" "visual-novel/art/scene-studies/batch6-northern/s038-northern-stores-office/candidate.png" 0 9 0 0 0 0 0)
(gimp-image-delete im))(gimp-quit 0)