(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/s056-north-infirmary/outpaint-source.png" "wide ward"))) (bg (car (gimp-image-get-active-layer im))) (src 0) (mask 0) (flat 0))
(gimp-item-set-name bg "Extended ward perimeter, completed headroom and boot contacts")
(set! src (car (gimp-file-load-layer RUN-NONINTERACTIVE im "visual-novel/art/scene-studies/s056-north-infirmary/generation-initial.png")))
(gimp-image-insert-layer im src 0 -1)
(gimp-item-set-name src "Original three identities and examination; uniformly registered")
(gimp-context-set-interpolation INTERPOLATION-NOHALO)
(gimp-layer-scale src 1428 804 TRUE)
(gimp-layer-set-offsets src 120 90)
(set! mask (car (gimp-layer-create-mask src ADD-BLACK-MASK)))
(gimp-layer-add-mask src mask)
(gimp-image-select-rectangle im CHANNEL-OP-REPLACE 128 99 1412 783)
(gimp-selection-feather im 10)
(gimp-edit-fill mask WHITE-FILL)
(gimp-selection-none im)
(gimp-xcf-save RUN-NONINTERACTIVE im src "visual-novel/art/scene-studies/s056-north-infirmary/ward-examination-master.xcf" "ward-examination-master.xcf")
(set! flat (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save RUN-NONINTERACTIVE im flat "/tmp/s056-base-native.png" "/tmp/s056-base-native.png" 0 9 0 0 0 0 0)
(gimp-image-scale im 1920 1080)
(set! flat (car (gimp-image-get-active-layer im)))
(file-png-save RUN-NONINTERACTIVE im flat "/tmp/s056-base-final-candidate.png" "/tmp/s056-base-final-candidate.png" 0 9 0 0 0 0 0)
(gimp-image-delete im))
(gimp-quit 0)
