(let* ((img (car (gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/s054-duel/batch7/03-arm-donor.png" "")))
       (base (car (gimp-image-get-active-layer img)))
       (patch (car (gimp-layer-copy base TRUE))))
 (gimp-image-insert-layer img patch 0 0)
 (gimp-item-set-name patch "GUIDE ONLY - remove spare armored segment and old blade")
 (gimp-layer-set-offsets patch 0 -230)
 (let ((mask (car (gimp-layer-create-mask patch ADD-BLACK-MASK))))
  (gimp-layer-add-mask patch mask)
  (gimp-image-select-polygon img CHANNEL-OP-REPLACE 22 #(607 224 865 160 940 160 991 199 1029 235 1008 270 968 263 932 236 896 220 627 269 608 253))
  (gimp-selection-feather img 3)
  (gimp-context-set-foreground '(255 255 255))
  (gimp-edit-fill mask FOREGROUND-FILL)
  (gimp-selection-none img))
 (gimp-xcf-save RUN-NONINTERACTIVE img patch "visual-novel/art/scene-studies/s054-duel/batch7/removed-segment-guide.xcf" "visual-novel/art/scene-studies/s054-duel/batch7/removed-segment-guide.xcf")
 (let ((merged (car (gimp-image-merge-visible-layers img CLIP-TO-IMAGE))))
  (file-png-save RUN-NONINTERACTIVE img merged "visual-novel/art/scene-studies/s054-duel/batch7/removed-segment-guide.png" "visual-novel/art/scene-studies/s054-duel/batch7/removed-segment-guide.png" 0 9 0 0 0 0 0))
 (gimp-image-delete img))
(gimp-quit 0)
