(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/s058-drawings/foundation.png" "foundation"))) (l 0) (bg 0) (out 0))
(set! l (car (gimp-image-get-active-layer im)))
(gimp-image-resize im 1920 1080 124 20)
(gimp-item-set-name l "Actual foundation at native scale, offset124,20")
(set! bg (car (gimp-layer-new im 1920 1080 RGBA-IMAGE "Peripheral context to extend" 100 NORMAL-MODE)))
(gimp-image-insert-layer im bg 0 1)
(gimp-context-set-foreground '(145 145 145))
(gimp-edit-fill bg FOREGROUND-FILL)
(gimp-xcf-save RUN-NONINTERACTIVE im l "visual-novel/art/scene-studies/s058-drawings/framing-guide.xcf" "guide")
(set! out (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save2 RUN-NONINTERACTIVE im out "visual-novel/art/scene-studies/s058-drawings/framing-guide.png" "guide" 0 9 0 0 0 0 0 0 0)
(gimp-image-delete im))
(gimp-quit 0)
