(let* ((im (car (gimp-image-new 1920 1080 RGB))) (donor 0) (core 0) (mask 0) (out 0))
(set! donor (car (gimp-file-load-layer RUN-NONINTERACTIVE im "visual-novel/art/scene-studies/s058-drawings/peripheral-donor.png")))
(gimp-image-insert-layer im donor 0 0)
(gimp-layer-scale donor 1957 1101 TRUE)
(gimp-layer-set-offsets donor -21 -21)
(gimp-item-set-name donor "Generated peripheral cloth/stone — uniform registration, core excluded")
(set! core (car (gimp-file-load-layer RUN-NONINTERACTIVE im "visual-novel/art/scene-studies/s058-drawings/foundation.png")))
(gimp-image-insert-layer im core 0 0)
(gimp-layer-set-offsets core 124 20)
(gimp-item-set-name core "Reviewed original painting — native scale; complete hands/papers protected")
(set! mask (car (gimp-layer-create-mask core ADD-BLACK-MASK)))
(gimp-layer-add-mask core mask)
(gimp-image-select-rectangle im CHANNEL-OP-REPLACE 148 44 1624 893)
(gimp-selection-feather im 24)
(gimp-context-set-foreground '(255 255 255))
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none im)
(gimp-image-select-rectangle im CHANNEL-OP-REPLACE 174 65 1565 805)
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none im)
(gimp-xcf-save RUN-NONINTERACTIVE im core "visual-novel/art/scene-studies/s058-drawings/drawings-master.xcf" "master")
(set! out (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save2 RUN-NONINTERACTIVE im out "visual-novel/art/scene-studies/s058-drawings/candidate.png" "candidate" 0 9 0 0 0 0 0 0 0)
(gimp-image-delete im))
(gimp-quit 0)
