(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/s044-arch/arch-local-master.xcf" "local arch master"))) (n (car (gimp-image-get-layers im))) (ls (cadr (gimp-image-get-layers im))) (group (car (gimp-layer-group-new im))) (mask 0) (margin 0) (flat 0) (injury 0) (i 0))
(gimp-image-insert-layer im group 0 0)
(gimp-item-set-name group "Original native-size hull and reviewed local mechanism repairs")
(while (< i n)
(gimp-image-reorder-item im (vector-ref ls i) group i)
(set! i (+ i 1)))
(gimp-image-resize im 1920 1080 124 60)
(set! margin (car (gimp-file-load-layer RUN-NONINTERACTIVE im "visual-novel/art/scene-studies/s044-arch/framing-source.png")))
(gimp-image-insert-layer im margin 0 1)
(gimp-context-set-interpolation INTERPOLATION-NOHALO)
(gimp-layer-scale margin 1920 1080 TRUE)
(gimp-layer-set-offsets margin 0 0)
(gimp-item-set-name margin "Generated peripheral river and masonry only; original actors not resampled")
(set! mask (car (gimp-layer-create-mask group ADD-BLACK-MASK)))
(gimp-layer-add-mask group mask)
(gimp-image-select-rectangle im CHANNEL-OP-REPLACE 134 70 1652 921)
(gimp-selection-feather im 10)
(gimp-edit-fill mask WHITE-FILL)
(gimp-selection-none im)
; Final root/peer catch: pale turns read as a dressing. Replace only that LEFT forearm.
(set! injury (car (gimp-file-load-layer RUN-NONINTERACTIVE im "visual-novel/art/scene-studies/s044-arch/forearm-no-dressing-source.png")))
(gimp-image-insert-layer im injury 0 0)
(gimp-context-set-interpolation INTERPOLATION-NOHALO)
(gimp-layer-scale injury 120 100 TRUE)
(gimp-layer-set-offsets injury 1185 455)
(gimp-item-set-name injury "Exposed freshly cut LEFT forearm, no premature white dressing")
(set! mask (car (gimp-layer-create-mask injury ADD-BLACK-MASK)))
(gimp-layer-add-mask injury mask)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 16 #(1204 492 1227 488 1264 520 1267 542 1245 547 1227 537 1208 521 1201 508))
(gimp-selection-feather im 1.5)
(gimp-edit-fill mask WHITE-FILL)
(gimp-selection-none im)
(gimp-xcf-save RUN-NONINTERACTIVE im group "visual-novel/art/scene-studies/s044-arch/arch-delivery-master.xcf" "arch-delivery-master.xcf")
(set! flat (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save RUN-NONINTERACTIVE im flat "/tmp/s044-arch-final-candidate.png" "/tmp/s044-arch-final-candidate.png" 0 9 0 0 0 0 0)
(gimp-image-delete im))
(gimp-quit 0)
