(define (masked-donor im path name x y w h feather)
(let* ((ly (car (gimp-file-load-layer RUN-NONINTERACTIVE im path))) (mask 0))
(gimp-image-insert-layer im ly 0 0)
(gimp-item-set-name ly name)
(set! mask (car (gimp-layer-create-mask ly ADD-BLACK-MASK)))
(gimp-layer-add-mask ly mask)
(gimp-image-select-rectangle im CHANNEL-OP-REPLACE x y w h)
(gimp-selection-feather im feather)
(gimp-edit-fill mask WHITE-FILL)
(gimp-selection-none im)
ly))
(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/s044-arch/generation-initial.png" "first hull source"))) (source (car (gimp-image-get-active-layer im))) (ly 0) (flat 0) (guide 0) (base 0) (bg 0))
(gimp-item-set-name source "Original hull, three adult supports, Serat and shipped oars")
(set! ly (masked-donor im "visual-novel/art/scene-studies/s044-arch/arch-patrol-source.png" "Low service arch and continuous bank at ordinary patrol scale" 980 0 692 435 5))
(set! ly (masked-donor im "visual-novel/art/scene-studies/s044-arch/actor-contacts-source.png" "Marren both hands compress his removed coat directly on forward seam" 155 438 390 240 5))
(set! ly (masked-donor im "visual-novel/art/scene-studies/s044-arch/actor-contacts-source.png" "Scraped upper canvas of separate old port-aft repair" 1190 546 157 160 4))
(set! ly (masked-donor im "visual-novel/art/scene-studies/s044-arch/lucan-left-side-source.png" "Lucan whole seated LEFT profile with healthy RIGHT tiller and fresh LEFT cut" 982 206 475 400 5))
(set! ly (masked-donor im "visual-novel/art/scene-studies/s044-arch/patrol-overlap-source.png" "Upstream raised patrol stem occluded by genuinely low stone crown" 1368 245 200 131 4))
(gimp-xcf-save RUN-NONINTERACTIVE im ly "visual-novel/art/scene-studies/s044-arch/arch-local-master.xcf" "arch-local-master.xcf")
(set! flat (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save RUN-NONINTERACTIVE im flat "/tmp/s044-arch-local.png" "/tmp/s044-arch-local.png" 0 9 0 0 0 0 0)
(gimp-image-resize im 1920 1080 124 60)
(set! bg (car (gimp-layer-new im 1920 1080 RGB-IMAGE "Neutral framing guide margins only" 100 NORMAL-MODE)))
(gimp-image-insert-layer im bg 0 1)
(gimp-context-set-foreground '(145 149 146))
(gimp-drawable-fill bg FOREGROUND-FILL)
(set! flat (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save RUN-NONINTERACTIVE im flat "/tmp/s044-arch-frame-guide.png" "/tmp/s044-arch-frame-guide.png" 0 9 0 0 0 0 0)
(gimp-image-delete im))
(gimp-quit 0)
