(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/s058-bellweir-market-spring/market-source.png" "market-source.png"))) (base (car (gimp-image-get-active-layer im))) (bg 0) (donor 0) (mask 0) (flat 0))
(gimp-context-set-interpolation INTERPOLATION-NOHALO)
(gimp-item-set-name base "Original six named identities, bodies, seating, supported board and square")
(gimp-image-resize im 1920 1080 124 80)
(set! bg (car (gimp-file-load-layer RUN-NONINTERACTIVE im "visual-novel/art/scene-studies/s058-bellweir-market-spring/peripheral-foreground-donor.png")))
(gimp-image-insert-layer im bg 0 -1) (gimp-image-lower-item-to-bottom im bg) (gimp-layer-scale bg 1920 1080 TRUE) (gimp-layer-set-offsets bg 0 0)
(gimp-item-set-name bg "Generated peripheral sky, town and paving only; original scale retained")
(set! mask (car (gimp-layer-create-mask base ADD-WHITE-MASK))) (gimp-layer-add-mask base mask)
(gimp-image-select-rectangle im CHANNEL-OP-REPLACE 130 86 1660 929)
(gimp-selection-feather im 8) (gimp-selection-invert im) (gimp-context-set-foreground '(0 0 0)) (gimp-edit-fill mask FOREGROUND-FILL) (gimp-selection-none im)
(set! donor (car (gimp-file-load-layer RUN-NONINTERACTIVE im "visual-novel/art/scene-studies/s058-bellweir-market-spring/peripheral-foreground-donor.png")))
(gimp-image-insert-layer im donor 0 0) (gimp-layer-scale donor 1920 1080 TRUE) (gimp-layer-set-offsets donor 0 0)
(gimp-item-set-name donor "LEFT pencil set down, book catalog, complete low oxblood slip-ons")
(set! mask (car (gimp-layer-create-mask donor ADD-BLACK-MASK))) (gimp-layer-add-mask donor mask)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 28 #(856 522 950 522 967 582 971 611 998 613 998 554 1055 554 1060 613 1111 637 1125 717 1080 735 835 735 833 666 860 624))
(gimp-selection-feather im 5) (gimp-edit-fill mask WHITE-FILL) (gimp-selection-none im)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 14 #(726 928 978 934 1019 1029 978 1062 718 1056 704 982 726 928))
(gimp-selection-feather im 6) (gimp-edit-fill mask WHITE-FILL) (gimp-selection-none im)
(set! donor (car (gimp-file-load-layer RUN-NONINTERACTIVE im "visual-novel/art/scene-studies/s058-bellweir-market-spring/background-state-donor.png")))
(gimp-image-insert-layer im donor 0 0) (gimp-layer-set-offsets donor 124 80)
(gimp-item-set-name donor "Missing LEFT heron wing, two repaired roof scars, Orren LEFT cane inside, northern inspector")
(set! mask (car (gimp-layer-create-mask donor ADD-BLACK-MASK))) (gimp-layer-add-mask donor mask)
(gimp-image-select-rectangle im CHANNEL-OP-REPLACE 405 83 282 327)
(gimp-selection-feather im 5) (gimp-edit-fill mask WHITE-FILL) (gimp-selection-none im)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 18 #(1334 240 1463 240 1468 319 1474 399 1483 498 1464 603 1360 621 1321 517 1324 357))
(gimp-selection-feather im 4) (gimp-edit-fill mask WHITE-FILL) (gimp-selection-none im)
(gimp-image-select-rectangle im CHANNEL-OP-REPLACE 1398 214 118 116)
(gimp-selection-feather im 5) (gimp-edit-fill mask WHITE-FILL) (gimp-selection-none im)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 12 #(1449 307 1516 310 1542 357 1530 397 1465 391 1449 307))
(gimp-selection-feather im 4) (gimp-edit-fill mask WHITE-FILL) (gimp-selection-none im)
(gimp-image-select-rectangle im CHANNEL-OP-REPLACE 383 365 59 116)
(gimp-selection-feather im 3) (gimp-edit-fill mask WHITE-FILL) (gimp-selection-none im)
(gimp-image-select-rectangle im CHANNEL-OP-REPLACE 173 142 135 111)
(gimp-selection-feather im 6) (gimp-edit-fill mask WHITE-FILL) (gimp-selection-none im)
(gimp-image-select-rectangle im CHANNEL-OP-REPLACE 366 151 69 105)
(gimp-selection-feather im 6) (gimp-edit-fill mask WHITE-FILL) (gimp-selection-none im)
(set! donor (car (gimp-file-load-layer RUN-NONINTERACTIVE im "visual-novel/art/scene-studies/s058-bellweir-market-spring/barge-crew-donor.png")))
(gimp-image-insert-layer im donor 0 0) (gimp-layer-scale donor 1672 939 TRUE) (gimp-layer-set-offsets donor 124 80)
(gimp-item-set-name donor "Northern barge crew head/horn masks only; original count and hull")
(set! mask (car (gimp-layer-create-mask donor ADD-BLACK-MASK))) (gimp-layer-add-mask donor mask)
(gimp-image-select-rectangle im CHANNEL-OP-REPLACE 177 337 67 70)
(gimp-selection-feather im 3) (gimp-edit-fill mask WHITE-FILL) (gimp-selection-none im)
(gimp-image-select-rectangle im CHANNEL-OP-REPLACE 147 402 34 28)
(gimp-selection-feather im 2) (gimp-edit-fill mask WHITE-FILL) (gimp-selection-none im)
(gimp-xcf-save RUN-NONINTERACTIVE im base "visual-novel/art/scene-studies/s058-bellweir-market-spring/market-master.xcf" "market-master.xcf")
(set! flat (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save RUN-NONINTERACTIVE im flat "/tmp/s058-market-final-candidate.png" "/tmp/s058-market-final-candidate.png" 0 9 0 0 0 0 0)
(gimp-image-delete im)) (gimp-quit 0)
