(let* ((im (car (gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/s058-bellweir-market-spring/barge-crew-source.png" "source"))) (horns 0) (flat 0))
(set! horns (car (gimp-layer-new im 1674 940 RGBA-IMAGE "Two tiny horns on the existing back-turned northern sailor" 100 NORMAL-MODE)))
(gimp-image-insert-layer im horns 0 0)
(gimp-drawable-fill horns TRANSPARENT-FILL)
(gimp-context-set-foreground '(66 60 50))
(gimp-context-set-brush "2. Hardness 075")
(gimp-context-set-brush-size 1.8)
(gimp-paintbrush-default horns 8 #(35 334 33 332 32 330 32 328))
(gimp-paintbrush-default horns 8 #(41 334 43 332 44 330 44 328))
(gimp-xcf-save RUN-NONINTERACTIVE im horns "visual-novel/art/scene-studies/s058-bellweir-market-spring/barge-local-master.xcf" "barge-local-master.xcf")
(set! flat (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save RUN-NONINTERACTIVE im flat "visual-novel/art/scene-studies/s058-bellweir-market-spring/barge-crew-donor.png" "barge-crew-donor.png" 0 9 0 0 0 0 0)
(gimp-image-delete im))
(gimp-quit 0)
