(let* ((img (car (gimp-file-load RUN-NONINTERACTIVE "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/s039-northern-river-town/local-finish-master.xcf" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/s039-northern-river-town/local-finish-master.xcf")))
(layers (gimp-image-get-layers img))
(oldtop (aref (cadr layers) 2))
(patch (car (gimp-file-load-layer RUN-NONINTERACTIVE img "/home/kir/.codex/generated_images/01a0d813-b01b-7003-ac1a-13c396875d28/exec-392db535-6fce-4da8-baf0-607129e81327.png"))))
(gimp-item-set-name oldtop "REJECTED extrapolated top (hidden)")
(gimp-item-set-visible oldtop FALSE)
(gimp-image-insert-layer img patch 0 0)
(gimp-item-set-name patch "Continuous plaster timber and leaves; top edge only")
(gimp-context-set-interpolation INTERPOLATION-NOHALO)
(gimp-layer-scale patch 1920 1080 FALSE)
(let ((mask (car (gimp-layer-create-mask patch ADD-BLACK-MASK))))
(gimp-layer-add-mask patch mask)
(gimp-context-set-foreground '(255 255 255))
(gimp-context-set-background '(0 0 0))
(gimp-edit-blend mask FG-BG-RGB-MODE NORMAL-MODE GRADIENT-LINEAR 100 0 REPEAT-NONE FALSE FALSE 1 0 TRUE 0 21 0 37))
(gimp-xcf-save RUN-NONINTERACTIVE img patch "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/s039-northern-river-town/local-finish-master.xcf" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/s039-northern-river-town/local-finish-master.xcf")
(let ((flat (car (gimp-image-merge-visible-layers img CLIP-TO-IMAGE))))
(file-png-save RUN-NONINTERACTIVE img flat "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/renpy/game/art/scenes/s039-northern-river-town.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/renpy/game/art/scenes/s039-northern-river-town.png" 0 9 0 0 0 0 0))
(gimp-image-delete img))
(gimp-quit 0)
