(let* ((img (car (gimp-file-load RUN-NONINTERACTIVE "/home/kir/.codex/generated_images/01a0d813-b01b-7003-ac1a-13c396875d28/exec-4fa99ddc-7c38-4e53-8e1c-50dbcd503f5b.png" "/home/kir/.codex/generated_images/01a0d813-b01b-7003-ac1a-13c396875d28/exec-4fa99ddc-7c38-4e53-8e1c-50dbcd503f5b.png")))
(base (car (gimp-image-get-active-layer img)))
(top (car (gimp-layer-copy base TRUE)))
(rows (car (gimp-layer-copy base TRUE))))
(gimp-image-insert-layer img top 0 1)
(gimp-item-set-name top "Narrow top texture extension for headroom")
(gimp-layer-resize top 1672 1 0 0)
(gimp-context-set-interpolation INTERPOLATION-NOHALO)
(gimp-layer-scale top 1672 14 FALSE)
(gimp-image-insert-layer img rows 0 0)
(gimp-item-set-name rows "Unspecified casualty names softened to unreadable ink rows")
(gimp-image-select-rectangle img CHANNEL-OP-REPLACE 222 43 85 293)
(gimp-selection-feather img 3)
(plug-in-gauss RUN-NONINTERACTIVE img rows 1.8 1.8 1)
(let ((mask (car (gimp-layer-create-mask rows ADD-BLACK-MASK))))
(gimp-layer-add-mask rows mask)
(gimp-context-set-foreground '(255 255 255))
(gimp-edit-fill mask FOREGROUND-FILL))
(gimp-selection-none img)
(gimp-layer-set-offsets base 0 14)
(gimp-layer-set-offsets rows 0 14)
(gimp-image-scale img 1920 1080)
(gimp-xcf-save RUN-NONINTERACTIVE img rows "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/s039-northern-river-town/local-finish-master.xcf" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/s039-northern-river-town/local-finish-master.xcf")
(let ((flat (car (gimp-image-merge-visible-layers img CLIP-TO-IMAGE))))
(file-png-save RUN-NONINTERACTIVE img flat "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/renpy/game/art/scenes/s039-northern-river-town.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/renpy/game/art/scenes/s039-northern-river-town.png" 0 9 0 0 0 0 0))
(gimp-image-delete img))
(gimp-quit 0)
