(let* ((p "/home/kir/.codex/generated_images/01a0cf96-3dfc-7501-b20b-81a2b39d7ac6/exec-fd8beb2a-5383-45f6-bcfe-fb1aed5d8bfd.png")
       (img(car(gimp-file-load RUN-NONINTERACTIVE p p))) (base(car(gimp-image-get-active-layer img))))
 (gimp-item-set-name base "Coherent widened depth composition — native1672x941")
 (let ((gap(car(gimp-layer-new img 1672 941 RGBA-IMAGE "Local vertical split through existing eight-point pin" 100 NORMAL-MODE))))
  (gimp-image-insert-layer img gap 0 0)
  (gimp-drawable-fill gap TRANSPARENT-FILL)
  (gimp-context-set-brush "2. Hardness 100")
  (gimp-context-set-brush-size 1.65)
  (gimp-context-set-opacity 100)
  (gimp-clone gap base CLONE-IMAGE 509 286 4 (vector 523 286 527 309))
  (gimp-xcf-save RUN-NONINTERACTIVE img gap "visual-novel/art/scene-studies/s033-valcair-war-room/depth-composition-master.xcf" "visual-novel/art/scene-studies/s033-valcair-war-room/depth-composition-master.xcf"))
 (let ((flat(car(gimp-image-merge-visible-layers img CLIP-TO-IMAGE))))
  (file-png-save RUN-NONINTERACTIVE img flat "/tmp/s033-depth-corrected-native.png" "/tmp/s033-depth-corrected-native.png" 0 9 0 0 0 0 0)
  (gimp-image-crop img 1664 936 4 2)
  (gimp-context-set-interpolation INTERPOLATION-NOHALO)
  (gimp-image-scale img 1920 1080)
  (file-png-save RUN-NONINTERACTIVE img flat "/tmp/s033-depth-delivery.png" "/tmp/s033-depth-delivery.png" 0 9 0 0 0 0 0))
 (gimp-image-delete img))
(gimp-quit 0)
