(let* ((src "/home/kir/.codex/generated_images/01a0cf96-3dfc-7501-b20b-81a2b39d7ac6/exec-132db4f2-1226-40f5-b6b4-bb4054d39b8f.png")
 (patchsrc "/home/kir/.codex/generated_images/01a0cf96-3dfc-7501-b20b-81a2b39d7ac6/exec-0c3e7d00-790c-4327-b518-0eb60a323294.png")
 (img (car(gimp-file-load RUN-NONINTERACTIVE src src)))
 (base (car(gimp-image-get-active-layer img)))
 (patch (car(gimp-file-load-layer RUN-NONINTERACTIVE img patchsrc))))
 (gimp-item-set-name base "Fresh rectangular table scene — shifted down60px")
 (gimp-layer-set-offsets base 0 60)
 (gimp-image-insert-layer img patch 0 0)
 (gimp-item-set-name patch "Masked top extension, removed banner, loose papers and removed seal")
 (let ((mask(car(gimp-layer-create-mask patch ADD-BLACK-MASK))))
  (gimp-layer-add-mask patch mask)
  (gimp-image-select-rectangle img CHANNEL-OP-REPLACE 0 0 1672 65)
  (gimp-image-select-rectangle img CHANNEL-OP-ADD 62 50 210 342)
  (gimp-image-select-rectangle img CHANNEL-OP-ADD 410 387 245 99)
  (gimp-image-select-rectangle img CHANNEL-OP-ADD 1018 390 258 100)
  (gimp-image-select-rectangle img CHANNEL-OP-ADD 477 508 48 28)
  (gimp-selection-feather img 3)
  (gimp-context-set-foreground '(255 255 255))
  (gimp-edit-fill mask FOREGROUND-FILL)
  (gimp-selection-none img))
 (let ((cloth(car(gimp-layer-new img 1672 941 RGBA-IMAGE "Local plum cloth beneath fixed split-star" 100 NORMAL-MODE))))
  (gimp-image-insert-layer img cloth 0 0)
  (gimp-drawable-fill cloth TRANSPARENT-FILL)
  (gimp-context-set-brush "2. Hardness 050")
  (gimp-context-set-brush-size 28)
  (gimp-context-set-opacity 100)
  (let* ((simg(car(gimp-file-load RUN-NONINTERACTIVE patchsrc patchsrc))) (sl(car(gimp-image-get-active-layer simg))))
   (gimp-clone cloth sl CLONE-IMAGE 1154 312 2 (vector 1169 261))
   (gimp-image-delete simg)))
 (let ((star(car(gimp-file-load-layer RUN-NONINTERACTIVE img "visual-novel/art/prop-keys/emblems/northern-split-star.png"))))
  (gimp-image-insert-layer img star 0 0)
  (gimp-item-set-name star "Canonical split eight-point star; three bars remain original")
  (gimp-context-set-interpolation INTERPOLATION-NOHALO)
  (gimp-layer-scale star 26 38 FALSE)
  (gimp-layer-set-offsets star 1156 242)
  (gimp-xcf-save RUN-NONINTERACTIVE img star "visual-novel/art/scene-studies/s033-valcair-war-room/rectangular-table-repair-master.xcf" "visual-novel/art/scene-studies/s033-valcair-war-room/rectangular-table-repair-master.xcf"))
 (let ((flat(car(gimp-image-merge-visible-layers img CLIP-TO-IMAGE))))
  (file-png-save RUN-NONINTERACTIVE img flat "/tmp/s033-corrected-native.png" "/tmp/s033-corrected-native.png" 0 9 0 0 0 0 0)
  (gimp-image-scale img 1920 1080)
  (file-png-save RUN-NONINTERACTIVE img flat "visual-novel/renpy/game/art/scenes/s033-valcair-war-room.png" "visual-novel/renpy/game/art/scenes/s033-valcair-war-room.png" 0 9 0 0 0 0 0))
 (gimp-image-delete img))
(gimp-quit 0)
