(let* ((src "/home/kir/.codex/generated_images/01a0cf96-3dfc-7501-b20b-81a2b39d7ac6/exec-ebac11e1-9b06-4107-b45b-0c88dd29eda9.png")
       (patchsrc "/home/kir/.codex/generated_images/01a0cf96-3dfc-7501-b20b-81a2b39d7ac6/exec-a20aa116-2c4b-43da-9df3-eab7e4453607.png")
       (img (car (gimp-file-load RUN-NONINTERACTIVE src src)))
       (base (car (gimp-image-get-active-layer img))))
 (gimp-item-set-name base "Untouched seated composition; native1672x941 at100,64")
 (gimp-image-resize img 1872 1053 100 64)
 (let* ((patch (car (gimp-file-load-layer RUN-NONINTERACTIVE img patchsrc))))
  (gimp-image-insert-layer img patch 0 0)
  (gimp-context-set-interpolation INTERPOLATION-NOHALO)
  (gimp-layer-scale patch 1872 1053 FALSE)
  (gimp-layer-set-offsets patch 0 0)
  (gimp-item-set-name patch "Masked framing margins and banner removal")
  (let ((mask (car (gimp-layer-create-mask patch ADD-BLACK-MASK))))
   (gimp-layer-add-mask patch mask)
   (gimp-image-select-rectangle img CHANNEL-OP-REPLACE 106 70 1660 929)
   (gimp-selection-invert img)
   (gimp-image-select-rectangle img CHANNEL-OP-ADD 1629 60 151 228)
   (gimp-selection-feather img 4)
   (gimp-context-set-foreground '(255 255 255))
   (gimp-edit-fill mask FOREGROUND-FILL)
   (gimp-selection-none img))
  (let ((repair (car(gimp-layer-new img 1872 1053 RGBA-IMAGE "Local unsigned-paper repair preserving original edge" 100 NORMAL-MODE))))
   (gimp-image-insert-layer img repair 0 0)
   (gimp-drawable-fill repair TRANSPARENT-FILL)
   (gimp-image-select-ellipse img CHANNEL-OP-REPLACE 636 624 58 20)
   (gimp-selection-feather img 2)
   (gimp-context-set-brush "2. Hardness 075")
   (gimp-context-set-brush-size 80)
   (gimp-context-set-opacity 100)
   (let* ((simg(car(gimp-file-load RUN-NONINTERACTIVE src src))) (sl(car(gimp-image-get-active-layer simg))))
    (gimp-clone repair sl CLONE-IMAGE 500 569 2 (vector 665 634))
    (gimp-image-delete simg))
   (gimp-selection-none img))
  (gimp-xcf-save RUN-NONINTERACTIVE img patch "visual-novel/art/scene-studies/s033-valcair-war-room/seated-composition-master.xcf" "visual-novel/art/scene-studies/s033-valcair-war-room/seated-composition-master.xcf"))
 (let ((flat (car (gimp-image-merge-visible-layers img CLIP-TO-IMAGE))))
  (file-png-save RUN-NONINTERACTIVE img flat "/tmp/s033-seated-native.png" "/tmp/s033-seated-native.png" 0 9 0 0 0 0 0)
  (gimp-image-scale img 1920 1080)
  (file-png-save RUN-NONINTERACTIVE img flat "/tmp/s033-seated-final.png" "/tmp/s033-seated-final.png" 0 9 0 0 0 0 0))
 (gimp-image-delete img))
(gimp-quit 0)
