(define (source-delivery path)
 (let* ((im (car (gimp-file-load RUN-NONINTERACTIVE path path))) (flat (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE))))
 (gimp-context-set-interpolation INTERPOLATION-NOHALO)
 (gimp-image-crop im 1664 936 4 2) (gimp-image-scale im 1920 1080) im))
(let* ((im (source-delivery "visual-novel/art/scene-studies/s033-valcair-war-room/depth-composition-master.xcf"))
(base (car (gimp-image-get-active-layer im))) (ci (car (gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/s033-valcair-war-room/agreement-action-component.png" "visual-novel/art/scene-studies/s033-valcair-war-room/agreement-action-component.png")))
(l 0) (m 0) (flat 0))
(gimp-item-set-name base "Delivered rebuilt room; table, figures and exposure preserved")
(gimp-context-set-interpolation INTERPOLATION-NOHALO)
(gimp-image-crop ci 1664 936 4 2) (gimp-image-scale ci 448 252)
(set! l (car (gimp-layer-new-from-drawable (car (gimp-image-get-active-layer ci)) im)))
(gimp-image-insert-layer im l 0 -1) (gimp-layer-set-offsets l 425 332)
(gimp-item-set-name l "Only Vask hands, removed quill and thin agreement laid down")
(set! m (car (gimp-layer-create-mask l ADD-BLACK-MASK))) (gimp-layer-add-mask l m)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 34 #(442 429 471 407 504 363 525 357 566 384 611 436 664 426 688 412 725 415 746 444 755 461 849 463 852 512 742 534 636 526 520 516 454 500))
(gimp-selection-feather im 3) (gimp-edit-fill m WHITE-FILL) (gimp-selection-none im)
(gimp-image-select-polygon im CHANNEL-OP-REPLACE 12 #(642 507 700 495 726 507 726 549 643 562 632 536))
(gimp-selection-feather im 1) (gimp-context-set-foreground '(0 0 0)) (gimp-edit-fill m FOREGROUND-FILL) (gimp-selection-none im)
(gimp-image-select-ellipse im CHANNEL-OP-REPLACE 759 471 82 87)
(gimp-selection-feather im 2) (gimp-context-set-foreground '(0 0 0)) (gimp-edit-fill m FOREGROUND-FILL) (gimp-selection-none im)
(gimp-xcf-save RUN-NONINTERACTIVE im l "visual-novel/art/scene-studies/s033-valcair-war-room/agreement-action-correction-master.xcf" "visual-novel/art/scene-studies/s033-valcair-war-room/agreement-action-correction-master.xcf")
(set! flat (car (gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save RUN-NONINTERACTIVE im flat "/tmp/s033-agreement-candidate.png" "/tmp/s033-agreement-candidate.png" 0 9 0 0 0 0 0)
(gimp-image-delete ci) (gimp-image-delete im)) (gimp-quit 0)
