(gimp-context-push)
(let* ((img (car (gimp-file-load RUN-NONINTERACTIVE "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s034-return-cargo-shed/source.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s034-return-cargo-shed/source.png"))))
(gimp-item-set-name (car (gimp-image-get-active-layer img)) "Current source, Claude repairs preserved")
(let* ((ly (car (gimp-file-load-layer RUN-NONINTERACTIVE img "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s034-return-cargo-shed/guard-donor.png"))) (mask 0))
(gimp-image-insert-layer img ly 0 0)
(gimp-item-set-name ly "Third northern guard: green cap and compact horn")
(gimp-layer-scale ly 220 380 TRUE)
(gimp-layer-set-offsets ly 1660 160)
(set! mask (car (gimp-layer-create-mask ly ADD-BLACK-MASK)))
(gimp-layer-add-mask ly mask)
(gimp-image-select-polygon img CHANNEL-OP-REPLACE 10 (vector 1817 251 1841 250 1842 286 1823 285 1817 278))
(gimp-selection-feather img 0.8)
(gimp-context-set-foreground "white")
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none img)
)
(let* ((ly (car (gimp-file-load-layer RUN-NONINTERACTIVE img "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s034-return-cargo-shed/guard-donor.png"))) (mask 0))
(gimp-image-insert-layer img ly 0 0)
(gimp-item-set-name ly "Third northern guard: green coat")
(gimp-layer-scale ly 220 380 TRUE)
(gimp-layer-set-offsets ly 1660 160)
(set! mask (car (gimp-layer-create-mask ly ADD-BLACK-MASK)))
(gimp-layer-add-mask ly mask)
(gimp-image-select-polygon img CHANNEL-OP-REPLACE 18 (vector 1831 314 1843 311 1843 411 1833 423 1826 403 1830 377 1830 356 1824 346 1827 331))
(gimp-selection-feather img 0.8)
(gimp-context-set-foreground "white")
(gimp-edit-fill mask FOREGROUND-FILL)
(gimp-selection-none img)
)
(gimp-xcf-save RUN-NONINTERACTIVE img (car (gimp-image-get-active-layer img)) "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s034-return-cargo-shed/master.xcf" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s034-return-cargo-shed/master.xcf")
(let* ((dup (car (gimp-image-duplicate img))))
(gimp-image-merge-visible-layers dup CLIP-TO-IMAGE)
(file-png-save RUN-NONINTERACTIVE dup (car (gimp-image-get-active-layer dup)) "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s034-return-cargo-shed/candidate.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s034-return-cargo-shed/candidate.png" 0 9 0 0 0 0 0)
(gimp-image-crop dup 220 380 1660 160)
(file-png-save RUN-NONINTERACTIVE dup (car (gimp-image-get-active-layer dup)) "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s034-return-cargo-shed/after-native.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s034-return-cargo-shed/after-native.png" 0 9 0 0 0 0 0)
(gimp-image-delete dup))
(gimp-image-delete img))
(let* ((re (car (gimp-file-load RUN-NONINTERACTIVE "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s034-return-cargo-shed/master.xcf" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s034-return-cargo-shed/master.xcf"))))
(gimp-image-merge-visible-layers re CLIP-TO-IMAGE)
(file-png-save RUN-NONINTERACTIVE re (car (gimp-image-get-active-layer re)) "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s034-return-cargo-shed/reopened.png" "/home/kir/Documents/Projects/the-ending-we-never-got/visual-novel/art/scene-studies/batch8-minor-details/s034-return-cargo-shed/reopened.png" 0 9 0 0 0 0 0)
(gimp-image-delete re))
(gimp-context-pop)
(gimp-quit 0)
