(let* ((im(car(gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/s054-binding/action-rebuild.png" "visual-novel/art/scene-studies/s054-binding/action-rebuild.png")))(bg 0)(f 0)(base 0)(m 0))
(set! base(car(gimp-image-get-active-layer im)))(gimp-item-set-name base "Reviewed right-hand care and incoming wounded, native scale")
(gimp-image-resize im 2240 1260 284 160)
(set! m(car(gimp-layer-create-mask base ADD-BLACK-MASK)))(gimp-layer-add-mask base m)
(gimp-image-select-rectangle im CHANNEL-OP-REPLACE 308 182 1624 874)
(gimp-selection-feather im 20)(gimp-edit-fill m WHITE-FILL)(gimp-selection-none im)
(set! bg(car(gimp-file-load-layer RUN-NONINTERACTIVE im "visual-novel/art/scene-studies/s054-binding/peripheral-donor.png")))
(gimp-image-insert-layer im bg 0 (car(gimp-image-get-layers im)))(gimp-layer-scale bg 2240 1260 TRUE)(gimp-layer-set-offsets bg 0 0)
(gimp-item-set-name bg "Peripheral hall, Olan headroom and completed boot")
(gimp-xcf-save RUN-NONINTERACTIVE im base "visual-novel/art/scene-studies/s054-binding/delivery-master.xcf" "visual-novel/art/scene-studies/s054-binding/delivery-master.xcf")
(set! f(car(gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save RUN-NONINTERACTIVE im f "visual-novel/art/scene-studies/s054-binding/candidate.png" "visual-novel/art/scene-studies/s054-binding/candidate.png" 0 9 0 0 0 0 0)
(gimp-image-delete im))(gimp-quit 0)
