(let* ((im(car(gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/s054-binding/peripheral-donor.png" "visual-novel/art/scene-studies/s054-binding/peripheral-donor.png")))(l 0))
(set! l(car(gimp-image-get-active-layer im)))(gimp-item-set-name l "Complete re-rendered care scene: final framing and right-hand action")
(gimp-xcf-save RUN-NONINTERACTIVE im l "visual-novel/art/scene-studies/s054-binding/native-master.xcf" "visual-novel/art/scene-studies/s054-binding/native-master.xcf")
(gimp-image-scale im 1920 1081)(gimp-image-resize im 1920 1080 0 0)(gimp-layer-resize-to-image-size l)
(gimp-xcf-save RUN-NONINTERACTIVE im l "visual-novel/art/scene-studies/s054-binding/delivery-master.xcf" "visual-novel/art/scene-studies/s054-binding/delivery-master.xcf")
(file-png-save RUN-NONINTERACTIVE im l "visual-novel/art/scene-studies/s054-binding/candidate.png" "visual-novel/art/scene-studies/s054-binding/candidate.png" 0 9 0 0 0 0 0)(gimp-image-delete im))
(let* ((im(car(gimp-file-load RUN-NONINTERACTIVE "visual-novel/art/scene-studies/s054-binding/delivery-master.xcf" "visual-novel/art/scene-studies/s054-binding/delivery-master.xcf")))(l 0))
(set! l(car(gimp-image-merge-visible-layers im CLIP-TO-IMAGE)))
(file-png-save RUN-NONINTERACTIVE im l "/tmp/s054-binding-reopened.png" "/tmp/s054-binding-reopened.png" 0 9 0 0 0 0 0)(gimp-image-delete im))(gimp-quit 0)
