(define (patch img donor name w h ox oy points feather)
  (let* ((layer (car (gimp-file-load-layer RUN-NONINTERACTIVE img donor))) (mask 0))
    (gimp-image-insert-layer img layer 0 0)
    (gimp-item-set-name layer name)
    (gimp-layer-scale layer w h FALSE)
    (gimp-layer-set-offsets layer ox oy)
    (set! mask (car (gimp-layer-create-mask layer ADD-BLACK-MASK)))
    (gimp-layer-add-mask layer mask)
    (gimp-image-select-polygon img CHANNEL-OP-REPLACE (vector-length points) points)
    (if (> feather 0) (gimp-selection-feather img feather))
    (gimp-context-set-foreground '(255 255 255))
    (gimp-edit-fill mask FOREGROUND-FILL)
    (gimp-selection-none img)
    layer))
(define (finish img stem)
  (gimp-xcf-save RUN-NONINTERACTIVE img (car (gimp-image-get-active-layer img)) (string-append stem ".xcf") (string-append stem ".xcf"))
  (let* ((copy (car (gimp-image-duplicate img))) (merged (car (gimp-image-merge-visible-layers copy CLIP-TO-IMAGE))))
    (file-png-save RUN-NONINTERACTIVE copy merged (string-append stem ".png") (string-append stem ".png") 0 9 0 0 0 0 0)
    (gimp-image-delete copy))
  (gimp-image-delete img)
  (let* ((reopen (car (gimp-file-load RUN-NONINTERACTIVE (string-append stem ".xcf") (string-append stem ".xcf")))) (merged (car (gimp-image-merge-visible-layers reopen CLIP-TO-IMAGE))))
    (file-png-save RUN-NONINTERACTIVE reopen merged (string-append stem "-reopened.png") (string-append stem "-reopened.png") 0 9 0 0 0 0 0)
    (gimp-image-delete reopen)))
